### ISSUE TITLE
cgroups v2  incompatibility issue ? 

### ISSUE THREAD

**Issue by matzew** [containers/libpod#6113] opened 2020-05-07 09:38 UTC
/kind bug

/kind feature

**Description**

**Steps to reproduce the issue:**

1. running the openshift/release repo target `jobs`
https://github.com/openshift/release/blob/master/Makefile#L49-L53

I get:

```
make jobs
docker pull registry.svc.ci.openshift.org/ci/ci-operator-prowgen:latest
Trying to pull registry.svc.ci.openshift.org/ci/ci-operator-prowgen:latest...
Getting image source signatures
Copying blob 524b0c1e57f8 skipped: already exists  
Copying blob 2b5515f617f5 done  
Copying config 3eba4c8c18 done  
Writing manifest to image destination
Storing signatures
3eba4c8c18137ff052fd30ce76aa3960f0aff3c3fa54979ac9cd16c0e5675157
docker run --rm -v "/home/matzew/go/src/github.com/openshift/release:/go/src/github.com/openshift/release:z" -e GOPATH=/go registry.svc.ci.openshift.org/ci/ci-operator-prowgen:latest --from-release-repo --to-release-repo
Error: invalid configuration, cannot specify resource limits without cgroups v2 and --cgroup-manager=systemd
make: *** [Makefile:42: jobs] Error 125
```

**Output of `podman version`:**

```
podman version
Version:            1.9.1
RemoteAPI Version:  1
Go Version:         go1.14.2
OS/Arch:            linux/amd64
```

**Output of `docker info`:**

```
docker info
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.14-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.14, commit: a08df20e61ed6795fd25cc9e27ef452cf3259c06'
  cpus: 8
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: linux.fritz.box
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.6.7-300.fc32.x86_64
  memFree: 14432448512
  memTotal: 33504034816
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.0.0-1.fc32.x86_64
    version: |-
      slirp4netns version 1.0.0
      commit: a3be729152a33e692cd28b52f664defbf2e7810a
      libslirp: 4.2.0
  swapFree: 16848252928
  swapTotal: 16852709376
  uptime: 146h 19m 10.42s (Approximately 6.08 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/matzew/.config/containers/storage.conf
  containerStore:
    number: 81
    paused: 0
    running: 0
    stopped: 81
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.8-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 0.7.8
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/matzew/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 903
  runRoot: /run/user/1000
  volumePath: /home/matzew/.local/share/containers/storage/volumes
```

**Comment by mheon** [comment] 2020-05-07 13:47
Dupe of #6084 I believe. Closing as such. If you disagree, we can reopen.

**Closed by mheon** 2020-05-07 13:47 UTC
Labels: kind/bug, kind/feature
