### ISSUE TITLE
podman varlink unknown flag: --timeout

### ISSUE THREAD

**Issue by adoyle-h** [containers/libpod#4529] opened 2019-11-18 09:06 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman varlink unknown flag: --timeout

**Steps to reproduce the issue:**

1. `brew cask intall podman`

2. `sudo podman varlink --log-level debug --timeout 0 unix://run/podman/io.podman`

**Describe the results you received:**

ERRO[0000] unknown flag: --timeout

**Describe the results you expected:**

Same to [Podman node setup](https://github.com/containers/libpod/blob/master/docs/tutorials/mac_client.md#podman-node-setup)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:
Version:            1.6.1-dev
RemoteAPI Version:  1
Go Version:         go1.12.9
OS/Arch:            darwin/amd64

Service:
Error: could not get runtime: dial unix /run/podman/io.podman: connect: no such file or directory
```

**Output of `podman info --debug`:**

```
Error: could not get runtime: dial unix /run/podman/io.podman: connect: no such file or directory
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
> brew cask info podman
podman: 1.6.0-28-gdac7889d
https://github.com/containers/libpod/
/usr/local/Caskroom/podman/1.6.0-28-gdac7889d (2 files, 47.4MB)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/podman.rb
==> Name
podman
==> Artifacts
podman-v1.6.0-28-gdac7889d/podman (Binary)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- MacBook Pro 10.15.1
- GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin19.0.0)

**Comment by baude** [comment] 2019-11-18 15:29
you cannot run the varlink service with the mac remote client.  though i am surprised it didnt choke on the varlink command.  ill take a look at that.

**Comment by baude** [comment] 2019-11-18 15:40
Ok what you are seeing is an artifact of how the cobra package works.  it is processing the flag first, but in reality there is no podman varlink command for the mac client.  closing as this is not a bug.

**Closed by baude** 2019-11-18 15:40 UTC
Labels: kind/bug
