### ISSUE TITLE
Static podman

### ISSUE THREAD

**Issue by jwendell** [containers/libpod#1399] opened 2018-09-02 19:52 UTC
Is it possible to build a static version of podman?

The use case would be to easily use podman in a machine with cri-o, in order to see/interact/debug running containers and inspect images in the cri-o host. Then one could just copy the podman binary into the host.

My particular use case: I'm trying to inspect containers in a minikube VM (started with --container-runtime=cri-o). Is there a better way to do that?

/kind feature

**Comment by mheon** [comment] 2018-09-02 19:59
You might want to investigate crictl for debugging CRI-O in that scenario.
You might run into similar problems with static binaries though.

As for building Podman statically, I don't think anyone has ever looked
into that. It sounds like it should be possible, though.

**Comment by rhatdan** [comment] 2018-09-03 10:38
We have a PR To make buildah staticly linked.  Which I need to get back to.  
If you have CRI-O on a system you might be able to just take podman executable (as long as it was built for the same OS and run it, without requiring it to be static.  Problems might happen because of conflicting versions of conmon though.

Which arch are you running with CRI-O?

**Comment by mheon** [comment] 2018-09-04 12:55
@rhatdan brings up another point - we rely on specific conmon commits for Podman, which often differ from CRI-O, causing us to ship our own version. You can't just copy the static Podman over as such - you'd need to provide `conmon` as well.

**Comment by rhatdan** [comment] 2018-09-04 14:14
Does  you system not have a libselinux.so.1 package?  What OS are you doing this on?

**Comment by jwendell** [comment] 2018-09-05 14:45
@rhatdan it's minikube. I don't know which distro they use, probably a custom one built with Buildroot? (based on the contents of /etc/os-release, see above)

**Comment by rhatdan** [comment] 2018-09-05 15:27
Well the podman was built on a different system, since it thinks it needs selinux.

**Comment by jwendell** [comment] 2018-09-05 15:58
@rhatdan yep, I know. I grabbed the f28 version. That's why I opened this RFE so that we can have a statically linked podman that I can copy over machines and start using it right away!

**Comment by rhatdan** [comment] 2018-12-22 12:01
We built a static buildah command, on Fedora, but it seems to crash randomly.  I am not sure that Fedora static librarie work real well.  What OS is static docker built on?

**Comment by rhatdan** [comment] 2019-01-06 22:38
I'm fine with that if it actually works.  We can add content to the Makefile to attempt to build podman statically.

**Comment by afbjorklund** [comment] 2019-01-07 17:48
Well, it's not really "static podman" so it is a bit off-topic here... But the original author said he was using `minikube` so thought it was worth mentioning ? It would be nice if they were faster to update it, though.

``` console
$ minikube version
minikube version: v0.32.0
$ minikube ssh
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ podman --version
WARN[0000] unable to find /etc/containers/registries.conf. some podman (image shortnames) commands may be limited 
podman version 0.4.1
$ 
```
https://github.com/kubernetes/minikube/releases/tag/v0.32.0
https://github.com/containers/libpod/releases/tag/v0.4.1

**Comment by pwFoo** [comment] 2019-03-06 22:17
Anyway progress with static build? Looks like current build wouldn't Run with alpine linux?

**Comment by pwFoo** [comment] 2019-03-08 22:22
During testing I noticed that more than the podman binary is needed to pull and run containers? There are some dependencies / recommended plugins.
- podman
- cni plugins / iptables 
- buildah (only needed to build images?)
- conmon
- ...

So what is the minimal podman install requirement to pull images and run containers (with network support)?

**Comment by mheon** [comment] 2019-03-08 23:15
We don't depend on Buildah, it's vendored into our codebase.

The minimum required packages for running Podman as root would be Podman, the CNI plugins (and IPTables for firewall rules), and Conmon.

For running Podman as rootless, the CNI plugins are replaced by slirp4netns.

If you wish to do both, we need both slirp and the CNI plugins

**Comment by pwFoo** [comment] 2019-03-09 07:45
@mheon 
Thanks! I'll test it. 
Which CNI plugin(s) is needed to run containers as root?

**Comment by pwFoo** [comment] 2019-03-09 10:11
iptables needs some more modules than docker / k3s
```
ERRO[0001] Error adding network: running [/usr/sbin/iptables -t nat -C CNI-1dd127f5293ca155ce3f87cc -d 10.88.0.0/16 -j ACCEPT -m comment --comment name: "podman" id: "ea5861a381db5fb240248ebd2de97987415090e95e1d1353d3914d4e0b1dd45a"y

Try `iptables -h' or 'iptables --help' for more information.
 
ERRO[0001] Error while adding pod to CNI network "podman": running [/usr/sbin/iptables -t nat -C CNI-1dd127f5293ca155ce3f87cc -d 10.88.0.0/16 -j ACCEPT -m comment --comment name: "podman" id: "ea5861a381db5fb240248ebd2de97987415090ey

Try `iptables -h' or 'iptables --help' for more information.
```

Start a container with `--net=host` has systemd dependency?
```
# podman run --rm -ti --net=host alpine sh
Trying to pull docker.io/alpine:latest...Getting image source signatures
Copying blob 8e402f1a9c57: 2.63 MiB / 2.63 MiB  2s
Copying config 5cb3aa00f899: 1.48 KiB / 1.48 KiB  0s
Writing manifest to image destination
Storing signatures
container create failed: systemd cgroup flag passed, but systemd support for managing cgroups is not available
: internal libpod error
```

cni plugins are many and increase the size of needed files / dependencies
```
# ls -lh /usr/libexec/cni/
total 46184
-rwxr-xr-x    1 root     root        4.1M Mar  9 09:04 bridge
-rwxr-xr-x    1 root     root       10.3M Mar  9 09:04 dhcp
-rwxr-xr-x    1 root     root        2.8M Mar  9 09:04 flannel
-rwxr-xr-x    1 root     root        3.2M Mar  9 09:04 host-local
-rwxr-xr-x    1 root     root        3.7M Mar  9 09:04 ipvlan
-rwxr-xr-x    1 root     root        3.2M Mar  9 09:04 loopback
-rwxr-xr-x    1 root     root        3.7M Mar  9 09:04 macvlan
-rwxr-xr-x    1 root     root        3.6M Mar  9 09:05 portmap
-rwxr-xr-x    1 root     root        4.1M Mar  9 09:04 ptp
-rwxr-xr-x    1 root     root        2.9M Mar  9 09:05 tuning
-rwxr-xr-x    1 root     root        3.7M Mar  9 09:04 vlan
```
```
# ls -lh /usr/local/bin/ /usr/libexec/podman/
/usr/libexec/podman/:
total 3572
-rwxr-xr-x    1 root     root        3.5M Mar  9 09:04 conmon

/usr/local/bin/:
total 40056
-rwxr-xr-x    1 root     root       32.3M Mar  9 09:03 podman
-rwxr-xr-x    1 root     root        6.8M Mar  9 08:57 runc
```

podman, runc and conmon: 42,5MB (static builds)
CNI plugins: 45,3MB
all together: **87,8MB**

Tried to reduze the size of an custom image / initrd, but difference is minimal to docker?

**Comment by pwFoo** [comment] 2019-03-09 10:15
With iptables comment the iptables error is gone, but the systemd dependency still kills the container.
```
container create failed: systemd cgroup flag passed, but systemd support for managing cgroups is not available
: internal libpod error
```

**Comment by mheon** [comment] 2019-03-09 13:59
Change your CGroup manager from systemd to cgroupfs in libpod.conf and you
won't need systemd

**Comment by afbjorklund** [comment] 2019-03-09 14:12
There's a list in dependencies here, but has pretty much the same findings as above...
https://github.com/boot2podman/boot2podman/blob/master/building_podman.md

The CNI plugins are mostly big due to the static linking and nature of Go programs.
Doing a fully static build (without libc) would probably make everything even bigger ?

**Comment by pwFoo** [comment] 2019-03-10 13:58
Is it possible to have some plugins (local container networking comparable to docker) builtin to podman binary? AS done with kernel modules?

**Comment by mheon** [comment] 2019-03-10 15:54
Not without extensive refactoring work on the CNI plugins themselves.

If you're willing to accept some sacrifices in performance and functionality, you can potentially drop the CNI plugins for slirp4netns for root networking as well. We don't support doing this by default now, but it wouldn't be particularly difficult to enable, and the binary size of slirp is much smaller (it also doesn't depend on IPTables). The downside is that you lose a lot of flexibility in networking.

**Comment by pwFoo** [comment] 2019-03-10 16:34
At the moment I have removed not needed plugins and files.
```
/etc/containers/:
-rw-r--r--    1 root     root        3.7K Mar 10 13:55 libpod.conf
-rw-r--r--    1 root     root         256 Mar 10 13:54 policy.json
-rw-r--r--    1 root     root         890 Mar 10 13:54 registries.conf

/usr/libexec/cni/:
-rwxr-xr-x    1 root     root        4.1M Mar  9 09:04 bridge
-rwxr-xr-x    1 root     root        3.2M Mar  9 09:04 host-local
-rwxr-xr-x    1 root     root        3.2M Mar  9 09:04 loopback
-rwxr-xr-x    1 root     root        3.6M Mar  9 09:05 portmap

/usr/local/bin/:
lrwxrwxrwx    1 root     root           6 Mar 10 13:55 docker -> podman
-rwxr-xr-x    1 root     root       32.3M Mar  9 09:03 podman
-rwxr-xr-x    1 root     root        6.8M Mar  9 08:57 runc

usr/libexec/podman/:
-rwxr-xr-x    1 root     root        3.5M Mar  9 09:04 conmon
```

At the moment I just use podman to run containers like with docker (container network, --net=host, privileged or single cap_add's). Maybe docker in podman optional.
If the performance isn't to bad maybe it could be an option with slirp4netns...

**Comment by rhatdan** [comment] 2019-04-13 09:19
Would a podman container help?

**Comment by pwFoo** [comment] 2019-04-13 09:41
A minimal or different feature set / use cases podman image would be nice to play with and see dependencies

**Comment by afbjorklund** [comment] 2019-04-13 10:25
The k3s distribution makes the CNI binaries smaller, by using a "busybox"-like method:

https://github.com/rancher/k3s/blob/master/cmd/cni/main.go#L15

That is, there is only one `cni` binary implementing _all_ of the currently known plugins...

Similarly there is one `k3s` that implements all of kubernetes (including crictl and kubectl)

----

This enables [boot2podman](https://boot2podman.github.io/) to fit linux + podman + buildah + crio + k3s onto a 175M image.

The default networking for it now uses `flannel` (VXLAN), to enable multi-node support...

**Comment by pwFoo** [comment] 2019-05-21 16:26
@rhatdan 
> Would a podman container help?
Any progress with a podman container? A minimal build / setup dockerfile and image would help as starting point.

**Comment by TomSweeneyRedHat** [comment] 2019-05-21 16:44
@pwfoo I've put together an initial PR #3156, however, the resulting image is having an unexpected EPERM error that I'm trying to track down.

**Comment by pwFoo** [comment] 2019-05-23 17:33
Hi @TomSweeneyRedHat, I tried that dockerfile and it worked for me. But it's 1.0 instead of latest release.
https://github.com/mgoltzsche/podman-static

I changed podman version to 1.3.1, but get an error now.
```
Error: error creating libpod runtime: failed to get new shm lock manager: failed to create 2048 locks in /libpod_lock: no such file or directory
```

Just changed runc (rc6 -> rc8) and podman (1.0.0 -> 1.3.1) version. I think it's podman related?

Maybe the dockerfile helps? 

I modified the 1.0.0 build to reduce size like that (removed skopeo, some plugins)):
```
COPY    --from=runc   /usr/local/bin/runc   /mnt/usr/local/bin/runc                                                                                     
COPY    --from=podman /usr/local/bin/podman /mnt/usr/local/bin/podman                                                                                   
COPY    --from=conmon /usr/libexec/podman/conmon /mnt/usr/libexec/podman/conmon                                                                         
COPY    --from=cniplugins /usr/libexec/cni /mnt/usr/libexec/cni                                                                                         
#COPY   --from=skopeo /usr/local/bin/skopeo /mnt/usr/local/bin/skopeo                                                                                   
#COPY   --from=fuse-overlayfs /usr/bin/fuse-overlayfs /mnt/usr/local/bin/fuse-overlayfs                                                                 
#COPY   --from=slirp4netns /slirp4netns/slirp4netns /mnt/usr/local/bin/slirp4netns                                                                      
#COPY   --from=buildah /usr/local/bin/buildah /mnt/usr/local/bin/buildah                                                                                
                                                                                                                                                                   
RUN     wget -O /mnt/etc/containers/registries.conf https://raw.githubusercontent.com/projectatomic/registries/master/registries.fedora                 
RUN     wget -O /mnt/etc/containers/policy.json     https://raw.githubusercontent.com/containers/skopeo/master/default-policy.json                      
RUN     wget -O /mnt/etc/cni/net.d/99-bridge.conflist https://raw.githubusercontent.com/containers/libpod/master/cni/87-podman-bridge.conflist          
                                                                                                                                                        
RUN     wget -O /mnt/etc/containers/libpod.conf https://raw.githubusercontent.com/containers/libpod/36df2e70738ab277699e8240f62355a67a6b2edb/libpod.conf
RUN     sed -i 's/cgroup_manager =.*/cgroup_manager = "cgroupfs"/' /mnt/etc/containers/libpod.conf
RUN     sed -i 's/#namespace = ""/namespace = "default"/' /mnt/etc/containers/libpod.conf
                                          
                                                                   
WORKDIR /mnt/usr/libexec/cni                                          
                                                                                                                
RUN     rm -f \                                                
        flannel \                                                    
        ipvlan \                                                                                             
        macvlan \                                                                 
        ptp \                                                           
        vlan \                            
        dhcp \                                                                                                                         
        tuning                                                                                                                 
```

**Comment by Ciantic** [comment] 2019-07-18 15:03
Reason I'm interested on this is that if I can build podman statically in docker container, I should be able to copy the binaries out of the docker container to my host Raspberry Pi 4. This way I could install podman to raspbian without messing my host the Raspberry Pi.

Does anyone in this thread know which binaries I should copy out of the https://github.com/mgoltzsche/podman-static container to my host machine so I can get podman?

**Comment by ThomasSchoenbeck** [comment] 2019-07-22 15:34
> Any progress with static build? Looks like current build wouldn't Run with alpine linux?

even after installing libselinux it doesn't run on alpine. the missing file is now avaiable in /lib but podman doesn't care

**Comment by rhatdan** [comment] 2019-07-23 10:28
Only reason libselinux is needed is for ostree, eliminate that from the build and you should be fine.

**Comment by vrothberg** [comment] 2019-10-02 12:00
@rhatdan, is this something we want to support? The issue is quite old.

**Comment by rhatdan** [comment] 2019-10-02 13:32
Only if community wants to generate and support it.  For now we can close this.  If someone wants to step up and modify the Makefile to handle it and provide a way for people to retrieve static builds, I would not prevent it.

**Closed by rhatdan** 2019-10-02 13:32 UTC
Labels: question
