### ISSUE TITLE
podman: ping from inside container stalls/fails on third successive run

### ISSUE THREAD

**Issue by mike-nguyen** [containers/libpod#2837] opened 2019-04-02 22:32 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If ping is ran three times in a row from inside a container, it will fail the third time.  If I try again right after the ping failure, it will continue to fail.  If I wait a few seconds before running the command in the reproducer, it will run two times successfully and fail the third time again.  There seems to be some kind of rate limiting?  This happens on several containers but the example below is using busybox.  Running `echo hello` from the container consecutively works regardless of how many times I run it. 

The previous Fedora Atomic Host release (Fedora-AtomicHost-29-20190318.0) did not have this problem.  I isolated the change down to the kernel bump from `kernel 4.20.15-200.fc29 -> 5.0.4-200.fc29`.  The problem goes away if I install the older kernel.  Docker does not have this same issue (see output at the very end).

**Steps to reproduce the issue:**

1.  Start up Fedora-AtomicHost-29-20190401.0.  Found here:
https://kojipkgs.fedoraproject.org/compose/updates/Fedora-29-updates-20190401.0/compose/AtomicHost/x86_64/images/Fedora-AtomicHost-29-20190401.0.x86_64.qcow2
2. `for i in {1..3}; do sudo podman run --rm docker.io/busybox ping -c 3 1.1.1.1; sleep 1; done`

**Describe the results you received:**
Ping stops working on third iteration

**Describe the results you expected:**
Ping always works

**Additional information you deem important (e.g. issue happens only occasionally):**
It happens every time.

**Output of `podman version`:**

```
$ podman --version
podman version 1.1.2
```

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: a95a49d3038462d033f84ac314ec8a3064a99cff
  go version: go1.11.5
  podman version: 1.1.2
host:
  BuildahVersion: 1.7.1
  Conmon:
    package: podman-1.1.2-1.git0ad9b6b.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: a95a49d3038462d033f84ac314ec8a3064a99cff'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 1641713664
  MemTotal: 2087198720
  OCIRuntime:
    package: runc-1.0.0-68.dev.git6635b4f.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ef9132178ccc3d2775d4fb51f1e431f30cac1398-dirty
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: fedora
  kernel: 5.0.4-200.fc29.x86_64
  os: linux
  rootless: true
  uptime: 6m 20.73s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /var/home/cloud-user/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/cloud-user/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /run/user/1000
  VolumePath: /var/home/cloud-user/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
My environment is libvirt

```
$ sudo rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora-atomic:fedora/29/x86_64/atomic-host
                   Version: 29.20190401.0 (2019-04-01T01:48:44Z)
                    Commit: a39e99a72c80c9c4a8fce8a2092b2856f742a5c3ba5c9bedd59a9e76aa3e9924
              GPGSignature: Valid signature by 5A03B4DD8254ECA02FDA1637A20AA56B429476B4
```
```
$ while true; do sudo podman run --rm docker.io/busybox ping -c 3  192.168.0.6; sleep 1;  done
PING 192.168.0.6 (192.168.0.6): 56 data bytes
64 bytes from 192.168.0.6: seq=0 ttl=63 time=0.217 ms
64 bytes from 192.168.0.6: seq=1 ttl=63 time=0.567 ms
64 bytes from 192.168.0.6: seq=2 ttl=63 time=0.619 ms

--- 192.168.0.6 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.217/0.467/0.619 ms
PING 192.168.0.6 (192.168.0.6): 56 data bytes
64 bytes from 192.168.0.6: seq=0 ttl=63 time=0.244 ms
64 bytes from 192.168.0.6: seq=1 ttl=63 time=0.459 ms
64 bytes from 192.168.0.6: seq=2 ttl=63 time=0.491 ms

--- 192.168.0.6 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.244/0.398/0.491 ms
PING 192.168.0.6 (192.168.0.6): 56 data bytes

--- 192.168.0.6 ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss
```

```
$ while true; do sudo docker run --rm docker.io/busybox ping -c 3 1.1.1.1;  done
Unable to find image 'docker.io/busybox:latest' locally
Trying to pull repository docker.io/library/busybox ... 
sha256:061ca9704a714ee3e8b80523ec720c64f6209ad3f97c0ff7cb9ec7d19f15149f: Pulling from docker.io/library/busybox
697743189b6d: Pull complete 
Digest: sha256:061ca9704a714ee3e8b80523ec720c64f6209ad3f97c0ff7cb9ec7d19f15149f
Status: Downloaded newer image for docker.io/busybox:latest
PING 1.1.1.1 (1.1.1.1): 56 data bytes
64 bytes from 1.1.1.1: seq=0 ttl=56 time=15.628 ms
64 bytes from 1.1.1.1: seq=1 ttl=56 time=50.852 ms
64 bytes from 1.1.1.1: seq=2 ttl=56 time=18.886 ms

--- 1.1.1.1 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 15.628/28.455/50.852 ms
PING 1.1.1.1 (1.1.1.1): 56 data bytes
64 bytes from 1.1.1.1: seq=0 ttl=56 time=19.105 ms
64 bytes from 1.1.1.1: seq=1 ttl=56 time=28.000 ms
64 bytes from 1.1.1.1: seq=2 ttl=56 time=22.905 ms

--- 1.1.1.1 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 19.105/23.336/28.000 ms
PING 1.1.1.1 (1.1.1.1): 56 data bytes
64 bytes from 1.1.1.1: seq=0 ttl=56 time=14.627 ms
64 bytes from 1.1.1.1: seq=1 ttl=56 time=23.661 ms
64 bytes from 1.1.1.1: seq=2 ttl=56 time=18.578 ms

--- 1.1.1.1 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 14.627/18.955/23.661 ms
PING 1.1.1.1 (1.1.1.1): 56 data bytes
64 bytes from 1.1.1.1: seq=0 ttl=56 time=17.236 ms
64 bytes from 1.1.1.1: seq=1 ttl=56 time=18.873 ms
64 bytes from 1.1.1.1: seq=2 ttl=56 time=18.932 ms
```

**Comment by mheon** [comment] 2019-04-02 22:44
Suspicion: overlapping processes (Podman cleanup processes and the fresh Podman processes being run in the loop) are racing, and CNI ends up removing network state necessary for the new container being run. @mccv1r0 is there any locking in CNI that would prevent multiple processes running at the same time from overwriting each other?

**Comment by rhatdan** [comment] 2019-04-03 12:04
Weird I can get this to happen once. Even upping the odds.

 do sudo podman run --rm docker.io/busybox ping -c 1 1.1.1.1; sleep 1; done

**Comment by rhatdan** [comment] 2019-04-03 12:05
@mike-nguyen One thing to try is with a --net=host, to make sure it is the network stack that is causing the issue.  I am pretty sure, but just to make sure.

**Comment by mike-nguyen** [comment] 2019-04-03 12:20
@rhatdan it works fine with `--net=host`

**Comment by mike-nguyen** [comment] 2019-04-03 12:28
> Weird I can get this to happen once. Even upping the odds.
> 
> do sudo podman run --rm docker.io/busybox ping -c 1 1.1.1.1; sleep 1; done

@rhatdan You can or can't?

This issue only occurs on `kernel 5.0.4-200.fc29`.  If downgrade to `kernel 4.20.15-200.fc29` it works again.

**Comment by mccv1r0** [comment] 2019-04-03 15:15
> Suspicion: overlapping processes (Podman cleanup processes and the fresh Podman processes being run in the loop) are racing, and CNI ends up removing network state necessary for the new container being run. @mccv1r0 is there any locking in CNI that would prevent multiple processes running at the same time from overwriting each other?

For e.g. host-local IPAM address allocation, yes, there are locks to serialize access so that containers don't get e.g. the same IP address.

**Comment by rhatdan** [comment] 2019-04-03 21:35
Could this be a kernel bug?

**Comment by giuseppe** [comment] 2019-04-04 16:59
might be in the kernel.  It seems to get confused by the same destination IP address used by the 3 containers.

@mike-nguyen could you try something like:
```
for i in 1.1.1.1 8.8.8.8 9.9.9.9; do sudo podman run --rm docker.io/busybox ping -c 3 $i; sleep 1; done
```
?

**Comment by mccv1r0** [comment] 2019-04-04 17:16
> might be in the kernel. It seems to get confused by the same destination IP address used by the 3 containers.

Wouldn't docker have the same issue?

**Comment by mike-nguyen** [comment] 2019-04-04 18:39
> might be in the kernel. It seems to get confused by the same destination IP address used by the 3 containers.
> 
> @mike-nguyen could you try something like:
> 
> ```
> for i in 1.1.1.1 8.8.8.8 9.9.9.9; do sudo podman run --rm docker.io/busybox ping -c 3 $i; sleep 1; done
> ```
> ?

@giuseppe that worked!
```
[cloud-user@fedora ~]$ for i in 1.1.1.1 8.8.8.8 9.9.9.9; do sudo podman run --rm docker.io/busybox ping -c 3 $i; done
PING 1.1.1.1 (1.1.1.1): 56 data bytes
64 bytes from 1.1.1.1: seq=0 ttl=56 time=19.140 ms
64 bytes from 1.1.1.1: seq=1 ttl=56 time=12.176 ms
64 bytes from 1.1.1.1: seq=2 ttl=56 time=18.328 ms

--- 1.1.1.1 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 12.176/16.548/19.140 ms
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=118 time=19.923 ms
64 bytes from 8.8.8.8: seq=1 ttl=118 time=22.942 ms
64 bytes from 8.8.8.8: seq=2 ttl=118 time=25.784 ms

--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 19.923/22.883/25.784 ms
PING 9.9.9.9 (9.9.9.9): 56 data bytes
64 bytes from 9.9.9.9: seq=0 ttl=56 time=18.633 ms
64 bytes from 9.9.9.9: seq=1 ttl=56 time=21.900 ms
64 bytes from 9.9.9.9: seq=2 ttl=56 time=11.468 ms

--- 9.9.9.9 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 11.468/17.333/21.900 ms
```

**Comment by giuseppe** [comment] 2019-04-08 12:13
> Weird I can get this to happen once. Even upping the odds.
> 
> do sudo podman run --rm docker.io/busybox ping -c 1 1.1.1.1; sleep 1; done

what kernel are you using?

**Comment by giuseppe** [comment] 2019-04-09 12:43
@teknoraver suggested me that the solution is `sysctl -w net.netfilter.nf_conntrack_icmp_timeout=2`.  Could you try if that solve the issue for you?

**Comment by mike-nguyen** [comment] 2019-04-09 14:07
> @teknoraver suggested me that the solution is `sysctl -w net.netfilter.nf_conntrack_icmp_timeout=2`. Could you try if that solve the issue for you?

@giuseppe that works! 

Do we know why this has changed from 4.20.x kernel behavior?  Why does it affect only podman containers and not docker containers or the host directly?  Is this something that needs to be fixed for podman?

**Comment by baude** [comment] 2019-05-29 15:07
any updates?

**Comment by teknoraver** [comment] 2019-05-29 15:09
Yes, this is the expected behaviour because the conntrack entries didn't expire yet. Try to lower the timeout with `net.netfilter.nf_conntrack_icmp_timeout=X`

**Comment by rhatdan** [comment] 2019-06-08 19:15
Well if it is expected I will close the issue.

**Closed by rhatdan** 2019-06-08 19:15 UTC
Labels: kind/bug, retiring
