### ISSUE TITLE
varlink API hangs: too aggressive daemon timeout hits systemd's start limit

### ISSUE THREAD

**Issue by martinpitt** [containers/libpod#3603] opened 2019-07-18 21:18 UTC
/kind bug

**Description**

In trying to debug issue #3602 , I ran some podman operations on the command line using the varlink API. But this locks up very often with hangs or "Unable to connect: CannotConnect".

**Steps to reproduce the issue:**

1. `podman pull docker.io/library/busybox:latest`

2. `mkdir -p /tmp/v1 /tmp/v2`

3. `while true; do podman rm -f busybox-with-tty || true; varlink call unix:/run/podman/io.podman/io.podman.CreateContainer '{"create":{"args":["docker.io/library/busybox:latest","sh","-c","while echo Hello World; do sleep 1; done"],"resources":{},"name":"busybox-with-tty","tty":true,"publish":["6000:5000/TCP","6001:5001/UDP","8001:8001/TCP"],"env":["APPLE=ORANGE","PEAR=BANANA","RHUBARB=STRAWBERRY"],"volume":["/tmp/v1:/tmp/ro:ro","/tmp/v2:/tmp/rw:rw"]}}'; varlink call unix:/run/podman/io.podman/io.podman.StartContainer '{"name":"busybox-with-tty"}'; podman ps; done`
(This is a fairly faithful representation of what happens in our integration test).

**Describe the results you received:**

After a few iterations this starts to fail with "Unable to connect: CannotConnect". The journal says why:
```
systemd[1]: io.podman.service: Succeeded.
systemd[1]: io.podman.service: Consumed 204ms CPU time.
systemd[1]: io.podman.service: Start request repeated too quickly.
systemd[1]: io.podman.service: Failed with result 'start-limit-hit'.
ystemd[1]: Failed to start Podman Remote API Service.
systemd[1]: io.podman.socket: Failed with result 'service-start-limit-hit'.
```
It seems that pretty much every operation starts io.podman.service, and immediately stops it again. `podman varlink --help` says the default timeout is 1s, but apparently it's lower than that -- and even that, if you issue one request per second (which is fairly realistic for a UI), then you hit the "5 restarts in 10 seconds" barrier pretty quickly.

**Describe the results you expected:**

varlink calls should succeed regardless of their frequency. Please increase the timeout to something reasonable, a magnitude of a minute. Once something starts talking to varlink, it's reasonable to assume that it will do more than just one call, so serving each call by a full startup of the executable is very expensive and prone to start limits.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.4.5-dev
RemoteAPI Version:  1
Go Version:         go1.12.6
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.6
  podman version: 1.4.5-dev
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-1.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.2.0, commit: 41010e63c287618b1dc34ee11d10d268e2feeefe'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 286429184
  MemTotal: 1030520832
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 1291841536
  SwapTotal: 1291841536
  arch: amd64
  cpus: 1
  hostname: m1.cockpit.lan
  kernel: 5.1.16-300.fc30.x86_64
  os: linux
  rootless: false
  uptime: 22m 59.44s
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 3
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by martinpitt** [comment] 2019-07-18 21:25
After `podman pull docker.io/library/busybox:latest`, this command locks up straight away for me:

```
# varlink call unix:/run/podman/io.podman/io.podman.CreateContainer '{"create":{"args":["docker.io/library/busybox:latest","sh","-c","while echo Hello World; do sleep 1; done"],"resources":{},"name":"c1","tty":true}}'; varlink call unix:/run/podman/io.podman/io.podman.StartContainer '{"name":"c1"}'
{
  "container": "996536350dba80739e8c940b275a65ecce2518b783f394e4873d67a590266c4c"
}
```

i. e. the `StartContainer` call is hanging forever. I see it in `ps`. The starting did succeed:
```
# podman ps
CONTAINER ID  IMAGE                             COMMAND               CREATED        STATUS            PORTS  NAMES
996536350dba  docker.io/library/busybox:latest  sh -c while echo ...  3 minutes ago  Up 3 minutes ago         c1
```

systemd shows that the process exited cleanly, but apparently before the `StartContainer` call got fully processed:
```
 # systemctl status io.podman
● io.podman.service - Podman Remote API Service
   Loaded: loaded (/usr/lib/systemd/system/io.podman.service; disabled; vendor preset: disabled)
   Active: inactive (dead) since Thu 2019-07-18 17:19:28 EDT; 1min 0s ago
     Docs: man:podman-varlink(1)
  Process: 7435 ExecStart=/usr/bin/podman varlink unix:/run/podman/io.podman (code=exited, status=0/SUCCESS)
 Main PID: 7435 (code=exited, status=0/SUCCESS)
      CPU: 193ms

Jul 18 17:19:27 m1.cockpit.lan systemd[1]: Started Podman Remote API Service.
Jul 18 17:19:27 m1.cockpit.lan podman[7435]: time="2019-07-18T17:19:27-04:00" level=error msg="unable to find flag trace"
Jul 18 17:19:27 m1.cockpit.lan podman[7435]: time="2019-07-18T17:19:27-04:00" level=error msg="unable to find flag http-proxy"
Jul 18 17:19:27 m1.cockpit.lan podman[7435]: time="2019-07-18T17:19:27-04:00" level=error msg="unable to find flag syslog"
Jul 18 17:19:27 m1.cockpit.lan podman[7435]: 2019-07-18 17:19:27.876929013 -0400 EDT m=+0.377240165 container create 996536350dba80739e>
Jul 18 17:19:28 m1.cockpit.lan podman[7435]: 2019-07-18 17:19:28.666345623 -0400 EDT m=+1.166656657 container init 996536350dba80739e8c>
Jul 18 17:19:28 m1.cockpit.lan podman[7435]: 2019-07-18 17:19:28.706713511 -0400 EDT m=+1.207024646 container start 996536350dba80739e8>
Jul 18 17:19:28 m1.cockpit.lan systemd[1]: io.podman.service: Succeeded.
Jul 18 17:19:28 m1.cockpit.lan systemd[1]: io.podman.service: Consumed 193ms CPU time.
```
This is *not* triggering the start-limit, as it's just two calls. Just the second one seems to happen at a bad time.

**Comment by baude** [comment] 2019-07-18 23:41
safe to assume you are running this all as root?

**Comment by baude** [comment] 2019-07-18 23:42
also, instead of running varlink as a service, if you run it manually with a timeout of 0, does it work?

**Comment by martinpitt** [comment] 2019-07-19 07:44
> safe to assume you are running this all as root?

Yes.

I took a look again at the timeout behaviour in 
[issue #3602](https://github.com/containers/libpod/issues/3602#issuecomment-513126580), with microsecond precision. The important part for this bug:

```
# journalctl -o short-precise -f -u io.podman -u io.podman.socket
-- Logs begin at Thu 2019-07-18 02:32:35 EDT. --
Jul 19 03:26:51.863787 m1.cockpit.lan systemd[1]: Listening on Podman Remote API Socket.
Jul 19 03:27:10.089846 m1.cockpit.lan systemd[1]: Started Podman Remote API Service.
Jul 19 03:27:10.172716 m1.cockpit.lan podman[8570]: time="2019-07-19T03:27:10-04:00" level=error msg="unable to find flag trace"
Jul 19 03:27:10.179353 m1.cockpit.lan podman[8570]: time="2019-07-19T03:27:10-04:00" level=error msg="unable to find flag http-proxy"
Jul 19 03:27:10.179511 m1.cockpit.lan podman[8570]: time="2019-07-19T03:27:10-04:00" level=error msg="unable to find flag syslog"
Jul 19 03:27:10.438117 m1.cockpit.lan podman[8570]: 2019-07-19 03:27:10.436936497 -0400 EDT m=+0.313240917 container create eeab55fbab3c3ba61b4ef482516960377fe455a2352727de540258388ad24f90 (image=docker.io/library/busybox:latest, name=c1)
Jul 19 03:27:11.220678 m1.cockpit.lan podman[8570]: 2019-07-19 03:27:11.220016136 -0400 EDT m=+1.096320510 container init eeab55fbab3c3ba61b4ef482516960377fe455a2352727de540258388ad24f90 (image=docker.io/library/busybox:latest, name=c1)
Jul 19 03:27:11.259892 m1.cockpit.lan podman[8570]: 2019-07-19 03:27:11.259843447 -0400 EDT m=+1.136147722 container start eeab55fbab3c3ba61b4ef482516960377fe455a2352727de540258388ad24f90 (image=docker.io/library/busybox:latest, name=c1)
Jul 19 03:27:11.448315 m1.cockpit.lan systemd[1]: io.podman.service: Succeeded.
Jul 19 03:27:11.449047 m1.cockpit.lan systemd[1]: io.podman.service: Consumed 171ms CPU time.
```

So this shows that between the last event and the shutdown there's less than 0.2s.

With

    /usr/bin/podman varlink --timeout 0 unix:/run/podman/io.podman

the container create/start/rm loop works fine, and podman does not exit.

With `--timeout 10000` it works as well. With `--timeout 1000` it exits too fast (and it's not really a full second).

**Comment by vrothberg** [comment] 2019-09-24 13:24
The service files and the backend has been improved. The issue is now resolved in master.

Thanks a lot for opening the issue, @martinpitt !

**Closed by vrothberg** 2019-09-24 13:24 UTC
Labels: kind/bug, remote
