### ISSUE TITLE
Keeping historical packages in the new Ubuntu repositories

### ISSUE THREAD

**Issue by alitvak69** [containers/libpod#4937] opened 2020-01-23 02:28 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
Currently, on openSuseBuild server repos, only the packages from the latest release are installed.  There is no way to go back manually or via packaging tools.  Older packages are gone from the repo forever.   I believe that older podman and build dependencies should be available for downgrading and troubleshooting at least up to the last .0 release.  I.e. if we have 1.7.0, we should be able to go to 1.6.1 if needed.  Or at least the most stable version of 1.6.x should be preserved.   PPA kept other built packages available for download without a limit. 

**Steps to reproduce the issue:**

1. Check the repo: http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/
 and you will see that podman 1.6.4 is gone and replaced with podman 1.7.0

**Describe the results you received:**

Podman 1.6.4 is no longer avaialble

**Describe the results you expected:**

Older podman versions up to the point should be available together with all the build dependencies.

**Comment by mheon** [comment] 2020-01-23 10:35
@lsm5 PTAL

**Comment by alitvak69** [comment] 2020-02-01 22:19
Is there an update on this issue?  Ubuntu 1.8.0 released under testing but 1.7.0 have disappeared.  What prevents one from keeping both versions?

**Comment by lsm5** [comment] 2020-02-02 23:22
@alitvak69 hi, i had set automation up to delete older builds when newer builds show up, I'll check if OBS does keep older debs if I leave the older packaging sources in there..

**Comment by lsm5** [comment] 2020-02-03 20:48
so OBS people told me the repos won't keep the prior built debs after a new version is shipped. If it helps, I can keep the packaging sources (dsc + tarball) in there so you can fetch the source and build it if need be.

**Comment by alitvak69** [comment] 2020-02-03 21:59
I think keeping sources will solve the problem for me.  It is easy enough
to build deb based on tarball and dsc.

**Comment by alitvak69** [comment] 2020-02-06 12:21
@lsm5 Podman 1.8 had been removed from testing repo.  Neither source not .deb are available.

**Comment by alitvak69** [comment] 2020-02-08 09:41
It looks like 1.7 dissapeared from stable repo on OBS yet again.  No source files either.  Is there at least a way keep sources and dsc in archive subfolder or something?

**Comment by rhatdan** [comment] 2020-02-18 15:35
@lsm5 This is a duplicate of another issue, could you close one of them?

**Comment by lsm5** [comment] 2020-02-18 15:40
> It looks like 1.7 dissapeared from stable repo on OBS yet again. No source files either. Is there at least a way keep sources and dsc in archive subfolder or something?

older files have `.old` appended. See: https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman . OBS wouldn't let me put stuff in subdirs, so that's why the name change.

Let's talk further in https://github.com/containers/libpod/issues/3924 if anything.

**Closed by lsm5** 2020-02-18 15:40 UTC
Labels: kind/feature, ubuntu
