### ISSUE TITLE
Chrome crashes when running in podman

### ISSUE THREAD

**Issue by greg-hydrogen** [containers/libpod#2041] opened 2018-12-21 05:21 UTC
**kind bug**

**Description**

Unable to reliably run chrome in a container started with podman.  Chrome crashes quickly when attempting to visit a site

**Steps to reproduce the issue:**

1.  Use the base image from fedora.  Install the latest version of chrome.  Create a new user.  save the image to be relauched

2.  Run the container with the following command line (root is needed due to /dev/dri)
sudo podman run --security-opt secommp=unconfined-v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/dri:/dev/dri -v /dev/shm:/dev/shm --name chrome --user createduser -e DISPLAY=:0.0 imagename /opt/google/chrome/google-chrome
3. Set the correct display variable for your system and allow x sessons to be run from any ip via xhost + (temporary).  Also, the security option here is just for testing, there is a more specific seccomp profile provided by Jessie Frazelle 
For the --device to work podman latest was compiled with https://github.com/containers/libpod/pull/2033 as this allows using --device with /dev/dri

**Describe the results you received:**
 Chrome starts, but crashes when visiting a site, especially a github.com site with any code

**Describe the results you expected:**
Chrome to run the same in podman as it does in docker.  With docker the same image runs without any issue

**Output of `podman version`:**
Version:       0.12.2-dev
Go Version:    go1.11.2
Git Commit:    "6b059a58828b978f30ed416da066987226e88e73-dirty"
Built:         Thu Dec 20 01:18:07 2018
OS/Arch:       linux/amd64

**Output of `podman info`:**

sudo podman info
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.1-1.git66d3499.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 8a97c0f33b6bd8eabb04f0b8368b78022b53942f-dirty'
  Distribution:
    distribution: fedora
    version: "28"
  MemFree: 37363875840
  MemTotal: 67537940480
  OCIRuntime:
    package: runc-1.0.0-59.dev.gitccb5efd.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 16
  hostname: lnxworkstn
  kernel: 4.19.8-200.fc28.x86_64
  os: linux
  rootless: false
  uptime: 1h 56m 17.53s (Approximately 0.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 6
  GraphDriverName: zfs
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Compression: lz4
    Parent Dataset: storage/podman/storage
    Parent Quota: "no"
    Space Available: "310907183104"
    Space Used By Parent: "4726448128"
    Zpool: storage
    Zpool Health: ONLINE
  ImageStore:
    number: 13
  RunRoot: /var/run/containers/storage

**Additional environment details (AWS, VirtualBox, physical, etc.):**
using zfs as the storage backend

**Comment by mheon** [comment] 2018-12-21 05:45
I'm assuming that an identical setup run with Docker succeeds without crashing?

I wonder if this isn't a `runc` issue. We're running very close to master, and issues do occasionally pop up...

Also, can you pastebin the result of the `podman run` you use for chrome with `--log-level=debug` added, to see if there's anything unusual going on?

**Comment by greg-hydrogen** [comment] 2018-12-21 06:09
@mheon  - yep the exact same setup run's in Docker without any issues

sure here is the pastebin output
https://pastebin.com/1ibcZQJc

**Comment by rhatdan** [comment] 2018-12-21 12:11
You would need to disable SELinux to make this work as well.
--security-opt label=disable

**Comment by greg-hydrogen** [comment] 2018-12-21 15:44
@rhatdan  - I had forgot to mention that the host is set to permissive.  I added the extra parameter of --security-opt label=disable... unfortunately the same result

**Comment by rhatdan** [comment] 2018-12-21 16:00
Any log from CHROME on why it was crashing?

**Comment by rhatdan** [comment] 2018-12-21 16:00
BTW This is with the device directory patch correct?

**Comment by rhatdan** [comment] 2018-12-21 17:04
Does it work if you do --privileged

**Comment by greg-hydrogen** [comment] 2018-12-21 17:09
just tried again, no luck, I used two variations of the run command

sudo podman run --privileged --security-opt seccomp=unconfined --security-opt=label=disable  -v /tmp/.X11-unix:/tmp/.X11-unix  --device /dev/dri:/dev/dri -v /dev/shm:/dev/shm --name chrome --user greg -e DISPLAY=:0.0 -ti chrome2 /bin/bash

sudo podman run --privileged  -v /tmp/.X11-unix:/tmp/.X11-unix ---device /dev/dri:/dev/dri -v /dev/shm:/dev/shm --name chrome --user greg -e DISPLAY=:0.0 -ti chrome2 /bin/bash

**Comment by rhatdan** [comment] 2018-12-21 17:15
So you are using X not wayland for running the pod.  I am building my own chrome container.

**Comment by rhatdan** [comment] 2018-12-21 17:20
This works for me.
podman run -e DISPLAY=:0.0 --net=host -ti -v /etc/machine-id:/etc/machine-id --user 3267 --device /dev/dri/ --privileged chrome google-chrome

**Comment by greg-hydrogen** [comment] 2018-12-21 17:20
Sorry I should have provided more details on the host OS.  I am running Fedora 28 XFCE spin fully up to date with the patched version of podman
The same is happening on a Fedora 29 XFCE spin that is fully up to date with a patched version of podman as well
Both running X

**Comment by rhatdan** [comment] 2018-12-21 17:21
I am using wayland.

**Comment by rhatdan** [comment] 2018-12-21 17:21
Try adding --net=host

**Comment by rhatdan** [comment] 2018-12-21 17:41
Ok that crashed for me also.

**Comment by rhatdan** [comment] 2018-12-21 17:47
Try adding --ipc=host
That seems to be working better for me.

**Comment by rhatdan** [comment] 2018-12-21 17:50
BTW A google-chrome flatpack is actually probably what you want for this use case.

https://flathub.org/home

**Comment by rhatdan** [comment] 2018-12-21 19:58
Weird you say it works the same on docker, though and docker has
```
 mount | grep shm
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,size=65536k)
```

**Comment by rhatdan** [comment] 2018-12-21 19:59
Perhaps we should not set this at all, and just let shm grow to 50% of cgroup mount max.

**Comment by mheon** [comment] 2018-12-21 20:02
@rhatdan Docker wasn't seeing it because of `-v /dev/shm:/dev/shm` - they were using the host SHM

**Comment by rhatdan** [comment] 2018-12-22 11:38
@greg-hydrogen Can I close this issue now, since we know the cause.

**Comment by greg-hydrogen** [comment] 2018-12-22 15:42
@rhatdan - I will, should we open a new issue for podman not using the host SHM when mounted via -v /dev/shm:/dev/shm?

**Comment by mheon** [comment] 2018-12-22 16:35
@greg-hydrogen Opening a new issue sounds like a good plan.

**Closed** 2018-12-22 23:03 UTC
Labels: bug

**Comment by rhatdan** [comment] 2018-12-24 13:08
@greg-hydrogen I have a fix for this other issue in https://github.com/containers/libpod/pull/2051
