### ISSUE TITLE
In read-only container, opening file for append still causes change to be shown in podman diff

### ISSUE THREAD

**Issue by adelton** [containers/libpod#1506] opened 2018-09-19 08:05 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

[//]: # Uncomment only one, leave it on its own line:

[//]: # **kind bug**

**Description**

In read-only container, opening file for append still causes change to be shown in podman diff.

**Steps to reproduce the issue:**

1. `podman run --read-only --name container -ti registry.access.redhat.com/rhel7 bash -c 'echo Test >> /var/log/btmp ; sleep 600' `
2. In another terminal: `podman diff container | grep /var/log/btmp`

**Describe the results you received:**

```
C /var/log/btmp
```

**Describe the results you expected:**

Nothing reported about `/var/log/btmp` since the container is read-only and that append-open failed anyway.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.7.3
Go Version:    go1.9.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  MemFree: 3677413376
  MemTotal: 5030330368
  SwapFree: 5234487296
  SwapTotal: 5234487296
  arch: amd64
  cpus: 8
  hostname: machine.example.com
  kernel: 3.10.0-862.14.3.el7.x86_64
  os: linux
  uptime: 3m 33.9s
insecure registries:
  registries: []
registries:
  registries:
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is RHEL 7.5.

This is based on https://bugzilla.redhat.com/show_bug.cgi?id=1611623.

**Comment by mheon** [comment] 2018-09-19 12:28
Thanks for the report, I'll look into it today

**Comment by mheon** [comment] 2018-09-19 12:29
I suspect there's a flag we're not providing to c/storage related to read-only that's causing it to allow overlay copyup to happen

**Comment by rhatdan** [comment] 2018-09-19 13:31
No this is normal running of a containers.  Their is content that we add to containers on the fly.

```
# podman run --read-only --name test fedora echo hello
hello
# podman diff test
C /run
A /run/.containerenv
A /run/secrets
```
The question I have is should we mask these from podman diff, so that they don't show up.  I actually think their are a few more /etc/hosts, and /etc/resolv.conf if they did not exists.

Since we know the list of inodes that are hard coded to add we should just whitelist these.

@nalind @rhvgoyal WDYT?

**Comment by adelton** [comment] 2018-09-19 13:40
Note that in this issue I don't speak about `/run/secrets` and other similar changes done during the container / pod setup.
What I'm concerned about is an operation executed from within the read-only container (opening the file for append) leaves some traces on the overlay / in the diff output -- ctime is modified. Attempt to open the file for write (but not append) fails as well and is not listed in diff output, I'd like the same for append.

**Comment by mheon** [comment] 2018-09-19 14:13
I don't see any relevant flags we would pass to c/storage. I'll ask @nalind if this looks like something on the storage side.

**Comment by mheon** [comment] 2018-09-19 14:26
Is /var/log an image volume for the RHEL7 image? That might explain what's going on

**Comment by rhatdan** [comment] 2018-09-19 15:37
@adelton Give me an example other then those stated by @mheon of writable content that shows up in the diff?

**Comment by adelton** [comment] 2018-09-19 17:11
> Alright, trying to reproduce locally gets me an error as I can't append to a read-only filesystem.

Yes, you get an error. But if you then run `podman diff`, you will see that file listed as modified.

**Comment by mheon** [comment] 2018-09-19 17:45
Huh. Confirmed - you get a read-only filesystem error, but `podman diff` does show a diff.

**Comment by mheon** [comment] 2018-09-19 17:53
There is no actual diff in the contents of the file.
@rhatdan I'm pretty sure this is overlay copyup happening, with the subsequent write being denied?

**Comment by rhatdan** [comment] 2018-09-19 18:04
Looks like a bug in overlay.  @rhvgoyal PTAL

**Comment by adelton** [comment] 2018-09-21 07:11
First stab by @rhatdan at fixing the issue: https://github.com/opencontainers/runc/pull/1896.

**Comment by rhatdan** [comment] 2018-09-21 11:54
Actually I closed this since it is a kernel issue and @rhvgoyal points out that it is fixed in upstream kernel.

```
dwalsh: latest upstream kernel first checks whether write access on filesystem is allowed or not. And later it does copy up. And that's why this problem is not present in 4.19-rc1 onwards.
```

**Closed** 2018-09-21 11:55 UTC
Labels: bug
