### ISSUE TITLE
 Bug: Restarting rootless containers with published ports fails (coredump)

### ISSUE THREAD

**Issue by daniel-wtd** [containers/libpod#6089] opened 2020-05-05 14:42 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When running a container with a published port (rootless) like so:

```
podman run -dt -p 8080:80 docker.io/library/httpd:2.4
```
And restarting the container afterwards:

```
podman restart -l
```

One will get an error like:

```
Error: failed to expose ports via rootlessport: "listen tcp 0.0.0.0:8080: bind: address already in use\n"
```

and the container will be stopped. Starting the container via `start` afterwards works fine. A coredump will be created via systemd:

```
Mai 05 10:52:52 nb01 systemd-coredump[9161]: Process 9009 (exe) of user 1000 dumped core.
                                             
                                             Stack trace of thread 9019:
                                             #0  0x000055fc0cc93701 runtime.raise (podman + 0xb6d701)
                                             #1  0x000055fc0cc779ae runtime.sigfwdgo (podman + 0xb519ae)
                                             #2  0x000055fc0cc762e4 runtime.sigtrampgo (podman + 0xb502e4)
                                             #3  0x000055fc0cc93a73 runtime.sigtramp (podman + 0xb6da73)
                                             #4  0x00007f0c6728ca90 __restore_rt (libpthread.so.0 + 0x14a90)
                                             #5  0x000055fc0cc93701 runtime.raise (podman + 0xb6d701)
                                             #6  0x000055fc0cc7757a runtime.crash (podman + 0xb5157a)
                                             #7  0x000055fc0cc607f6 runtime.fatalpanic (podman + 0xb3a7f6)
                                             #8  0x000055fc0cc60191 runtime.gopanic (podman + 0xb3a191)
                                             #9  0x000055fc0cc31b29 runtime.chansend (podman + 0xb0bb29)
                                             #10 0x000055fc0cc31545 runtime.chansend1 (podman + 0xb0b545)
                                             #11 0x000055fc0dba359f github.com/containers/libpod/pkg/rootlessport.parent.func1 (podman + 0x>
                                             #12 0x000055fc0dba2ad8 github.com/containers/libpod/pkg/rootlessport.parent (podman + 0x1a7cad>
                                             #13 0x000055fc0dba3418 github.com/containers/libpod/pkg/rootlessport.init.0.func1 (podman + 0x>
                                             #14 0x000055fc0dee44ab main.main (podman + 0x1dbe4ab)
                                             #15 0x000055fc0cc62c2a runtime.main (podman + 0xb3cc2a)
                                             #16 0x000055fc0cc91b21 runtime.goexit (podman + 0xb6bb21)
-- Subject: Process 9009 (exe) dumped core

```

## information

- OS: Fedora 32 Silverblue
- Podman: 1.9.1

**Comment by mheon** [comment] 2020-05-05 16:44
Believe this is a dupe of #6018 - can you verify the fix there resolves this?

**Comment by daniel-wtd** [comment] 2020-05-07 18:45
@mheon afaik, therefore I need to build podman on my own, correct?

Will have a look.

**Comment by mheon** [comment] 2020-06-02 16:13
Should be fixed, closing

**Closed by mheon** 2020-06-02 16:13 UTC
Labels: kind/bug
