### ISSUE TITLE
Ubuntu install guide: can't execute Podman

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#2449] opened 2019-02-26 17:55 UTC
Following the [install guide](https://github.com/containers/libpod/blob/master/install.md) for Ubuntu (18.04.2), I end up in a rather unusable state as some configs are not installed.

```
valentin@uvm:~$ podman run alpine ls
Error: error creating libpod runtime: Error running podman info while refreshing state: exit status 1
valentin@uvm:~$ sudo podman run alpine ls
Error: unable to pull alpine: error getting default registries to try: unable to parse the registries.conf file: open /etc/containers/registries.conf: no such file or directory
```

I think the package must be updated. Let's use the issue as a tracker.

**Comment by vrothberg** [comment] 2019-02-26 17:56
@lsm5, can you have a look? I am not sure if it's a known issue or not. I just installed an Ubuntu VM for some performance tests.

**Comment by mheon** [comment] 2019-02-26 18:12
Known issue, but I don't think we've collated all of this in the same place before.

I walked someone on IRC through getting things working a few weeks back, and we encountered the following issues:

- No dependency on `uidmap` package (needed for rootless)
- Missing `slirp4netns` (no package)
- Missing `registries.conf`

**Comment by rhatdan** [comment] 2019-03-08 18:39
@lsm5 was looking at this package today.  Is this issue fixed?

**Comment by lsm5** [comment] 2019-03-08 18:43
sorry, been fighting some rhel fires, but this is on my todo for today, closing this as duplicate of https://github.com/containers/libpod/issues/2116

**Closed by lsm5** 2019-03-08 18:43 UTC
