### ISSUE TITLE
tput cols/tput lines gives wrong results in `podman exec`

### ISSUE THREAD

**Issue by praiskup** [containers/libpod#3903] opened 2019-08-28 18:58 UTC
Correct output from `podman run`
```
$ podman run --rm -ti fedora:30 bash
[root@830e92c167ba /]# tput cols
237
[root@830e92c167ba /]# tput lines
56
[root@830e92c167ba /]# 
```

Wrong output in `exec` from the same container:
```
$ podman exec -ti objective_bohr bash
[root@830e92c167ba /]# tput cols
80
[root@830e92c167ba /]# tput lines
24
```

```
rpm -q runc podman
runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
podman-1.5.1-3.fc30.x86_64`
```

**Comment by praiskup** [comment] 2019-08-28 19:00
I used separate terminal, in separate tab in `konsole` (but I tried separate terminal in `gnome-terminal`, and I have the same results).

**Comment by haircommander** [comment] 2019-08-29 14:20
thanks for the issue @praiskup  I was able to reproduce. I'll look into it

**Comment by debarshiray** [comment] 2019-09-05 14:02
Interestingly, only the initial size is wrong. If the terminal emulator window is resized afterwards, then it picks up the changes correctly.

**Comment by mheon** [comment] 2019-09-05 14:35
We might not be sending an initial resize message to Conmon

**Comment by haircommander** [comment] 2019-09-05 14:38
yeah I found the issue. the initial resize request happens before conmon creates the ctl file, so it just errors out. I am trying to find a work around now

**Comment by praiskup** [comment] 2019-09-05 15:45
I just need to claim that this used to work in some previous version of podman (or runc, or whatever).  I noticed problems last week for the first time.  Btw., thanks for the work-around with window resizing!

**Comment by juhp** [comment] 2019-09-09 03:29
Another workaround is for a shell is to run `reset` :)  (Yep, it is a regression as Rishi also explained in his report.)

**Comment by praiskup** [comment] 2019-09-09 07:31
The `reset` workaround doesn't help in my case.

**Comment by debarshiray** [comment] 2019-09-09 12:52
I wonder if there's some race involved here. For some reason this bug stopped reproducing today out of the blue, even with the same software versions that were reliably reproducing it until last Thursday.

Anyway, since @haircommander already figured it out, I'll wait for the fix. :)

**Comment by juhp** [comment] 2019-09-11 07:45
@praiskup you are right - I came back to report the same - maybe I had resized the window...

**Comment by mheon** [comment] 2019-10-24 17:29
@haircommander This is fixed, yes?

**Comment by haircommander** [comment] 2019-10-24 18:47
yes it should be!

**Comment by mheon** [comment] 2019-10-24 19:08
Closing

**Closed by mheon** 2019-10-24 19:08 UTC
Labels: kind/bug
