### ISSUE TITLE
Relative volume path in Kube yaml is not resolved

### ISSUE THREAD

**Issue by Fodoj** [containers/libpod#3029] opened 2019-04-27 10:26 UTC
For example:

```
  volumes:
    - name: app
      hostPath:
        path: ./
        type: Directory
```

Will result in volume simply ignored. Podman 1.3.0-dev, Fedora Workstation 29.

**Comment by haircommander** [comment] 2019-05-06 18:40
@Fodoj just to make sure, are you expecting the path to be based on the kube yaml location?

**Comment by Fodoj** [comment] 2019-05-06 19:19
Good question... I think that would make more sense than relative to where podman runs from, but no idea what's the way to go, really

**Comment by haircommander** [comment] 2019-05-06 19:40
```podman --mount type=bind,src=./,target=/tmp -ti alpine ls /tmp```
actually mounts based on the rundir. I'd likely want to line up functionality with that, as that's the equivalent from the podman CLI. WDYT @Fodoj 
(cc: @mheon because you just did some mount reworking and may have something to say here)

**Comment by mheon** [comment] 2019-05-06 20:08
Relative mounts working right now are honestly more of an accident than anything. I don't think we consider them supported, so if we want to change where they're relative to (such that they make more sense), I'd be fine with that. Directory Podman is being run from would seem to make the most sense to me.

(We'll probably have to resolve the relative paths before we pass them into Libpod to do this, but that's not a particularly big deal now that we have a common path for all mounts code)

**Comment by baude** [comment] 2019-08-02 17:19
where do we stand

**Comment by haircommander** [comment] 2019-08-02 17:20
@QiWang19 I seem to remember you doing work with resolving relative paths, is that the case?

**Comment by QiWang19** [comment] 2019-08-02 17:27
I have this PR https://github.com/containers/libpod/pull/3537 to convert the src path to absolute path

**Comment by haircommander** [comment] 2019-08-02 17:41
I can confirm #3537 fixed this! thanks @QiWang19

**Closed by haircommander** 2019-08-02 17:41 UTC

**Comment by majidaldo** [comment] 2023-05-13 01:31
this doesn't work on windows (from the outside). it does work if i use podman inside podman-machine-default inside wsl.
