### ISSUE TITLE
error creating libpod runtime: there might not be enough IDs available in the namespace

### ISSUE THREAD

**Issue by juansuerogit** [containers/libpod#3421] opened 2019-06-24 21:38 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug
 

**Description**

I have RHEL servers in the 7.x range ( i think they are 7.4 or 7.5 ) that we currently run containers on with docker-compose.   Went to a Red Hat conference and learned about Podman so want to use Podman in production to help us get away from the big fat deamons and not to run containers as root.

To that end i have created a centos 7.5 VM on my laptop and installed podman.  But i cannot seem to get the uidmap functionality to work.

Im hoping that once we solve this uidmap bug im encountering that we can then take this and run it on RHEL 7.4 server.

On the RHEL 7.4 we can only operate as a regular user so we need to figure out rootless podman.

I understand that some changes to the OS are needed and we need adminstrative control to do this.  Like the subuid and subgid and the kernal params to enable user namespaces.  we can do that.  but on a day to day basis including running the production containers we have to be able to run rootless podman and backup and recover the files as the same regular user ( not root )

In addition im not sure how to map an existing user on the container image
for example mongod ( the mongodb user )
to the regular server user.  but thats maybe getting ahead of ourselves.

**Steps to reproduce the issue:**

1. clean Centos 7.5  VM
2. logged into a regular user called "meta" (not root)  
3. sudo grubby --args="namespace.unpriv_enable=1 user_namespace.enable=1" --update-kernel="/boot/vmlinuz-3.10.0-957.5.1.el7.x86_64"
4. sudo yum -y update && sudo yum install -y podman
5. sudo echo 'user.max_user_namespaces=15076' >> /etc/sysctl.conf
6. sudo echo 'meta:100000:65536' >> /etc/subuid
7. sudo echo 'meta:100000:65536' >> /etc/subgid
8. sudo reboot
9. podman run -dt --uidmap 0:100000:500 ubuntu sleep 1000

**Describe the results you received:**

Error: error creating libpod runtime: there might not be enough IDs available in the namespace (requested 100000:100000 for /home/meta/.local/share/containers/storage/vfs): chown /home/meta/.local/share/containers/storage/vfs: invalid argument

**Describe the results you expected:**

I expected a pod / container which would be running and i could exec into it and 
create files inside the container as user root 

upon exiting the container i expect those files to be owned by user "meta"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.3.2
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding subids 
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.3.2
host:
  BuildahVersion: 1.8.2
  Conmon:
    package: podman-1.3.2-1.git14fdcd0.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.14.0-dev, commit: e0b5a754190a3c24175944ff64fa7add6c8b0431-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 410226688
  MemTotal: 3973316608
  OCIRuntime:
    package: runc-1.0.0-59.dev.git2abd837.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  hostname: min0-kube0
  kernel: 3.10.0-957.21.3.el7.x86_64
  os: linux
  rootless: true
  uptime: 2h 25m 41.8s (Approximately 0.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /home/meta/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/meta/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /tmp/1000
  VolumePath: /home/meta/.local/share/containers/storage/volumes

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Centos 7.5  VM  
sudo yum -y update && sudo yum install -y podman
sudo echo 'user.max_user_namespaces=15076' >> /etc/sysctl.conf
sudo echo 'meta:100000:65536' >> /etc/subuid
sudo echo 'meta:100000:65536' >> /etc/subgid
sudo reboot
podman run -dt --uidmap 0:100000:500 ubuntu sleep 1000

**Comment by mheon** [comment] 2019-06-24 21:43
`--uidmap 0:100000:500` looks like the problem. You're requesting to map to UID 1000000 with rootless Podman (I'm presuming that last Podman command in your reproducer is run without sudo).

You don't need to use `--uidmap` with rootless Podman - we'll automatically select the UID/GID ranges from subuid and subgid. You only need the uidmap flag if you want to change the way users are allocated within the container (for example, by default, the user launching Podman is mapped into the rootless container as UID 0 - you can change that with a few `--uidmap` args).

Just running Podman as a non-root user, no extra arguments or special flags (but with a configured `/etc/subuid` and `/etc/subgid`), is enough to launch your containers inside an unprivileged user namespace.

**Comment by mheon** [comment] 2019-06-24 21:45
And to provide further clarity on why it fails - `--uidmap` is trying to map to UID 1000000, which is not mapped into the container. The container only has 65536 UIDs from the ranges in `/etc/subuid` and `/etc/subgid` (plus one more - the UID/GID of the user that launches it). Mapping to UID 1000000 and higher won't work, since we don't have any UIDs higher than 65536 available.

**Comment by juansuerogit** [comment] 2019-06-24 22:17
Ahhh so to take your example further.   if for example i use the mongodb image where the user mongod might be user 23 i dunno.  some number other than zero.   and i just want to run that no modifications with rootless podman then i will need to use --uidmap to map my regular user to the mongod user number 23 inside the container.  so in that case the args would be --uidmap 0:23 ?

**Comment by mheon** [comment] 2019-06-24 22:45
Depends on how you want to use it... There's no requirement that the user running in the container must match the user who ran Podman. However, if you have volumes in the container, and you need to access them from the host, you generally will need to ensure the UIDs match. (Alternatively, you can use `podman unshare` to get a shell with UID/GID mappings matching the rootless container).

Technically, you'll also need 3 UID maps... One for UIDs below 23, one for 23 itself, one for UIDs about 23. Because of this, we generally recommend just running the service in the container as UID 0 - it's not really root, it's the user that launched the container, so you don't give up anything in terms of security.

**Comment by juansuerogit** [comment] 2019-06-24 22:59
ok thanks that got me past that error but now im running rootless and getting image related errors.

podman run -v /home/meta/backup:/root/backup -dt docker.io/centos:latest sleep 100

note: im using the fully qualified path here because without it i get another type of error.
and further more i cant seem to draw from the my companies registry either even though im docker logged in via their tools.  but currently stuck at this error.......


podman run -v /home/meta/backup:/root/backup -dt docker.io/centos:latest sleep 100

WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding subids 
Trying to pull docker.io/centos:latest...Getting image source signatures
Copying blob 8ba884070f61 done
Copying config 9f38484d22 done
Writing manifest to image destination
Storing signatures
ERRO[0026] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 0:54 for /run/lock/lockdev): lchown /run/lock/lockdev: invalid argument 
ERRO[0026] Error pulling image ref //centos:latest: Error committing the finished image: error adding layer with blob "sha256:8ba884070f611d31cb2c42eddb691319dc9facf5e0ec67672fcfa135181ab3df": ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 0:54 for /run/lock/lockdev): lchown /run/lock/lockdev: invalid argument 
Failed
Error: unable to pull docker.io/centos:latest: unable to pull image: Error committing the finished image: error adding layer with blob "sha256:8ba884070f611d31cb2c42eddb691319dc9facf5e0ec67672fcfa135181ab3df": ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 0:54 for /run/lock/lockdev): lchown /run/lock/lockdev: invalid argument

**Comment by mheon** [comment] 2019-06-24 23:01
`WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding subids`

There's your problem.

Do you have `newuidmap` and `newgidmap` binaries installed?

**Comment by juansuerogit** [comment] 2019-06-24 23:10
no the directions at https://github.com/containers/libpod/blob/master/install.md  didnt say to do this

**Comment by juansuerogit** [comment] 2019-06-24 23:28
ok i ran the directions at  https://www.scrivano.org/2018/10/12/rootless-podman-from-upstream-on-centos-7/

it gave me the newuidmap and newgidmap binaries and i rebooted.

now when i run 
podman run -v /home/meta/backup:/root/backup -dt docker.io/centos:latest sleep 100

i get
Error: error checking path "/home/meta/backup": stat /home/meta/backup: no such file or directory

isnt this suppose to work like docker.  i think docker creates the directory if its not there in the volume map.

**Comment by juansuerogit** [comment] 2019-06-24 23:31
In addition when i create the directory manually i cannot exec into the container... 

after running mkdir ./backup and then 
podman run -v /home/meta/backup:/root/backup -dt docker.io/centos:latest sleep 100

the container can be seen as running with
e1516b7986b9  docker.io/library/centos:latest  sleep 100  3 seconds ago  Up 2 seconds ago         nervous_williamson

but when i try to exec.. 

podman exec -ti -l bash
exec failed: container_linux.go:345: starting container process caused "process_linux.go:91: executing setns process caused \"exit status 22\""
Error: exit status 1

**Comment by mheon** [comment] 2019-06-24 23:32
@giuseppe Any idea about that exit status out of runc? Sounds like something we might have fixed in a more recent version.

**Comment by mheon** [comment] 2019-06-24 23:33
RE: the Docker issue - I'll look into this tomorrow. If we're not matching Docker, that's definitely a bug.

**Comment by juansuerogit** [comment] 2019-06-24 23:36
fyi my requirement is to be able to run rootless here is docker version... 
not sure if they are clashing.
i didnt install runc or anything else

docker version
Client:
 Version:           18.09.6

podman version
Version:            1.3.2

**Comment by rhatdan** [comment] 2019-06-25 10:29
We explicitly decided not to follow Docker on this one.  Creating a bind mount volume on the host when it does not exist.  I believe that this is a bug in Docker, since it could lead to user typos, being ignored an unexpected directories/volumes being created.

**Comment by rhatdan** [comment] 2019-06-25 10:30
There are other flags in the kernel that need to be set to use User Namespace on RHEL7/Centos 7.
@giuseppe PTAL

**Comment by giuseppe** [comment] 2019-06-25 11:45
I see different issues here.  The blog post I've written some time ago seems outdated, I'll need to write another one.

So the first thing: newuidmap/newgidmap seems to be missing, you'll need to install them, or most images won't work (same issue as https://github.com/containers/libpod/issues/3423).

You need to update runc, since the version you are using has different issues with rootless containers, .e.g. it will complain about `gid=5` using an unmapped UID even though that UID is present in the user namespace.

Currently upstream podman is broken for RHEL 7.5, the issue is being addressed with https://github.com/containers/libpod/pull/3397

**Comment by llchan** [comment] 2019-06-25 20:23
I have podman working on my normal host, but today when I went to try it on a different host I saw the "not enough IDs available" error mentioned here. I must be forgetting a step that I ran on the other host, so if we could put together a pre-flight checklist that would be helpful.  Off the top of my head here are the things I checked:
- newuidmap/newgidmap exist on PATH (version 4.7)
- runc exists on PATH (version 1.0.0-rc8)
- slirp4netns exists on PATH (version 0.3.0)
- conmon exists on PATH (version 1.14.4)
- /proc/sys/user/max_user_namespaces is large enough (16k)
- /etc/subuid and /etc/subgid have enough sub ids (64k, offset by a large number)
- $XDG_RUNTIME_DIR exists
- I ran `podman system migrate` to refresh the pause process

What am I forgetting?  Is there something I can run to pinpoint the issue?

**Comment by mheon** [comment] 2019-06-25 20:33
Is the image requesting an ID over 65k? Some images do include UIDs in the million range - those can break even for properly configured rootless.

**Comment by llchan** [comment] 2019-06-25 20:53
I don't think so, it said `(requested 0:42 for /etc/shadow)` for the alpine:latest I was testing with.

**Comment by rhatdan** [comment] 2019-06-25 20:55
Does podman unshare work?

podman unshare cat /proc/self/uid_map

**Comment by llchan** [comment] 2019-06-25 20:57
Yes, I think so:
```
$ podman unshare cat /proc/self/uid_map
         0      12345          1
```
`unshare -U` also appears to work.

**Comment by rhatdan** [comment] 2019-06-25 20:59
That indicates that the user executing podman unshare only has one UID 12345
I would guess that /etc/subuid does not have an entry for user 12345 USERNAME.

**Comment by llchan** [comment] 2019-06-25 22:06
Did a bit more snooping, looks like the podman log level is not set early enough, so the newuidmap debug output is getting swallowed. I built a binary with that log level bumped up and this is the error that causes the issue:
```
WARN[0000] error from newuidmap: newuidmap: open of uid_map failed: Permission denied
```

**Comment by mheon** [comment] 2019-06-25 22:11
Permissions issue on the binary?

**Comment by mheon** [comment] 2019-06-25 22:11
I'll tag @giuseppe in case it isn't that - he might have some ideas

**Comment by llchan** [comment] 2019-06-25 23:16
Binary is readable/executable and executes fine, but it looks like on this box where it's not working, it's owned by a user other than root:root (we deploy packages differently to that host). Is it required for it to be root:root to do its magic?

Also, is there any way to detect newuidmap for too old of a version? I have a colleague who ran into an issue with his PATH so it was falling back to the system newuidmap, and something other than an EPERM would have been nice.

**Comment by giuseppe** [comment] 2019-06-26 11:58
> Binary is readable/executable and runs fine, but it looks like it's owned by a user other than root:root (we deploy packages differently to that host). Is it required for it to be root:root to do its magic?

yes, newuidmap/newgidmap must be owned by root and it must either have fcaps enabled or installed as setuid.

**Comment by juansuerogit** [comment] 2019-06-26 14:40
So long story short I need to use RHEL 8?

**Comment by giuseppe** [comment] 2019-06-26 14:44
> So long story short I need to use RHEL 8?

that will surely help as all the needed pieces are there, including an updated kernel where you can use fuse-overlayfs.

**Comment by rhatdan** [comment] 2019-06-26 14:45
getcap /usr/bin/newuidmap 
/usr/bin/newuidmap = cap_setuid+ep

If this is not set then this will not work.

**Comment by juansuerogit** [comment] 2019-06-26 14:45
Is there a Podman-Compose?  How do i run the same container/container images iterated over in Dev with Podman and Buildah with a deployment to Amazon ECS, Azure AKS or IBM IKS?

**Comment by giuseppe** [comment] 2019-06-26 14:47
@juansuerogit you can use `podman generate kube` and `podman play kube`

**Comment by juansuerogit** [comment] 2019-06-26 14:50
So my friends on Mac are dead in the water.  I told them to get a Red Hat workstation they wouldnt listen :( :(

**Comment by llchan** [comment] 2019-06-26 18:50
Okay, I've confirmed that the owner of newuidmap must be root for it to work.  I'll pass that along to our package deployment people to see if we can find a workaround.

@rhatdan somehow getcap returns nothing even on the host that's working :thinking: 

Btw @juansuerogit sorry for sort of hijacking your thread, I thought it was related but maybe not :)

**Comment by rhatdan** [comment] 2019-06-27 00:27
@llchan Then it is probably setuid.

@juansuerogit I had a nice demo today of podman running on a MAC using podman-remote.  Should soon have packages available on Brew.

**Comment by giuseppe** [comment] 2019-06-29 09:19
@juansuerogit the discussion derailed a bit from the original issue you were having.  Have you had any chance to try again?  Keep in mind the uidmap for rootless works in the default user namespace we create, so you'll need to pick IDs in the range [0-number of IDs available], this for example should work:
`podman run -dt --uidmap 0:100:500 ubuntu sleep 1000`

**Comment by baude** [comment] 2019-08-02 18:17
@juansuerogit ?

**Comment by rhatdan** [comment] 2019-08-04 10:35
@juansuerogit reopen if you do not agree with the fix.

**Closed by rhatdan** 2019-08-04 10:35 UTC
Labels: kind/bug, retiring

**Comment by vrothberg** [comment] 2019-08-27 11:53
@rhatdan @giuseppe can you have a look?

**Comment by rusty-eagle** [comment] 2019-08-29 04:51
I had a similar problem on **openSUSE Tumbleweed**.  I had run the following commands:

> zypper in podman
> echo "jon:100000:65536" >> /etc/subuid
> echo "jon:100000:65536" >> /etc/subgid

But I was still getting errors like this:

> Error: error creating libpod runtime: there might not be enough IDs available in the namespace (requested 100000:100000 for /home/jon/.local/share/containers/storage/overlay/l): chown /home/jon/.local/share/containers/storage/overlay/l: invalid argument

And this:

>  Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 0:42 for /etc/shadow): lchown /etc/shadow: invalid argument

I could see that **newuidmap** and **newgidmap** are installed.  **The fix** for me was this command:

`podman system migrate`


##### system info #####
Distributor ID:	openSUSE
Description:	openSUSE Tumbleweed
Release:	20190824

5.2.9-1-default #1 SMP Fri Aug 16 20:25:11 UTC 2019 (80c0ffe) x86_64 x86_64 x86_64 GNU/Linux

**Comment by vrothberg** [comment] 2019-08-29 07:19
Thanks for the info, @rusty-eagle! `system migrate` is usually needed when upgrading to a new version of Podman. I assume that the package missed adding that to the post-install section (Cc @marcov @flavio @sysrich). @lsm5, @mheon, how's Fedora tackling migration? I couldn't find references in the spec files.

**Comment by marcov** [comment] 2019-08-29 08:46
@vrothberg , that's something defintely missing in the "post-install" section.
A couple of points:
- is it OK doing that at every package upgrade?
- you may consider adding a hint for the `podman system migrate` command for libpod runtime failures like those.

**Comment by vrothberg** [comment] 2019-08-29 08:49
> is it OK doing that at every package upgrade?

@mheon and @lsm5 will know.

> you may consider adding a hint for the podman system migrate command for libpod runtime failures like those.

We definitely need to improve the error messages, especially for cases where we know how it can be resolved.

**Comment by marcov** [comment] 2019-08-29 09:20
@rusty-eagle: I'd like to know what's the set of commands you run on Tumbleweed to get:

> Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 0:42 for /etc/shadow): lchown /etc/shadow: invalid argument

and @vrothberg: do you know why `podman system migrate` fixed that?

**Comment by vrothberg** [comment] 2019-08-29 09:29
>  do you know why podman system migrate fixed that?

Not really, no. `migrate` is currently only focusing on locks and I don't see how that could impact unser-namespace issues.

**Comment by mheon** [comment] 2019-08-29 13:01
Migrate is actually unrelated to locks. It does configuration rewrites as
necessary to fix database issues from containers created with older
versions of Podman. As of now, that only includes one single issue.

However, it does have the side effect of forcing a full restart of all
containers including the rootless init process (for safety). That is
probably what is fixing the issue.

**Comment by ankon** [comment] 2019-10-21 10:36
For the record and future googlers: 

I had the same issue (`there might not be enough IDs available in the namespace (requested 0:42 for /etc/shadow): lchown /etc/shadow: invalid argument`). In my case I had `/etc/subuid` configured for my user (`echo ${LOGNAME}:100000:65536 > /etc/subuid`), but had failed to do the same for `/etc/subgid`. A warning pointing to `/etc/subgid` was shown on `podman build`. 
The problem persisted after that though, and doing `podman unshare cat /proc/self/uid_map` showed:

```sh
$ podman unshare cat /proc/self/uid_map
         0       1000          1
```

Unfortunately I couldn't find what it _should_ show though, so in a moment of desparation I also executed `podman system migrate`.  That didn't say _anything_, but afterwards things started to work!

```sh
$ podman unshare cat /proc/self/uid_map
         0       1000          1
         1     100000      65536
```

So, if you can: 
1. Please add a pointer to to this somewhere in the documentation, _including the expected outputs_
2. Please make `podman system migrate` say _something_

**Comment by djmattyg007** [comment] 2019-11-17 11:53
I had the same experience as @ankon on a fresh install on Arch Linux. I'd configured `/etc/subuid` and `/etc/subgid` appropriately, but it simply did not work until I ran `podman system migrate`. I had the same output for `podman unshare cat /proc/self/uid_map`, and after running the migrate command it magically started working.

**Comment by gatoniel** [comment] 2020-03-30 18:26
Thanks, @ankon . The expected output of `podman unshare cat /proc/self/uid_map` was important for me, too.

On CentOS 8, it seems, one needs to run `podman system migrate` for each user that was added after the Podman installation. If you switch users with `su`, you need to use `su -`. Otherwise some old environment variables of the former user might conflict with the migrate command.

**Comment by bolind** [comment] 2020-04-28 11:19
I got similar errors, even with correctly configured /etc/subuid and /etc/subgid. Turns out, there's a known issue/bug when your home directory is on NFS. Try something like:

`mkdir /tmp/foo && podman --root=/tmp/foo --runroot=/tmp/foo run alpine uname -a`

**Comment by rhatdan** [comment] 2020-04-28 18:08
NFS homedirs are covered in the troubleshooting guide.

**Comment by djmattyg007** [comment] 2020-04-28 23:29
To clarify, the machine on which I encountered this definitely had no NFS-related anything installed or running.

**Comment by andrescodas** [comment] 2021-02-21 00:35
I'm running on rhel 8.3

I tried to follow your instructions but I still get:

```
there might not be enough IDs available in the namespace (requested 0:42 for /etc/gshadow): lchown /etc/gshadow: invalid argument
```
this is my output:
```
codas:~$ cat /etc/subuid
codas:100000:65536
codas:~$ cat /etc/subgid
codas:100000:65536
codas:~$ ls -ls /usr/bin/newuidmap
44 -rwsr-xr-x. 1 root root 40632 Aug  7  2020 /usr/bin/newuidmap
codas:~$ ls -ls /usr/bin/newgidmap
48 -rwsr-xr-x. 1 root root 44760 Aug  7  2020 /usr/bin/newgidmap
codas:~$ podman system migrate
codas:~$ podman unshare cat /proc/self/uid_map
         0       1000          1
```

Can someone help me figure out what am I missing?

**Comment by mheon** [comment] 2021-02-21 17:21
Have you tried running ‘podman system migrate’?

**Comment by andrescodas** [comment] 2021-02-22 12:49
@mheon 

>Have you tried running ‘podman system migrate’?

Yes.  It is the second to last command I executed as posted on my previous message [here](https://github.com/containers/podman/issues/3421#issuecomment-782771867)

**Comment by mheon** [comment] 2021-02-23 14:40
@giuseppe Any ideas? It looks like everything should be in order here.

**Comment by giuseppe** [comment] 2021-02-23 14:46
can you show the output of `id`?

**Comment by giuseppe** [comment] 2021-02-23 15:22
also any reason to use CentOS 7.5 and don't move to 8?

**Comment by andrescodas** [comment] 2021-02-23 16:51
@giuseppe 

I'm not running CentOS

```
codas:~$ hostnamectl
   Static hostname: caperucita
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: ddd81f6a73a6436690f6572752407787
           Boot ID: 1af9a1e06eee48a1ac73107081d45723
  Operating System: Red Hat Enterprise Linux 8.3 (Ootpa)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:8.3:GA
            Kernel: Linux 4.18.0-240.10.1.el8_3.x86_64
      Architecture: x86-64
codas:~$ id
uid=1000(codas) gid=1001(codas) groups=1001(codas),10(wheel),982(libvirt) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023

```

**Comment by andrescodas** [comment] 2021-02-23 18:03
@giuseppe 

```
codas:~$ getcap /usr/bin/newuidmap /usr/bin/newgidmap
/usr/bin/newuidmap = cap_setuid+ep
/usr/bin/newgidmap = cap_setgid+ep
codas:~$ unshare -U sleep 1000 &
[1] 509275
codas:~$ newuidmap $! 0 1000 1 1 100000 65536
newuidmap: open of uid_map failed: Permission denied
codas:~$ newgidmap $! 0 1000 1 1 100000 65536
newgidmap: gid range [0-1) -> [1000-1001) not allowed
```
should I use sudo?

**Comment by AdsonCicilioti** [comment] 2021-02-23 18:05
Hi guys,

My Outputs:

❯_ ~ cat /etc/subuid
`adson:100000:65536`

❯_ ~ cat /etc/subgid
`adson:100000:65536`

❯_ ~ ls -ls /usr/bin/newuidmap
`40 -rwxr-xr-x 1 root root 36992 Sep  7 10:42 /usr/bin/newuidmap`

❯_ ~ ls -ls /usr/bin/newgidmap
`44 -rwxr-xr-x 1 root root 41088 Sep  7 10:42 /usr/bin/newgidmap`

❯_ ~ podman system migrate

❯_ ~ podman unshare cat /proc/self/uid_map
 ```
         0       1000          1
         1     100000      65536
```
❯_ ~ podman run -d -p 3000:3000 heroku/nodejs-hello-world
`Error: error creating container storage: could not find enough available IDs`

On first time after fix with `podman system migrate` step, the container works fine, but after stoped it's not working more.

**Comment by giuseppe** [comment] 2021-02-23 18:18
> ```
> codas:~$ getcap /usr/bin/newuidmap /usr/bin/newgidmap
> /usr/bin/newuidmap = cap_setuid+ep
> /usr/bin/newgidmap = cap_setgid+ep
> codas:~$ unshare -U sleep 1000 &
> [1] 509275
> codas:~$ newuidmap $! 0 1000 1 1 100000 65536
> newuidmap: open of uid_map failed: Permission denied
> codas:~$ newgidmap $! 0 1000 1 1 100000 65536
> newgidmap: gid range [0-1) -> [1000-1001) not allowed
> ```
> 
> should I use sudo?

my mistake about newgid it should be:  `newgidmap $! 0 1001 1 1 100000 65536`

but newuidmap failed with EPERM, we need to figure out why that happened.  It is not under the Podman control.

Any message in the logs?  Can you also share `cat /proc/self/mountinfo`?



>  `Error: error creating container storage: could not find enough available IDs`

can you share the full message?  What ID was not found?

**Comment by AdsonCicilioti** [comment] 2021-02-23 18:35
> Hi guys,
> 
> My Outputs:
> 
> ❯_ ~ cat /etc/subuid
> `adson:100000:65536`
> 
> ❯_ ~ cat /etc/subgid
> `adson:100000:65536`
> 
> ❯_ ~ ls -ls /usr/bin/newuidmap
> `40 -rwxr-xr-x 1 root root 36992 Sep 7 10:42 /usr/bin/newuidmap`
> 
> ❯_ ~ ls -ls /usr/bin/newgidmap
> `44 -rwxr-xr-x 1 root root 41088 Sep 7 10:42 /usr/bin/newgidmap`
> 
> ❯_ ~ podman system migrate
> 
> ❯_ ~ podman unshare cat /proc/self/uid_map
> 
> ```
>         0       1000          1
>         1     100000      65536
> ```
> 
> ❯_ ~ podman run -d -p 3000:3000 heroku/nodejs-hello-world
> `Error: error creating container storage: could not find enough available IDs`
> 
> On first time after fix with `podman system migrate` step, the container works fine, but after stoped it's not working more.

After i run `podman system reset` and forced remove all lockeds storage dirs/files, all works again.

**Comment by andrescodas** [comment] 2021-02-23 18:58
@giuseppe 

> but newuidmap failed with EPERM, we need to figure out why that happened. It is not under the Podman control.

Can you suggest how to check the permissions?  I included in the commands `ls -last` so you can check the permissions details

>Any message in the logs? Can you also share cat /proc/self/mountinfo?

I'm posting  `/proc/self/mountinfo` let me know if you need other log?

> can you share the full message?

I posted  `/proc/self/mountinfo` let me know if it is other message you need

> What ID was not found?

I do not know of what ID you are talking about...  I didn't see any message talking about a missing ID

```
codas:~$ getcap /usr/bin/newuidmap /usr/bin/newgidmap
/usr/bin/newuidmap = cap_setuid+ep
/usr/bin/newgidmap = cap_setgid+ep

codas:~$ unshare -U sleep 1000 &
[3] 580141

codas:~$ ls -last $(which newuidmap)
44 -rwsr-xr-x. 1 root root 40632 Aug  7  2020 /usr/bin/newuidmap

codas:~$ newuidmap $! 0 1000 1 1 100000 65536
newuidmap: open of uid_map failed: Permission denied

codas:~$ ls -last $(which newgidmap)
48 -rwsr-xr-x. 1 root root 44760 Aug  7  2020 /usr/bin/newgidmap

codas:~$ newgidmap $! 0 1001 1 1 100000 65536
newgidmap: open of gid_map failed: Permission denied

cat /proc/self/mountinfo > mountinfo.txt
```
[mountinfo.txt](https://github.com/containers/podman/files/6031221/mountinfo.txt)

**Comment by giuseppe** [comment] 2021-02-23 19:36
thanks, that was helpful.  newuidmap and newgidmap seem to have both setuid and file capabilities.

Does `rpm -V shadow-utils` report any issue?

Can you reinstall the shadow-utils package?

This is how it looks for me on CentOS 8:

```
$ ls -last /usr/bin/new?idmap
44 -rwxr-xr-x. 1 root root 44760 Aug 12  2020 /usr/bin/newgidmap
40 -rwxr-xr-x. 1 root root 40632 Aug 12  2020 /usr/bin/newuidmap
```



> > 
> 
> I do not know of what ID you are talking about... I didn't see any message talking about a missing ID

sorry that was a question for @AdsonCicilioti

**Comment by andrescodas** [comment] 2021-02-23 19:59
@giuseppe 

thank you very much, seems that the re-installation of shadow-utils helped. This is the output just in case:

```
codas:~$ rpm -V shadow-utils                                                                                                                                                                 [2652/2652]
S.5....T.  c /etc/login.defs                                                                                                                                                                               
.M.......    /usr/bin/newgidmap                                                                                                                                                                            
.M.......    /usr/bin/newuidmap   

codas:~$ sudo dnf reinstall -y shadow-utils
Last metadata expiration check: 1:16:16 ago on Tue 23 Feb 2021 03:32:07 PM -03.
 Package                                       Architecture                            Version                                         Repository                                                      Size
============================================================================================================================================================================================================
  shadow-utils-2:4.6-11.el8.x86_64                                                                                                                                                                         
Transaction Summary
============================================================================================================================================================================================================

Total download size: 1.2 M
Installed size: 3.8 M
Downloading Packages:
shadow-utils-4.6-11.el8.x86_64.rpm                                                                                                                                          489 kB/s | 1.2 MB     00:02    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                       488 kB/s | 1.2 MB     00:02    
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                    1/1
  Reinstalling     : shadow-utils-2:4.6-11.el8.x86_64                                                                                                                                                   1/2
  Cleanup          : shadow-utils-2:4.6-11.el8.x86_64                                                                                                                                                   2/2
  Running scriptlet: shadow-utils-2:4.6-11.el8.x86_64                                                                                                                                                   2/2
  Verifying        : shadow-utils-2:4.6-11.el8.x86_64                                                                                                                                                   1/2
  Verifying        : shadow-utils-2:4.6-11.el8.x86_64                                                                                                                                                   2/2
Installed products updated.

Reinstalled:
  shadow-utils-2:4.6-11.el8.x86_64                                                                                                                                                                         

Complete!

codas:~$ getcap /usr/bin/newuidmap /usr/bin/newgidmap
/usr/bin/newuidmap = cap_setuid+ep
/usr/bin/newgidmap = cap_setgid+ep

codas:~$ unshare -U sleep 1000 &
[1] 654868

codas:~$ ls -last $(which newuidmap)
44 -rwxr-xr-x. 1 root root 40632 Aug  7  2020 /usr/bin/newuidmap

codas:~$ newuidmap $! 0 1000 1 1 100000 65536

codas:~$ ls -last $(which newgidmap)
48 -rwxr-xr-x. 1 root root 44760 Aug  7  2020 /usr/bin/newgidmap

codas:~$ newgidmap $! 0 1001 1 1 100000 65536

codas:~$ cat /proc/self/mountinfo > mountinfo.txt

codas:~$ rpm -V shadow-utils
S.5....T.  c /etc/login.defs

codas:~$ podman unshare cat /proc/self/uid_map
         0       1000          1
         1     100000      65536
``` 

[mountinfo.txt](https://github.com/containers/podman/files/6031526/mountinfo.txt)
