### ISSUE TITLE
podman image save & push are broken for archlinux/base

### ISSUE THREAD

**Issue by refi64** [containers/libpod#4081] opened 2019-09-23 01:28 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If I try to save the archlinux/base image, it fails.

**Steps to reproduce the issue:**

1. `podman pull archlinux/base`

2. `podman image save archlinux/base -o arch.tar`

3. Cry containerized tears.

**Describe the results you received:**

```
$ podman image save archlinux/base -o arch.tar
Error: unable to save "archlinux/base": Error copying image to the remote destination: Error writing blob: open /var/home/ryan/.local/share/containers/storage/overlay/6eb78788590649509a8dfa34066cdff59efc2e0597286fbc343354f8bf179c1d/merged/etc/X11/xinit/xinitrc.d/50-systemd-user.sh: no such file or director
```

**Describe the results you expected:**

```
$ podman image save archlinux/base -o arch.tar
*insert magic*
$ # arch.tar now exists
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm guessing `push` and `image save` traverse the same code paths?

**Output of `podman version`:**

```
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.7
  podman version: 1.5.1
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: podman-1.5.1-3.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.0, commit: d728afa06cd2df86a27f32a4692c7099a56acc97-dirty'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 2560729088
  MemTotal: 16553390080
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 8051044352
  SwapTotal: 8346660864
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: hp-fedora
  kernel: 5.2.14-200.fc30.x86_64
  os: linux
  rootless: true
  uptime: 83h 8m 48.42s (Approximately 3.46 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/ryan/.config/containers/storage.conf
  ContainerStore:
    number: 8
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/ryan/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 96
  RunRoot: /run/user/1000
  VolumePath: /var/home/ryan/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.5.1-3.fc30.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on Fedora Silverblue 30.

**Comment by mheon** [comment] 2019-09-23 01:59
@giuseppe Might this be a fuse-overlayfs error?

**Comment by giuseppe** [comment] 2019-09-23 04:59
yes, I think it is fuse-overlayfs and can be a duplicate of https://github.com/containers/buildah/issues/1867

**Comment by refi64** [comment] 2019-09-23 06:19
Ah that does seem to be it.

**Closed** 2019-09-23 06:19 UTC
Labels: kind/bug, rootless
