### ISSUE TITLE
flake: "Podman run ns" test has 'podman run ...' exit 2 instead of 0

### ISSUE THREAD

**Issue by wking** [containers/libpod#1039] opened 2018-07-02 17:26 UTC
In a recent master test, we [had][1]:

```
• Failure [6.461 seconds]
Podman run ns
/go/src/github.com/projectatomic/libpod/test/e2e/run_ns_test.go:10
  podman run ipcns test [It]
  /go/src/github.com/projectatomic/libpod/test/e2e/run_ns_test.go:48
  Expected
      <int>: 2
  to equal
      <int>: 0
  /go/src/github.com/projectatomic/libpod/test/e2e/run_ns_test.go:56
```

The failing call is [here][2]:

```go
session := podmanTest.Podman([]string{"run", "--ipc=host", fedoraMinimal, "ls", testFile})
```

We'd seen this [back in May as well][3].  With #1014, we should have access to the runc stderr via syslog.  Maybe we can work up a failure hook that dumps that syslog into something that Travis exposes.  Or we can wait until we get this flake again outside of Travis, because the non-Travis jobs may expose the syslog as an additional artifact.

[1]: https://travis-ci.org/projectatomic/libpod/jobs/399188583#L2832
[2]: https://github.com/projectatomic/libpod/blob/d357703e061258a57854df1880e23775dbe717ef/test/e2e/run_ns_test.go#L54
[3]: https://github.com/projectatomic/libpod/pull/829#issuecomment-391870118

**Comment by wking** [comment] 2018-07-02 17:34
On IRC, @mheon suggested capturing conmon's standard streams through a pipe so users don't have to hit the logs to get this information.  That's difficult for `create` workflows, where we're trying to daemonize `conmon`, and in doing so are closing its standard streams.  But a non-daemon `conmon` should be possible for `run` workflows.

**Comment by rhatdan** [comment] 2018-07-13 13:08
Weird I would have figured this would have gotten a 125 similar to the linked issue, since I believe these test failures were caused by missing fedoraMinimal.
	fedoraMinimal      = "registry.fedoraproject.org/fedora-minimal:latest"

**Comment by baude** [comment] 2018-08-20 15:06
I don't believe we are seeing this flake anymore, closing ... can re-open if appears

**Closed by baude** 2018-08-20 15:06 UTC
Labels: flakes
