### ISSUE TITLE
podman doesn't pass --create-sandbox to slirp4netns even though it is supported

### ISSUE THREAD

**Issue by vextta** [containers/libpod#4296] opened 2019-10-18 08:54 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When starting a rootless container with slirp4netns network, the `--create-sandbox` option is not passed to slirp4netns even though it is supported.

**Steps to reproduce the issue:**

1. Verify that `--create-sandbox` is available in the output of `slirp4netns --help`.

2. Start a rootless container by `podman run -d --rm alpine sleep 60`.

3. Find the arguments passed to slirp4netns with `ps xa | grep slirp4netns`.

**Describe the results you received:**

`--create-sandbox` option is missing from the parameters passed to slirp4netns. 

``getpcaps `pgrep slirp4netns` `` outputs tons of capabilities.

**Describe the results you expected:**

`--create-sandbox` is passed to slirp4netns.

And ``getpcaps `pgrep slirp4netns` `` outputs only `cap_net_bind_service`.

**Additional information you deem important (e.g. issue happens only occasionally):**

A skimming of `libpod/libpod/networking_linux.go` indicates that in the `func checkSlirpFlags` podman looks for `--enable-sandbox`, instead of `--create-sandbox`, in the output of `slirp4netns --help` to determine the support for sandbox. But I am not sure whether this is a typo or has some historical reasons.

**Output of `podman version`:**

```
Version:            1.6.1
RemoteAPI Version:  1
Go Version:         go1.12.9
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.9
  podman version: 1.6.1
host:
  BuildahVersion: 1.11.2
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.1-1.fc30.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.1, commit: 4346fbe0b2634b05857973bdf663598081240374'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 132861952
  MemTotal: 1028444160
  OCIRuntime:
    package: runc-1.0.0-95.rc9.gitc1485a1.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9+dev
      commit: 0840802d505e28d3adcbc7a275cbeadbdf64ddec
      spec: 1.0.1-dev
  SwapFree: 1709174784
  SwapTotal: 1719660544
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: localhost.localdomain
  kernel: 5.3.6-200.fc30.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-4.git19d199a.fc30.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.2
      commit: 19d199a6ca424fcf9516320a327cedad85cf4dfb
  uptime: 21m 13.9s
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/user/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.6.4-2.fc30.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.6.4
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/user/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /run/user/1001
  VolumePath: /home/user/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.1-2.fc30.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 30 in VirtualBox

**Comment by giuseppe** [comment] 2019-10-18 12:57
the issue is that the `--create-sandbox` was only present in a rc release of slirp4netns, it later got renamed to `--enable-sandbox` and Podman is checking for that.  We need to update the version of the slirp4netns package we have in Fedora

**Comment by giuseppe** [comment] 2019-10-18 13:01
also there are some fixes in slirp4netns master that are not part of a release yet.

@AkihiroSuda could we tag a new release?

**Comment by AkihiroSuda** [comment] 2019-10-18 13:06
sure https://github.com/rootless-containers/slirp4netns/pull/156

**Comment by giuseppe** [comment] 2019-10-21 07:22
thanks, closing the issue since there is nothing we can do in Podman itself.

**Closed by giuseppe** 2019-10-21 07:22 UTC
Labels: kind/bug
