### ISSUE TITLE
podman: option parsing failed: Unknown option -n

### ISSUE THREAD

**Issue by iamgalaxie** [containers/libpod#3232] opened 2019-05-30 02:08 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Doing practically anything with podman exits with status code 1 due to command-line options parsing failure.

**Steps to reproduce the issue:**

One quick example:

1. `podman run -ti alpine:latest`

**Describe the results you received:**

```
$ podman run -ti alpine:latest
Trying to pull docker.io/library/alpine:latest...
Getting image source signatures
Copying blob e7c96db7181b done
Copying config 055936d392 done
Writing manifest to image destination
Storing signatures
option parsing failed: Unknown option -n
                                        Error: exit status 1
```

**Describe the results you expected:**

Anything but exiting with option parsing failure.

**Additional information you deem important (e.g. issue happens only occasionally):**

It happens with almost anything I do podman-related.

**Output of `podman version`:**

```
Version:            1.3.2-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.3.2-dev
host:
  BuildahVersion: 1.9.0-dev
  Conmon:
    package: 'conmon: /usr/libexec/crio/conmon'
    path: /usr/libexec/crio/conmon
    version: 'conmon version , commit: '
  Distribution:
    distribution: ubuntu
    version: "18.10"
  MemFree: 145453056
  MemTotal: 4030869504
  OCIRuntime:
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  hostname: galaxie-pc
  kernel: 4.18.0-20-generic
  os: linux
  rootless: true
  uptime: 18m 17.18s
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/galaxie/.config/containers/storage.conf
  ContainerStore:
    number: 31
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/galaxie/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 52
  RunRoot: /tmp/1000
  VolumePath: /home/galaxie/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I installed from the Ubuntu PPA.

**Comment by rlittlefield** [comment] 2019-05-30 02:51
I also have this same problem. I'm guessing this wasn't a problem in the previous versions, but I can't seem to find an older one available on Ubuntu PPA.

**Comment by rlittlefield** [comment] 2019-05-30 02:54
```
INFO[0000] running as rootless                          
DEBU[0000] Initializing boltdb state at /home/ryan/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver vfs                       
DEBU[0000] Using graph root /home/ryan/.local/share/containers/storage 
DEBU[0000] Using run root /tmp/1001                     
DEBU[0000] Using static dir /home/ryan/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1001/libpod/tmp      
DEBU[0000] Using volume path /home/ryan/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "vfs"   
DEBU[0000] Initializing event backend journald          
DEBU[0000] parsed reference into "[vfs@/home/ryan/.local/share/containers/storage+/tmp/1001]docker.io/library/python:3.7-stretch" 
DEBU[0000] parsed reference into "[vfs@/home/ryan/.local/share/containers/storage+/tmp/1001]@a4cc999cf2aaafbe0b934b74be5a55cb3b8bd9349856131bea3579428b4155bf" 
DEBU[0000] exporting opaque data as blob "sha256:a4cc999cf2aaafbe0b934b74be5a55cb3b8bd9349856131bea3579428b4155bf" 
DEBU[0000] parsed reference into "[vfs@/home/ryan/.local/share/containers/storage+/tmp/1001]@a4cc999cf2aaafbe0b934b74be5a55cb3b8bd9349856131bea3579428b4155bf" 
DEBU[0000] exporting opaque data as blob "sha256:a4cc999cf2aaafbe0b934b74be5a55cb3b8bd9349856131bea3579428b4155bf" 
DEBU[0000] parsed reference into "[vfs@/home/ryan/.local/share/containers/storage+/tmp/1001]@a4cc999cf2aaafbe0b934b74be5a55cb3b8bd9349856131bea3579428b4155bf" 
DEBU[0000] Got mounts: []                               
DEBU[0000] Got volumes: []                              
DEBU[0000] Using slirp4netns netmode                    
DEBU[0000] created OCI spec and options for new container 
DEBU[0000] Allocated lock 8 for container 2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a 
DEBU[0000] parsed reference into "[vfs@/home/ryan/.local/share/containers/storage+/tmp/1001]@a4cc999cf2aaafbe0b934b74be5a55cb3b8bd9349856131bea3579428b4155bf" 
DEBU[0000] exporting opaque data as blob "sha256:a4cc999cf2aaafbe0b934b74be5a55cb3b8bd9349856131bea3579428b4155bf" 
DEBU[0001] created container "2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a" 
DEBU[0001] container "2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a" has work directory "/home/ryan/.local/share/containers/storage/vfs-containers/2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a/userdata" 
DEBU[0001] container "2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a" has run directory "/tmp/1001/vfs-containers/2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a/userdata" 
DEBU[0001] New container created "2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a" 
DEBU[0001] container "2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a" has CgroupParent "/libpod_parent/libpod-2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a" 
DEBU[0001] Handling terminal attach                     
DEBU[0001] mounted container "2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a" at "/home/ryan/.local/share/containers/storage/vfs/dir/1373a4490d0f15064c7b8c58c47413adca1448376c8b213129975c37076c99a2" 
DEBU[0001] Created root filesystem for container 2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a at /home/ryan/.local/share/containers/storage/vfs/dir/1373a4490d0f15064c7b8c58c47413adca1448376c8b213129975c37076c99a2 
INFO[0001] No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 nameserver 8.8.4.4] 
INFO[0001] IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844] 
DEBU[0001] /etc/system-fips does not exist on host, not mounting FIPS mode secret 
DEBU[0001] Created OCI spec for container 2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a at /home/ryan/.local/share/containers/storage/vfs-containers/2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a/userdata/config.json 
DEBU[0001] /usr/libexec/crio/conmon messages will be logged to syslog 
DEBU[0001] running conmon: /usr/libexec/crio/conmon      args=[-c 2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a -u 2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a -n keen_lumiere -r /usr/bin/runc -b /home/ryan/.local/share/containers/storage/vfs-containers/2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a/userdata -p /tmp/1001/vfs-containers/2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a/userdata/pidfile --exit-dir /run/user/1001/libpod/tmp/exits --conmon-pidfile /tmp/1001/vfs-containers/2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/ryan/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /tmp/1001 --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg cgroupfs --exit-command-arg --tmpdir --exit-command-arg /run/user/1001/libpod/tmp --exit-command-arg --runtime --exit-command-arg runc --exit-command-arg --storage-driver --exit-command-arg vfs --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a --socket-dir-path /run/user/1001/libpod/tmp/socket -t -l k8s-file:/home/ryan/.local/share/containers/storage/vfs-containers/2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a/userdata/ctr.log --log-level debug --syslog]
WARN[0001] Failed to add conmon to cgroupfs sandbox cgroup: mkdir /sys/fs/cgroup/systemd/libpod_parent: permission denied 
option parsing failed: Unknown option -n
                                        DEBU[0001] Cleaning up container 2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a 
DEBU[0001] Network is already cleaned up, skipping...   
DEBU[0001] unmounted container "2d5de2f99d9c1fb9aefc461203749c3b02e292f5684858fd9eafc82cfea1004a" 
ERRO[0001] exit status 1                   
```

**Comment by mheon** [comment] 2019-05-30 02:54
Is this just `podman run` or any command?

**Comment by mheon** [comment] 2019-05-30 02:55
Oh oh oh, it's not us, it's conmon. That explains it.

@lsm5 We're going to need to have the PPA point at `github.com/containers/conmon` and build master there, instead of CRI-O's version.

**Comment by mheon** [comment] 2019-05-30 02:55
It helps when I hit the right button and don't accidentally close things

**Comment by rlittlefield** [comment] 2019-05-30 02:58
> Is this just `podman run` or any command?

It sounds like you already know what the problem is, but it mainly seems to be related to `run`. I don't get the problem any other way, but many commands require a container first.

**Comment by mheon** [comment] 2019-06-06 20:02
Fix landed for the PPA, so closing

**Closed by mheon** 2019-06-06 20:02 UTC
Labels: kind/bug

**Comment by pck** [comment] 2019-06-12 07:30
PPA has an updated conmon for Ubuntu 18.04 but not for 16.04.

**Comment by rhatdan** [comment] 2019-06-12 07:54
@lsm5 ^^

**Comment by jakefanvote** [comment] 2019-06-15 22:04
On 16.04 same issue.

**Comment by mbigras** [comment] 2019-06-21 20:37
This is an issue for me on ubuntu 16.04, I'm not able to run `podman run` without any options:

```
vagrant@srv0:~$ lsb_release -r
Release:	16.04
vagrant@srv0:~$ podman --version
podman version 1.4.0
vagrant@srv0:~$ podman run alpine echo hello world
option parsing failed: Unknown option -n
Error: exit status 1
vagrant@srv0:~$ sudo docker run alpine echo hello world
hello world
```

**Comment by mheon** [comment] 2019-06-21 20:56
I'll poke @lsm5 again and ask about getting this fixed
