### ISSUE TITLE
Connection to pod can only be established once

### ISSUE THREAD

**Issue by mlezajic** [containers/libpod#5745] opened 2020-04-07 11:07 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After upgrading from podman **v1.6.4** to **v1.8.2**  we experience the problem that any newly created pod allows exactly ONE connection attempt while subsequent connection attempts are
rejected.

**Steps to reproduce the issue:**

1. Create a new pod from scratch with just one port mapping: 

   <code>podman pod create -p 4545:8080 --name testpod</code>

2. Start the pod: 

   <code>podman pod start testpod</code>

   
3. Connect to the pod using ncat: 

   <code>nc -v localhost 4545 </code>
   <code>  Ncat: Version 7.70 ( https://nmap.org/ncat ) </code>
   <code> Ncat: Connected to ::1:4545. </code>
   

4. Terminate the ncat connection and repeat step 3, now the connection attempt is rejected: 

   <code>nc -v localhost 4545 </code>
   <code>Ncat: Version 7.70 ( https://nmap.org/ncat ) </code>
   <code>Ncat: Connection to ::1 failed: Connection refused. </code>
   <code>Ncat: Trying next address... </code>
   <code>Ncat: Connection refused. </code>

   
5. Any subsequent connection attempt fail as well UNLESS the pod gets restarted: 

   <code>podman pod stop testpod ; podman pod start testpod </code> 

**Describe the results you received:**

A connection to a pod can only be established once, subsequent connection attempts fail (unless the pod is restarted).

**Describe the results you expected:**

Several connections can be made to a running pod.

**Additional information you deem important (e.g. issue happens only occasionally):**

- Issue can be reproduced
- Never expierenced this problem in v1.6.4
- podman is used/running in rootless mode
- We upgraded to v1.8.2 using the instuctions from the podman website respectively the Kubic project/stream:

```
sudo dnf -y module disable container-tools
sudo dnf -y install 'dnf-command(copr)'
sudo dnf -y copr enable rhcontainerbot/container-selinux
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/devel:kubic:libcontainers:stable.repo
sudo dnf -y install podman
```

**Output of `podman version`:**

```
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.8.2
host:
  BuildahVersion: 1.14.3
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module_el8.1.0+272+3e64ee36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 7a4f0dd7b20a3d4bf9ef3e5cbfac05606b08eac0'
  Distribution:
    distribution: '"centos"'
    version: "8"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1020
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1020
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
  MemFree: 95430443008
  MemTotal: 105331625984
  OCIRuntime:
    name: runc
    package: runc-1.0.0-64.rc9.module_el8.1.0+272+3e64ee36.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 1048571904
  SwapTotal: 1048571904
  arch: amd64
  cpus: 2
  eventlogger: file
  hostname: daisyt
  kernel: 4.18.0-147.5.1.el8_1.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.3-23.2.el8.x86_64
    Version: |-
      slirp4netns version 0.4.3-beta.1
      commit: b04291ba84ca35ccc60bd009372a28f9ea7ef841
  uptime: 22h 31m 39.37s (Approximately 0.92 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
store:
  ConfigFile: /home/fwd/.config/containers/storage.conf
  ContainerStore:
    number: 6
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-1.module_el8.1.0+272+3e64ee36.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  GraphRoot: /home/fwd/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 5
  RunRoot: /tmp/run-1020/containers
  VolumePath: /home/fwd/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.8.2-1.1.el8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

We run podman on a bare metal CentOS 8 server.
 
`cat /etc/os-release`:

```
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

**Comment by mheon** [comment] 2020-04-07 14:40
Running as root, or rootless?

**Comment by mlezajic** [comment] 2020-04-07 14:48
Hi @mheon,
thanks for the quick response. We operate podman in rootless mode.

**Comment by mheon** [comment] 2020-04-07 18:15
Possibly related to #5740

**Comment by mlezajic** [comment] 2020-04-08 08:47
#5740 talks about the port mappings being lost. This seems not to be the case here as 

<code>podman port -l</code> 

still lists the ports exposed by the pod even if the pod becomes inaccessible after the first connection attempt.

**Comment by mheon** [comment] 2020-04-08 13:54
Hm.
@giuseppe @AkihiroSuda PTAL

**Comment by giuseppe** [comment] 2020-04-08 15:12
I can reproduce with `1.8.1`, but not with the version from git master.

A bisect says it is fixed with 4841cd1630d892cd2e1353c88502235e79f2556f

@mlezajic could you check if it is solved for you as well?

**Comment by mlezajic** [comment] 2020-04-08 15:51
@giuseppe
how am i supposed to apply 4841cd1 ?

**Comment by giuseppe** [comment] 2020-04-08 16:35
> @giuseppe
> how am i supposed to apply [4841cd1](https://github.com/containers/libpod/commit/4841cd1630d892cd2e1353c88502235e79f2556f) ?

you could try directly the last version from git master

**Comment by mlezajic** [comment] 2020-04-09 06:22
> > @giuseppe
> > how am i supposed to apply [4841cd1](https://github.com/containers/libpod/commit/4841cd1630d892cd2e1353c88502235e79f2556f) ?
> 
> you could try directly the last version from git master

@giuseppe 
thanks for getting back to me. I am quite new to this so i have never run podman directly from git master. I guess i have to download/clone the repo and then build podman somehow or run it from within the cloned repo? Any advice would be highly appreciated.

**Comment by giuseppe** [comment] 2020-04-09 07:29
> > 
> 
> @giuseppe
> thanks for getting back to me. I am quite new to this so i have never run podman directly from git master. I guess i have to download/clone the repo and then build podman somehow or run it from within the cloned repo? Any advice would be highly appreciated.

yes exactly.  You'd need to clone the git repository at $GOPATH/src/github.com/containers/libpod.  A `make podman` should be enough to build podman (assuming you have installed all the dependencies).

Since you are running Centos 8, you can fetch the list of dependencies here: https://github.com/containers/libpod/blob/master/Dockerfile.centos#L3-L30 

Some packages might have a different name (e.g. go-md2man).

**Comment by mlezajic** [comment] 2020-04-09 10:53
> > > 
> > 
> > 
> > @giuseppe
> > thanks for getting back to me. I am quite new to this so i have never run podman directly from git master. I guess i have to download/clone the repo and then build podman somehow or run it from within the cloned repo? Any advice would be highly appreciated.
> 
> yes exactly. You'd need to clone the git repository at $GOPATH/src/github.com/containers/libpod. A `make podman` should be enough to build podman (assuming you have installed all the dependencies).
> 
> Since you are running Centos 8, you can fetch the list of dependencies here: https://github.com/containers/libpod/blob/master/Dockerfile.centos#L3-L30
> 
> Some packages might have a different name (e.g. go-md2man).

Thanks Giuseppe! I was able to pull all dependencies as well as building and installing a rpm with the latest code from git master using 

<code>make package-install</code> resulting in:

```
Version: 1.8.3-dev
RemoteAPI Version: 1
Go Version: go1.12.12
Git Commit: 12ff9c2648a0aa7d0727f57ff808fb88570c8fe6-dirty
Built: Thu Apr  9 11:17:26 2020
OS/Arch: linux/amd64
```

With this code level i no longer observe the problem. Do you have an estimate on when <code>v1.8.3</code> will officially be released? 

Once again many thanks for your help and Happy Easter.

**Closed** 2020-04-09 11:54 UTC
Labels: kind/bug

**Comment by rhatdan** [comment] 2020-04-09 12:50
We are planning on releasing v1.9.0 in the next week or two.  Not sure when this will bubble down to Centos.
