### ISSUE TITLE
[apiv2] can't build successfully an image from the given Dockerfile

### ISSUE THREAD

**Issue by chuanchang** [containers/libpod#6274] opened 2020-05-19 11:48 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. ./bin/podman system service --timeout 0 tcp:127.0.0.1:8080

2. to create a Dockerfile 

3. curl -v -X POST "http://localhost:8080/v1.40/build?dockerfile=./Dockerfile"|jq

**Describe the results you received:**
```
1. can successfully build an image from Dockerfile by podman cmdline
[fedora@fedora32 containers]$ ./libpod/bin/podman build -f Dockerfile
STEP 1: FROM busybox
Getting image source signatures
Copying blob d9cbbca60e5f done
Copying config 78096d0a54 done
Writing manifest to image destination
Storing signatures
STEP 2: COPY ./hello /hello
--> 09ed0df702c
STEP 3: RUN cat /hello
hello
STEP 4: COMMIT
--> a074a7c68b1
a074a7c68b17ce7cc941182b7a3833603a850f14243c34442c2ab693b0fdd68f

[fedora@fedora32 containers]$ ./libpod/bin/podman images|grep busybox
docker.io/library/busybox                 latest  78096d0a5478  5 days ago   1.44 MB

[fedora@fedora32 containers]$ ./libpod/bin/podman rmi busybox
Untagged: docker.io/library/busybox:latest

2. to build image w/ the same Dockerfile by curl
[fedora@fedora32 containers]$ curl -v -X POST "http://localhost:8080/v1.40/build?dockerfile=./Dockerfile"|jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1:8080...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1.40/build?dockerfile=./Dockerfile HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.69.1
> Accept: */*
>
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Date: Tue, 19 May 2020 11:27:18 GMT
< Content-Length: 506
<
{ [506 bytes data]
100   506  100   506    0     0   2032      0 --:--:-- --:--:-- --:--:--  2024
* Connection #0 to host localhost left intact
{
  "cause": "no such file or directory",
  "message": "error building at STEP \"ADD /$SCRIPT_BASE $GOSRC/$SCRIPT_BASE\": no files found matching \"/tmp/libpod_builder367071067/build/contrib/cirrus\": no such file or directory",
  "response": 500
}
{
  "stream": "\nFROM registry.fedoraproject.org/fedora:latest\nENV GOPATH=/var/tmp/go\nENV GOSRC=$GOPATH/src/github.com/containers/libpod\nENV SCRIPT_BASE=./contrib/cirrus\nENV PACKER_BASE=$SCRIPT_BASE/packer\nADD /$SCRIPT_BASE $GOSRC/$SCRIPT_BASE\nSuccessfully built \n"
}

NOTE: it still raised an error like 'no such file or directory' even though a absolute path is given for the Dockerfile, I also tried to use http encode to pass parameter to curl w/o double quota around URL, I got the same result. It is more puzzling that the registry.fedoraproject.org/fedora:latest is pulled on the local.

[fedora@fedora32 containers]$ ./libpod/bin/podman images|grep busybox
[fedora@fedora32 containers]$ ./libpod/bin/podman images|grep fedora
registry.fedoraproject.org/fedora         latest  eb7134a03cd6  4 days ago   208 MB
```

**Describe the results you expected:**
```
Can build successfully an image from the given Dockerfile
```

**Additional information you deem important (e.g. issue happens only occasionally):**
```
[fedora@fedora32 libpod]$ ./bin/podman system service --timeout 0 tcp:127.0.0.1:8080 &
[1] 109052
[fedora@fedora32 libpod]$ This function is EXPERIMENTAL.
http: superfluous response.WriteHeader call from github.com/containers/libpod/pkg/api/handlers/utils.WriteJSON (handler.go:64)
```

**Output of `podman version`:**

```
Version:            2.0.0-dev
RemoteAPI Version:  1
Go Version:         go1.14.2
Git Commit:         0f8ad039235137d086b9fea33bb74b362e625cdd
Built:              Tue May 19 11:02:16 2020
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**
```
host:
  arch: amd64
  buildahVersion: 1.15.0-dev
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.15-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 33da5ef83bf2abc7965fc37980a49d02fdb71826'
  cpus: 4
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: fedora32
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.6.10-300.fc32.x86_64
  linkmode: dynamic
  memFree: 823971840
  memTotal: 4118323200
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.0.0-1.fc32.x86_64
    version: |-
      slirp4netns version 1.0.0
      commit: a3be729152a33e692cd28b52f664defbf2e7810a
      libslirp: 4.2.0
  swapFree: 0
  swapTotal: 0
  uptime: 195h 29m 51.01s (Approximately 8.12 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/fedora/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 3
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.0.0-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.0.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/fedora/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 9
  runRoot: /run/user/1000/containers
  volumePath: /home/fedora/.local/share/containers/storage/volumes
version:
  Built: 1589886136
  GitCommit: 0f8ad039235137d086b9fea33bb74b362e625cdd
  GoVersion: go1.14.2
  OsArch: linux/amd64
  RemoteAPIVersion: 1
  Version: 2.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
[fedora@fedora32 libpod]$ git rev-parse HEAD
0f8ad039235137d086b9fea33bb74b362e625cdd
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Opentack VM

**Comment by mheon** [comment] 2020-05-19 14:18
@vrothberg PTAL

**Comment by vrothberg** [comment] 2020-05-19 14:31
The usage of curl is not correct (see https://docs.docker.com/engine/api/v1.40/#operation/ImageBuild). The build endpoint expects a tarfile with the Dockerfile(s) and the entire build context:
```
 --request POST \
 --header "Content-Type: application/x-tar" \
 --data-binary "@context.tar" \
```

I have to leave the keyboard in a bit, so I cannot reproduce but the usage of this issue is wrong and Podman validly errors out.

**Comment by chuanchang** [comment] 2020-05-19 17:53
> 
> 
> The usage of curl is not correct (see https://docs.docker.com/engine/api/v1.40/#operation/ImageBuild). The build endpoint expects a tarfile with the Dockerfile(s) and the entire build context:
> 
> ```
>  --request POST \
>  --header "Content-Type: application/x-tar" \
>  --data-binary "@context.tar" \
> ```
> 
Thanks, but I haven't found related documentation about 'header Parameters' in http://docs.podman.io/en/latest/_static/api.html#operation/buildImage

**Comment by rhatdan** [comment] 2020-05-19 19:29
It would be great to get these curl commands into a test suite that we could run on each PR.

**Comment by vrothberg** [comment] 2020-05-20 08:00
> > The usage of curl is not correct (see https://docs.docker.com/engine/api/v1.40/#operation/ImageBuild). The build endpoint expects a tarfile with the Dockerfile(s) and the entire build context:
> > ```
> >  --request POST \
> >  --header "Content-Type: application/x-tar" \
> >  --data-binary "@context.tar" \
> > ```
> 
> Thanks, but I haven't found related documentation about 'header Parameters' in http://docs.podman.io/en/latest/_static/api.html#operation/buildImage

That's a fair point. The docs should mention that.

**Comment by chuanchang** [comment] 2020-05-21 09:13
@vrothberg , I still can't get expected result w/ above parameters, maybe, I'm wrong, could you give a cmdline example?  thanks!

```
$ file /tmp/busybox-latest.tar
/tmp/busybox-latest.tar: POSIX tar archive

$ curl -v -X POST -H "Content-Type: application/x-tar" --data-binary "@busybox-latest.tar" http://localhost:8080/v1.40/libpod/build|jq
Note: Unnecessary use of -X or --request, POST is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1:8080...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1.40/libpod/build HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.69.1
> Accept: */*
> Content-Type: application/x-tar
> Content-Length: 1446400
> Expect: 100-continue
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 21 May 2020 09:10:24 GMT
< Content-Length: 10
< Connection: close
<
{ [10 bytes data]
  0 1412k  100    10    0     0   5000      0 --:--:-- --:--:-- --:--:--  5000
* Closing connection 0
parse error: Invalid numeric literal at line 1, column 4
```

**Comment by apollo13** [comment] 2020-05-22 12:33
@chuanchang You are getting back a 404, `v1.40/libpod/build` doesn't exist. You most likely ment `v1.40/build` instead since that are the docker api endpoints.

**Comment by baude** [comment] 2020-05-22 13:45
i also just made a change upstream so libpod/build now exists.

**Comment by chuanchang** [comment] 2020-05-26 04:10
Both the /libpod/build and /build didn't work for me, if my cmdline is wrong please correct me, thanks.

```
[fedora@fedora32 libpod]$ git rev-parse HEAD
1077d2d0b72d027a01080c0d3ebdb7d99a969661

[fedora@fedora32 containers]$ cat Dockerfile
FROM busybox
RUN echo hello

[fedora@fedora32 containers]$ tar cvf Dockerfile.tar Dockerfile
Dockerfile

[fedora@fedora32 containers]$ file Dockerfile.tar
Dockerfile.tar: POSIX tar archive (GNU)

[fedora@fedora32 containers]$ curl -v -X POST -H "Content-Type: application/x-tar" --data-binary "@Dockerfile.tar" http://localhost:8080/v1.40/libpod/build|jq
Note: Unnecessary use of -X or --request, POST is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1:8080...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1.40/libpod/build HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.69.1
> Accept: */*
> Content-Type: application/x-tar
> Content-Length: 10240
>
} [10240 bytes data]
* upload completely sent off: 10240 out of 10240 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Date: Tue, 26 May 2020 03:48:58 GMT
< Content-Length: 236
<
{ [236 bytes data]
100 10476  100   236  100 10240    979  42489 --:--:-- --:--:-- --:--:-- 43650
* Connection #0 to host localhost left intact
{
  "cause": "no such file or directory",
  "message": "error building at STEP \"ADD /$SCRIPT_BASE $GOSRC/$SCRIPT_BASE\": no files found matching \"/tmp/libpod_builder589466626/build/contrib/cirrus\": no such file or directory",
  "response": 500
}

[fedora@fedora32 containers]$ curl -v -X POST -H "Content-Type: application/x-tar" --data-binary "@Dockerfile.tar" http://localhost:8080/v1.40/build|jq
Note: Unnecessary use of -X or --request, POST is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1:8080...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1.40/build HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.69.1
> Accept: */*
> Content-Type: application/x-tar
> Content-Length: 10240
>
} [10240 bytes data]
* upload completely sent off: 10240 out of 10240 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Date: Tue, 26 May 2020 03:49:16 GMT
< Content-Length: 236
<
{ [236 bytes data]
100 10476  100   236  100 10240   1035  44912 --:--:-- --:--:-- --:--:-- 45947
* Connection #0 to host localhost left intact
{
  "cause": "no such file or directory",
  "message": "error building at STEP \"ADD /$SCRIPT_BASE $GOSRC/$SCRIPT_BASE\": no files found matching \"/tmp/libpod_builder041902975/build/contrib/cirrus\": no such file or directory",
  "response": 500
}
```

**Comment by vrothberg** [comment] 2020-06-22 12:19
Works for me. Closing. Feel free to reopen if it doesn't work for you.

**Closed by vrothberg** 2020-06-22 12:19 UTC
Labels: APIv2, kind/bug

**Comment by chuanchang** [comment] 2020-07-07 07:57
> Works for me. Closing. Feel free to reopen if it doesn't work for you.

It doesn't work well for me, the curl command can't still normally exit after 8 mins.

$ curl -v -X POST -H "Content-Type: application/x-tar" --data-binary "@Dockerfile.tar" http://localhost:8080/v1.40/libpod/build|jq
Note: Unnecessary use of -X or --request, POST is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1:8080...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1.40/libpod/build HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.69.1
> Accept: */*
> Content-Type: application/x-tar
> Content-Length: 10240
>
} [10240 bytes data]
* upload completely sent off: 10240 out of 10240 bytes
100 10240    0     0  100 10240      0     21  0:08:07  0:08:02  0:00:05     0   <------------  **Can't normally exit**

**Comment by baude** [comment] 2020-07-07 14:37
@chuanchang can you paste the full curl command here?

**Comment by chuanchang** [comment] 2020-07-10 03:47
> 
> 
> @chuanchang can you paste the full curl command here?

@baude I still used previous curl command, you can got it from https://github.com/containers/podman/issues/6274#issuecomment-654670255 and https://github.com/containers/podman/issues/6274#issuecomment-633797218, thanks!
