### ISSUE TITLE
Podman dies during interactive session exec due to disconnect

### ISSUE THREAD

**Issue by alitvak69** [containers/libpod#3226] opened 2019-05-29 15:13 UTC
/kind bug

**Description**

When running a shell script in the interactive shell with the terminal during exec , podman dies if session is disconnected.
 
**Steps to reproduce the issue:**
This is just an example, you can 
1.  Connect to your remote host via ssh.  Run bash in the podman e.g.
podman exec -it  containerx /bin/bash

2.  Run loop e.g.
while x=1; do  ls; sleep 1; done

3.  Disconnect ssh session

**Describe the results you received:**
Container dies.     
May 29 07:58:26 storage2n1-la sshd[5785]: Received disconnect from 10.10.8.142 port 33360:11: disconnected by user
May 29 07:58:26 storage2n1-la sshd[5785]: Disconnected from user root 10.10.8.142 port 33360
May 29 07:58:26 storage2n1-la sshd[5785]: pam_unix(sshd:session): session closed for user root
May 29 07:58:26 storage2n1-la ceph-mon-storage2n1-la[6614]: teardown: managing teardown after SIGCHLD
May 29 07:58:26 storage2n1-la ceph-mon-storage2n1-la[6614]: teardown: Sending SIGTERM to PID 173
May 29 07:58:26 storage2n1-la ceph-mon-storage2n1-la[6614]: debug 2019-05-29 07:58:26.956 7f393d287700 -1 received  signal: Terminated from  (PID: 259) UID: 0
May 29 07:58:26 storage2n1-la ceph-mon-storage2n1-la[6614]: debug 2019-05-29 07:58:26.956 7f393d287700 -1 mon.storage2n1-la@0(leader) e1 *** Got Signal Terminated ***
May 29 07:58:26 storage2n1-la systemd-logind[1256]: Removed session 524.
-- Subject: Session 524 has been terminated

**Describe the results you expected:**
Container stays alive with and bash session dies.   This works if I just do exec /bin/bash and don't run loop in that shell.

**Additional information you deem important (e.g. issue happens only occasionally):**
There is an additional problem.  The session dies uncleanly.  Systemd cannot restart it unless I do podman rm --force <container name>

**Output of `podman version`:**

```
Version:            1.3.2-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.3.2-dev
host:
  BuildahVersion: 1.9.0-dev
  Conmon:
    package: 'conmon: /usr/libexec/crio/conmon'
    path: /usr/libexec/crio/conmon
    version: 'conmon version , commit: '
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 117319438336
  MemTotal: 134647275520
  OCIRuntime:
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 6446641152
  SwapTotal: 6446641152
  arch: amd64
  cpus: 40
  hostname: storage2n1-la
  kernel: 4.18.0-20-generic
  os: linux
  rootless: false
  uptime: 163h 34m 28.88s (Approximately 6.79 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 8
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical host

**Comment by giuseppe** [comment] 2019-05-30 11:25
how have you created the container?

**Comment by alitvak69** [comment] 2019-05-31 00:02
ExecStart=/usr/bin/podman run --rm --name ceph-mon-%i \
  --log-opt path=/dev/null \
  --memory=128409m \
--cpus=1 \
-v /var/lib/ceph:/var/lib/ceph:z \
  -v /etc/ceph:/etc/ceph:z \
  -v /var/run/ceph:/var/run/ceph:z \
  -v /etc/localtime:/etc/localtime:ro \
--net=host \
-e IP_VERSION=4 \
  -e MON_IP=10.0.40.121 \
  -e CLUSTER=ceph \
  -e FSID=9b4468b7-5bf2-4964-8aec-4b2f4bee87ad \
  -e MON_PORT=3300 \
  -e CEPH_PUBLIC_NETWORK=10.0.40.0/23 \
  -e CEPH_DAEMON=MON \
  -e CONTAINER_IMAGE=docker.xcastlabs.net/ceph/daemon:latest-nautilus-centos-7-x86_64 \
   \
  docker.xcastlabs.net/ceph/daemon:latest-nautilus-centos-7-x86_64

**Comment by alitvak69** [comment] 2019-05-31 00:03
It is a ceph container

**Comment by mheon** [comment] 2019-06-11 18:50
@alitvak69 Are you running as root, or rootless?

**Comment by mheon** [comment] 2019-06-11 18:51
I'm wondering if this might be systemd killing the cgroup Podman is in.

**Comment by alitvak69** [comment] 2019-06-11 19:19
@mheon I am running as root

**Comment by mheon** [comment] 2019-06-11 19:21
Hmm. Is this exec only? The container in question keeps running, but the exec session dies?

**Comment by mheon** [comment] 2019-06-11 19:22
I *think* the conmon exec work from @haircommander - #3143 - will solve this one

**Comment by alitvak69** [comment] 2019-06-11 19:27
Container dies.  If exec would die I wouldn't complain.  Container dies not cleanly and I have to force remove it to start a new one.

**Comment by haircommander** [comment] 2019-06-11 19:30
how are you disconnecting ssh session?

**Comment by haircommander** [comment] 2019-06-11 19:30
(just wondering so I can test my patch to see if it does fix it like @mheon thinks)

**Comment by alitvak69** [comment] 2019-06-11 19:31
I believe it is reproducible with a similarly run container of any sort.  It doesn't have to be ceph.

**Comment by alitvak69** [comment] 2019-06-11 19:32
I have a terminal open with Xshell (could be any terminal software I guess)  and I click disconnect.

**Comment by alitvak69** [comment] 2019-06-11 19:33
Under linux / unix I beleive you could just close a terminal window.

**Comment by haircommander** [comment] 2019-06-11 19:39
I was unable to reproduce with
`podman run -d alpine top`
`podman exec -til /bin/sh`
`while x=1; do ls; sleep 1; done`
**disconnect**

@alitvak69 are you able to find a reproducer that is less complicated than the ceph container? otherwise, I can look into it more tomorrow. I feel similarly that the patch will at least not brick the container if the exec session is disconnected

**Comment by alitvak69** [comment] 2019-06-11 19:47
You are detaching container (-d) and I do not,

**Comment by alitvak69** [comment] 2019-06-11 19:48
Also, I run container via systemd unit perhaps this has anything to do with the issue?

**Comment by alitvak69** [comment] 2019-06-11 19:52
Maybe running some web server with --rm without -d  will help.   I guess I will try to find something later today,

**Comment by haircommander** [comment] 2019-06-11 19:54
@alitvak69 oh yes, I got it
1: `podman run alpine top` 
2: `podman exec -til /bin/sh`
2: `while x=1; do ls; sleep 1; done`
**kill 2**
**kill 1**
`Error: cannot remove container ffde6a6bf513b7bebe8d2480c46db953a711987da2a52570f05a65c22e57c9d5 as it has active exec sessions: container state improper`

The patch mentioned above doesn't fix, but it shouldn't be a bad follow up PR to fix this issue.

**Comment by baude** [comment] 2019-08-02 17:29
@haircommander is this fixed?

**Comment by haircommander** [comment] 2019-08-06 16:00
@baude @alitvak69 it is not fixed, but I'm actually not convinced it's a problem anymore. the behavior of having a running exec session in a container is similar to the container's main process running. Right now, to remove a running container, -f is needed, and it is similarly needed for a to remove a container with a running exec process.

**Comment by alitvak69** [comment] 2019-08-06 21:07
@haircommander I think it is a problem because exec is not killed by choice.  Yes we do it to reproduce the problem but exec is also dying if my ssh session is disconnected due to a connection failure for example

**Comment by alitvak69** [comment] 2019-08-06 21:19
@haircommander I understand that you need to cleanup with -f sometimes but I don't understand why running a bash script in container exec shell should cause the  whole thing to die during a terminal session disconnection.  I believe it should cause a script itself to die as well as exec session but not the running container.  Anyway, what would be a comparable docker or rkt behavior?  I used both and don't recall either had the same issue.

**Comment by rhatdan** [comment] 2019-08-07 18:32
I agree an exec session dieing should not cause the container to exit, just hte exec session.

**Comment by haircommander** [comment] 2019-08-07 18:47
@alitvak69 can you test master with your set up? given your description and @rhatdan's comment, this is actually fixed:
```1: podman run alpine top
2: podman exec -til /bin/sh
2: while x=1; do ls; sleep 1; done
disconnect 2
disconnect 1```
allows me to leave the top session running

**Comment by alitvak69** [comment] 2019-08-08 00:06
@haircommander What released version of podman I need to run in order to verify the fix?

**Comment by mheon** [comment] 2019-08-08 00:09
@alitvak69 We don't have a release including it yet, but we're in the process of cutting 1.5.0 which will include it - down to two PRs before it's done, so hopefully tomorrow.

**Comment by alitvak69** [comment] 2019-08-08 01:02
@haircommander  @mheon I am out this week so I will try testing it early next week and report it back to you.

**Comment by alitvak69** [comment] 2019-08-15 16:29
The box I could get for testing was a centos instance I was tasked with testing latest podman on centos in addition. :-)  Problem is the centos rpm 1.5.0.2 on CBS failed to build, and my attempt to use the f30 and cri-o branches on https://github.com/lsm5/rpm-builder/ failed due to my lack of understanding of how to get the environment ready.  Can any of you either look into 1.5.0.2 on CBS or better yet give me a hint on how to use git repo mentioned above to build those RPMs, this way I don't have to wait for new package to drop or bother you with that and can do builds based on master and tagged release going forward.

Thank you,

**Comment by alitvak69** [comment] 2019-08-17 18:16
I have tested with 1.5.1 and disconnecting ssh session while running the loop no longer kills the container.

**Comment by rhatdan** [comment] 2019-08-18 10:37
@alitvak69 So we can close this issue?

**Comment by alitvak69** [comment] 2019-08-18 13:12
Yes you can.  Thank you.

**Closed** 2019-08-18 23:06 UTC
Labels: kind/bug
