### ISSUE TITLE
segfault when using --init

### ISSUE THREAD

**Issue by thmo** [containers/libpod#3670] opened 2019-07-30 08:43 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman segfaults with `--init` if the executable used as init has wrong selabels.

**Steps to reproduce the issue:**

1. Build and install e.g. openSUSE/catatonit into `/usr/libexec/podman/catatonit`
2. Verify
    ```
    $ ls -lZ /usr/libexec/podman/catatonit              
    -rwxr-xr-x. 1 root root unconfined_u:object_r:user_home_t:s0 1806480 29. Jul 10:28 /usr/libexec/podman/catatonit
    ```
3. Run podman, segfaults
    ```
    $ podman run --rm -ti --init busybox || echo $?
    139
    ```
4. Fix label
    ```
    $ sudo restorecon -v /usr/libexec/podman/catatonit
    Relabeled /usr/libexec/podman/catatonit from unconfined_u:object_r:user_home_t:s0 to unconfined_u:object_r:bin_t:s0
    ```
5. Run podman, works
    ```
    podman run --rm -ti --init busybox
    / # 
    ```

**Describe the results you received:**

podman segfaults.

**Describe the results you expected:**

podman should print an error.

**Output of `podman version`:**

```
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.7
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.0.0-dev, commit: 164df8af4e62dc759c312eab4b97ea9fb6b5f1fc'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 3558744064
  MemTotal: 16812867584
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 8472489984
  SwapTotal: 8472489984
  arch: amd64
  cpus: 12
  hostname: XXXXXXXX
  kernel: 5.1.19-300.fc30.x86_64
  os: linux
  rootless: true
  uptime: 46h 27m 23.51s (Approximately 1.92 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/XXX/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/XXX/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 9
  RunRoot: /run/user/1000
  VolumePath: /home/XXX/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment] 2019-07-30 14:17
I'll take this.

**Comment by mheon** [comment] 2019-07-30 14:39
Hm. This doesn't look like a segfault. Podman itself is working fine, recording the exit code of the container. We get a proper AVC from the container's denied access.

@rhatdan Given that we're not seeing a segfault here, I think we're mostly functioning as designed, unless we want to force a relabel before starting containers?

**Comment by rhatdan** [comment] 2019-07-30 14:48
No the current behaviour is correct.  We don't want to randomly change labels.  This is up to the user to fix.
I am closing this as a not a bug.

**Closed by rhatdan** 2019-07-30 14:48 UTC
Labels: kind/bug

**Comment by thmo** [comment] 2019-07-30 15:14
But return code 139 signals segfault of the child, what am I missing?

**Comment by mheon** [comment] 2019-07-30 15:20
Podman is passing along the return codes from the process in the container - why it's 139, I'm not exactly sure, but SELinux is preventing init from running.
