### ISSUE TITLE
Can i redirect a detached containers stdout and stderr?

### ISSUE THREAD

**Issue by towe75** [containers/libpod#4560] opened 2019-11-23 15:55 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I'd like to redirect a detached containers stdout/stderr to a file/socket. 

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a issue i found while working on [nomad-driver-podman](https://github.com/pascomnet/nomad-driver-podman/issues/4). 

Nomad provides some nice integration for the two streams, it's enough to just redirect the content into a precreated socket.  As a POC i simply redirected podmans logger output and it works. The drawback is, however, that i can not distinguish between regular output and error messages.

So i wondered how to solve this in a better way:

1) i could use varlink attach and stream the content into nomads sockets
2) implement an alternative logger which can write two log streams/files instead of just one
3) more efficient: maybe conmon can redirect the streams directly?

Regarding 3, i found this in conmon sources:

https://github.com/containers/libpod/blob/3e2d9f8662663f2f703bf674408d5255e493e18e/libpod/oci_conmon_linux.go#L933

```
        // TODO this is probably a really bad idea for some uses
	// Make this configurable
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
```

**Comment by mheon** [comment] 2019-12-04 18:02
We're doing some unrelated work on the attach API endpoint that might make this easier, but no exact ETA on that yet.

**Comment by towe75** [comment] 2019-12-04 18:49
Hey @mheon, thanks for checking.
There is no real presure, so i'll wait for the attach API change.

**Comment by onlyjob** [comment] 2020-01-04 01:16
@github-actions is in denial of all valid issues, adding noise everywhere... :(

**Comment by rhatdan** [comment] 2020-01-04 11:26
I disagree, this is waking us up to old issues, that get buried on the stack.  When these happen primary contributors go back and review the issue and either allow it to be closed, or remove the stale flag.
I think this is better then just letting issues rot.

**Comment by onlyjob** [comment] 2020-01-04 13:41
I've seen it far too many times when such practice causes closure of legitimate issues because team member did not respond. People quickly learn that not answering tickets and letting them expire takes least effort.
Auto-closure is a _terrible_ practice for issue management and it is incredibly frustrating to reporters.
You see, when I care to report a problem and it can not be fixed because developers are busy or have greater priorities, it is fair, it is understandable. Reported issue then becomes a point of communication between others who is affected by it and you never know who might eventually contribute a patch.
But when the issue is closed without an action, that's denial, discouragement. A slap in the face of reporter and others who cares. A strong feedback saying "your issues are not important to us" which is not too different from private issue trackers.
An issue is an issue and the problem does not go away from closing the ticket because the real problem is prioritising. Just never ever (auto-)close actionable tickets without doing anything.

**Comment by vrothberg** [comment] 2020-01-04 14:08
I think @onlyjob is right. We don't want to scare off contributors. The intention of closure was more to get the developers immediate attention to prevent closure. I'll bump the limit to 356 days and rephrase the wording.

**Comment by rhatdan** [comment] 2020-01-04 15:32
On the other hand, leaving a issue to wither on the vine, because of lack of resources or lack of priority, is not much better.  Some times kicking the issue, is helpful to see if the reporter is still seeing the issue, or if the issue is even still important.

Just today, I closed two issues, that were >30 days and fixed in Master.

**Comment by baude** [comment] 2020-01-04 17:42
@vrothberg please bring up during scrum next week before making a change.

**Comment by vrothberg** [comment] 2020-01-07 10:05
I opened https://github.com/containers/libpod/pull/4788 before reading the comment

**Comment by baude** [comment] 2020-01-27 20:53
@mheon fixed? @towe75 have you been able to try master?

**Comment by mheon** [comment] 2020-01-27 22:43
I think that APIv2 should remove the need for this

**Comment by towe75** [comment] 2020-01-28 07:09
@mheon I was not aware about your ApiV2 branch until now, so i did not try it yet. I like the idea of not depending on varlink. 

But my question was actually about telling podman to redirect the streams to a different file or socket, regardless of the used api transport/encoding. 

I assume that the new API can poll/stream both streams to a client. This would help me to do a proper integration, although it's not the most elegant way.

**Comment by rhatdan** [comment] 2020-02-17 22:19
Since we are not updating varlink, closing this issue.

**Closed by rhatdan** 2020-02-17 22:19 UTC
Labels: do-not-close, kind/feature
