### ISSUE TITLE
podman list fails in rawhide

### ISSUE THREAD

**Issue by matthiasclasen** [containers/libpod#2935] opened 2019-04-15 02:24 UTC
```
$ rpm -q podman
podman-1.3.0-11.dev.git387d601.fc31.x86_64
$ podman list
ERRO[0000] open /run/user/1000/overlay-containers/0781aa62f52996e65e0eeea8dd18934c16dc53b448db2c03e253faf4e1ecb200/userdata/conmon.pid: permission denied 
```

**Comment by mheon** [comment] 2019-04-15 04:45
@giuseppe PTAL

**Comment by giuseppe** [comment] 2019-04-15 08:35
this is probably caused by the recent change of using only one namespace.

@matthiasclasen how many containers for the user are running?  I think it is required to stop them first, and then restarting them will ensure they are in the same user namespace

**Comment by matthiasclasen** [comment] 2019-04-15 12:24
none are running. this is after rebooting into a new silverblue image

**Comment by giuseppe** [comment] 2019-04-15 12:56
`/run/user/1000/overlay-containers` should be empty after a reboot.  How was the container 0781aa62f52996e65e0eeea8dd18934c16dc53b448db2c03e253faf4e1ecb200 created?

**Comment by matthiasclasen** [comment] 2019-04-15 13:06
```
$ sudo ls -l /run/user/1000/overlay-containers/0781aa62f52996e65e0eeea8dd18934c16dc53b448db2c03e253faf4e1ecb200 /run/user/1000/overlay-containers/0781aa62f52996e65e0eeea8dd18934c16dc53b448db2c03e253faf4e1ecb200/userdata
/run/user/1000/overlay-containers/0781aa62f52996e65e0eeea8dd18934c16dc53b448db2c03e253faf4e1ecb200:
total 0
drwx------. 2 100000 100000 160 Apr 14 22:21 userdata

/run/user/1000/overlay-containers/0781aa62f52996e65e0eeea8dd18934c16dc53b448db2c03e253faf4e1ecb200/userdata:
total 20
-rw-r--r--. 1 mclasen mclasen   4 Apr 14 22:21 conmon.pid
-rw-r--r--. 1  100000  100000   7 Apr 14 22:21 hostname
-rw-r--r--. 1  100000  100000 158 Apr 14 22:21 hosts
-rw-r--r--. 1 mclasen mclasen   4 Apr 14 22:21 pidfile
-rw-r--r--. 1 mclasen mclasen  35 Apr 14 22:21 resolv.conf
```

**Comment by giuseppe** [comment] 2019-04-15 13:25
so the issue we are hitting here was fixed by 6c6a8654363457a9638d58265d0a7e8743575d7a, unfortunately the fix doesn't work for containers that were created without the fix.

I wonder if we can add a command like "system rootless-restore" that stops all the containers, changes the configuration for the conmon pid file to be in the static directory and then restart the containers.

Matt, would it be ok?  What about changing the configuration?

**Comment by matthiasclasen** [comment] 2019-04-15 13:50
I don't know anything about podman configuration. You will have to tell me what I need to change.

**Comment by mheon** [comment] 2019-04-15 14:22
Hm. We have the core mechanism to do that from `system renumber`...

@giuseppe I'd call the command `podman system migrate` or something similar. There are a few other things that will require that.

**Comment by mheon** [comment] 2019-04-15 14:23
But no fundamental objection to adding a command that will migrate container configurations to change things like this, as long as we guarantee the containers are down when we make the changes.

**Comment by giuseppe** [comment] 2019-04-15 20:07
opened a PR here: https://github.com/containers/libpod/pull/2950

I've currently marked it as WIP as I'll continue working on it

**Closed** 2019-04-26 22:28 UTC
Labels: bug, rootless
