### ISSUE TITLE
Update of Podman to 1.9.2 via Kubic fails on Centos 8 because of dependency issue

### ISSUE THREAD

**Issue by stephan-klein** [containers/libpod#6272] opened 2020-05-19 07:56 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Install/Update Podman under Centos 8 via Kubic Repository as described here https://podman.io/getting-started/installation.html

**Describe the results you received:**
```
[root@eptossjboss05 yum.repos.d]# dnf update podman
Last metadata expiration check: 0:12:05 ago on Tue 19 May 2020 03:40:02 AM EDT.
Error:
 Problem: cannot install the best update candidate for package podman-1.8.2-1.1.el8.x86_64
  - nothing provides containernetworking-plugins >= 0.8.6-1 needed by podman-1.9.2-1.1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Describe the results you expected:**

Successful update of podman

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
[root@eptossjboss05 yum.repos.d]# podman --version
podman version 1.8.2
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.8.2
host:
  BuildahVersion: 1.14.3
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module_el8.1.0+272+3e64ee36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 7a4f0dd7b20a3d4bf9ef3e5cbfac05606b08eac0'
  Distribution:
    distribution: '"centos"'
    version: "8"
  MemFree: 12892454912
  MemTotal: 33559535616
  OCIRuntime:
    name: runc
    package: runc-1.0.0-60.rc8.module_el8.1.0+237+63e26edc.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 941076480
  SwapTotal: 2147479552
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: eptossjboss05.paradine.local
  kernel: 4.18.0-147.3.1.el8_1.x86_64
  os: linux
  rootless: false
  uptime: 2680h 26m 54.89s (Approximately 111.67 days)
registries:
  search:
  - registry.redhat.io
  - registry.access.redhat.com
  - quay.io
  - docker.io
  - dockerrep.paradine.at
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Last metadata expiration check: 0:13:51 ago on Tue 19 May 2020 03:40:02 AM EDT.
Installed Packages
Name         : podman
Version      : 1.8.2
Release      : 1.1.el8
Architecture : x86_64
Size         : 78 M
Source       : podman-1.8.2-1.1.el8.src.rpm
Repository   : @System
From repo    : devel_kubic_libcontainers_stable
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment] 2020-05-19 14:15
@vrothberg Any thoughts here?

**Comment by rhatdan** [comment] 2020-05-19 18:58
Can we update containernetworking-plugins >= 0.8.6-1?

**Comment by mheon** [comment] 2020-05-19 19:13
Ahh, this is an OBS-build Cent package - @lsm5 PTAL

**Comment by lsm5** [comment] 2020-05-19 19:26
my bad, seems like some of my changes in the autobuilder job didn't get done correctly for the plugins package. Fixing...

**Comment by lsm5** [comment] 2020-05-19 20:22
Done. Please close once you verify this works.

**Comment by lsm5** [comment] 2020-05-20 10:37
@stephan-klein Closing, please reopen if the issue isn't resolved for you.

**Closed by lsm5** 2020-05-20 10:37 UTC
Labels: CentOS 8, Packaging, obs
