### ISSUE TITLE
podman logs -f [multi] : incomplete output (nonroot only?)

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2692] opened 2019-03-18 16:18 UTC
/kind bug

Two containers running, both with `--rm`; `podman logs` is not seeing the final message from the last one to exit.
```
$ podman run -d --rm --name c1 alpine sh -c 'echo a;sleep 10;echo d';\
  podman run -d --rm --name c2 alpine sh -c 'echo b;sleep 3;echo c';\
  podman logs -f c1 c2
dc81d8fa3e56 a
ac284201b831 b
ac284201b831 c
[pause for a few seconds, then exit 0]
```
Expected: same pause, with a final `dc81 d` line.

I cannot reproduce when running as root. Rootless, reproduces about 90% of the time. Looks like a race condition but I don't understand why it would be rootless-only.

master @ ea54a1c2f51d3173649277939738ce9b1c392076

**Comment by rhatdan** [comment] 2019-03-18 17:17
So you are saying the `d` never gets printed?

**Comment by edsantiago** [comment] 2019-03-18 17:19
Running rootless, I see the `d` only about 10% of the time. The rest of the time, `podman logs` exits (successfully) after a few seconds; consistent with `c1` finishing.

**Comment by rhatdan** [comment] 2019-03-18 17:19
There is a race between podman logs seeing the output and the --rm erasing it.  I think it would be better for your tests to put a sleep at the end for a couple of seconds to remove the race.

**Comment by rhatdan** [comment] 2019-03-18 17:21
```
./bin/podman run -d --rm --name c1 alpine sh -c 'echo a;sleep 10;echo d; sleep 5';\
./bin/podman run -d --rm --name c2 alpine sh -c 'echo b;sleep 3;echo c; sleep 5';\
./bin/podman logs -f c1 c2
cd1a4b6e7f4059d5a835b04a6e164bf3cc5420c82ad8caedf92ef26c7e7f1f76
777361b4a40ceec499d010ff53a7d73ccc1d75bf4b397f6aafcdcf8e31ac3495
cd1a4b6e7f40 a
777361b4a40c b
777361b4a40c c
cd1a4b6e7f40 d
```

**Comment by edsantiago** [comment] 2019-03-18 17:22
Well, that's easy to do of course, but is it correct? Should a user expect that the final output of a container will be logged?

**Comment by rhatdan** [comment] 2019-03-18 17:22
As soon as the container exits, the --rm fires up and wipes out the log.  If the podman logs command does not wake up in time to see the changed logs, it will miss the change and the file will be gone.

**Comment by edsantiago** [comment] 2019-03-18 17:24
Understood. I'm suggesting that this may catch other users by surprise.

**Comment by rhatdan** [comment] 2019-03-18 17:27
Sure, but we don't have a real good way to fix it.  We could make podman logs timout to read shorter, but this is only making the issue less likely, while using up more CPU.

**Comment by cevich** [comment] 2019-03-19 15:45
If this behavior has to remain, it would be good to document the heck out of it.  I'm glad the issue is known now, but really pitty any non-expert trying to debug this behavior.  The least we can do is make the problem easy for google to index.

@rhatdan @mheon could we fix this by "cheating".  In other-words, an out-of-band logs update, not in the standard flow?  (I'm ignorant of the mechanics here)  Somehow have the the container going down, in it's death-throws, stuff the tail of the output somewhere accessable to the podman logs process, before closing it's fds and exiting, like a special fifo somewhere?

**Comment by cevich** [comment] 2019-03-19 16:03
That's actually not a bad idea at all.  Better to make the fact known in-line.  It's absence now and in the future would signal the problem was (somehow) fixed.  It would still probably be helpful to include a small warning in the 'podman logs' docs.  Are those hard to update?   /me wanders off to check

**Comment by baude** [comment] 2019-03-19 17:10
I have some long-term thoughts on logging which will fix this.  If we do anything, lets make it minimum effort for max reward.

**Comment by cevich** [comment] 2019-03-20 16:00
@baude yes, I agree.  Another +1 for "documentation update" then let google do the work to help people not hit this :smile:

**Comment by mheon** [comment] 2019-03-26 22:35
I believe we merged a docs update from @rhatdan about this

**Closed by mheon** 2019-03-26 22:35 UTC
Labels: kind/bug
