### ISSUE TITLE
Podman creates images that cannot be removed

### ISSUE THREAD

**Issue by bmaupin** [containers/libpod#3304] opened 2019-06-11 20:12 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

While creating a minimal test case for #3303, I managed to create images that I was unable to remove, even using `-f`.

**Steps to reproduce the issue:**

1. Create the Dockerfile

    ```
    $ echo 'FROM scratch
    LABEL org.opencontainers.image.authors="<somefolks@example.org>"
    LABEL org.opencontainers.image.created=2019-06-11T19:03:37Z
    LABEL org.opencontainers.image.description="This is a test image"
    LABEL org.opencontainers.image.title=test
    LABEL org.opencontainers.image.vendor="Example.org"
    LABEL org.opencontainers.image.version=1' > Dockerfile
    ```

2. Build the image

    ```
    $ podman build .
    STEP 1: FROM scratch
    STEP 2: LABEL org.opencontainers.image.authors="<somefolks@example.org>"
    --> 4ebea5977ec0993c77b4a614225076640a00883b72bee1b9e16aa1f7bba35d45
    STEP 3: LABEL org.opencontainers.image.created=2019-06-11T19:03:37Z
    --> 93f759f779d94830bf362b9c884346bf5a34f835fb50e3e717e7adbbf7f1afd7
    STEP 4: LABEL org.opencontainers.image.description="This is a test image"
    --> 2574ed1a96155670e8a139a39011dd5fc07f931d4cd235aebed0f50b1fa7314c
    STEP 5: LABEL org.opencontainers.image.title=test
    --> 619b496ce10a0f32051114a0feaabc33c59d1fafd66b517fca122ed8a214d486
    STEP 6: LABEL org.opencontainers.image.vendor="Example.org"
    --> 7aed0f33d0ad9f9b8c018fabb3e9470e0cc5101e5389a62186e40e43bf6500a4
    STEP 7: LABEL org.opencontainers.image.version=1
    STEP 8: COMMIT
    --> f881d3aec74db46b890745b89169333c5628bd588db5c5d698ab9ddc076a172e
    ```

3. Try to delete any of the built images

    ```
    $ podman image ls
    ERRO[0000] error checking if image is a parent "4ebea5977ec0993c77b4a614225076640a00883b72bee1b9e16aa1f7bba35d45": layer not known
    ERRO[0000] error checking if image is a parent "93f759f779d94830bf362b9c884346bf5a34f835fb50e3e717e7adbbf7f1afd7": layer not known
    ERRO[0000] error checking if image is a parent "2574ed1a96155670e8a139a39011dd5fc07f931d4cd235aebed0f50b1fa7314c": layer not known
    ERRO[0000] error checking if image is a parent "619b496ce10a0f32051114a0feaabc33c59d1fafd66b517fca122ed8a214d486": layer not known
    ERRO[0000] error checking if image is a parent "7aed0f33d0ad9f9b8c018fabb3e9470e0cc5101e5389a62186e40e43bf6500a4": layer not known
    ERRO[0000] error checking if image is a parent "f881d3aec74db46b890745b89169333c5628bd588db5c5d698ab9ddc076a172e": layer not known
    REPOSITORY   TAG      IMAGE ID       CREATED          SIZE
    <none>       <none>   f881d3aec74d   42 seconds ago   1.85 kB
    <none>       <none>   7aed0f33d0ad   43 seconds ago   1.68 kB
    <none>       <none>   619b496ce10a   44 seconds ago   1.48 kB
    <none>       <none>   2574ed1a9615   45 seconds ago   1.3 kB
    <none>       <none>   93f759f779d9   46 seconds ago   1.07 kB
    <none>       <none>   4ebea5977ec0   48 seconds ago   858 B

    $ podman rmi -f $(podman images -q)
    ERRO[0000] error checking if image is a parent "4ebea5977ec0993c77b4a614225076640a00883b72bee1b9e16aa1f7bba35d45": layer not known
    ERRO[0000] error checking if image is a parent "93f759f779d94830bf362b9c884346bf5a34f835fb50e3e717e7adbbf7f1afd7": layer not known
    ERRO[0000] error checking if image is a parent "2574ed1a96155670e8a139a39011dd5fc07f931d4cd235aebed0f50b1fa7314c": layer not known
    ERRO[0000] error checking if image is a parent "619b496ce10a0f32051114a0feaabc33c59d1fafd66b517fca122ed8a214d486": layer not known
    ERRO[0000] error checking if image is a parent "7aed0f33d0ad9f9b8c018fabb3e9470e0cc5101e5389a62186e40e43bf6500a4": layer not known
    ERRO[0000] error checking if image is a parent "f881d3aec74db46b890745b89169333c5628bd588db5c5d698ab9ddc076a172e": layer not known
    layer not known
    layer not known
    layer not known
    layer not known
    layer not known
    Error: layer not known

    $ podman image ls
    ERRO[0000] error checking if image is a parent "4ebea5977ec0993c77b4a614225076640a00883b72bee1b9e16aa1f7bba35d45": layer not known
    ERRO[0000] error checking if image is a parent "93f759f779d94830bf362b9c884346bf5a34f835fb50e3e717e7adbbf7f1afd7": layer not known
    ERRO[0000] error checking if image is a parent "2574ed1a96155670e8a139a39011dd5fc07f931d4cd235aebed0f50b1fa7314c": layer not known
    ERRO[0000] error checking if image is a parent "619b496ce10a0f32051114a0feaabc33c59d1fafd66b517fca122ed8a214d486": layer not known
    ERRO[0000] error checking if image is a parent "7aed0f33d0ad9f9b8c018fabb3e9470e0cc5101e5389a62186e40e43bf6500a4": layer not known
    ERRO[0000] error checking if image is a parent "f881d3aec74db46b890745b89169333c5628bd588db5c5d698ab9ddc076a172e": layer not known
    REPOSITORY   TAG      IMAGE ID       CREATED         SIZE
    <none>       <none>   f881d3aec74d   8 minutes ago   1.85 kB
    <none>       <none>   7aed0f33d0ad   8 minutes ago   1.68 kB
    <none>       <none>   619b496ce10a   8 minutes ago   1.48 kB
    <none>       <none>   2574ed1a9615   8 minutes ago   1.3 kB
    <none>       <none>   93f759f779d9   8 minutes ago   1.07 kB
    <none>       <none>   4ebea5977ec0   8 minutes ago   858 B
    ```

**Describe the results you received:**

Multiple images were created and I was unable to delete any of them.

**Describe the results you expected:**

I expected only one image to be created. I expected to be able to delete the created images.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.4.0
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.4.0
host:
  BuildahVersion: 1.8.3
  Conmon:
    package: 'conmon: /usr/libexec/crio/conmon'
    path: /usr/libexec/crio/conmon
    version: 'conmon version 0.2.0, commit: '
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 7144542208
  MemTotal: 16759091200
  OCIRuntime:
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8171274240
  SwapTotal: 8189374464
  arch: amd64
  cpus: 8
  hostname: workstation
  kernel: 4.18.0-21-generic
  os: linux
  rootless: true
  uptime: 95h 2m 39.19s (Approximately 3.96 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/user/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/user/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 6
  RunRoot: /tmp/1000
  VolumePath: /home/user/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine running Ubuntu 18.04.

**Comment by mheon** [comment] 2019-06-11 20:23
Could be related to #3266

**Comment by mheon** [comment] 2019-06-11 20:26
I think these are coming straight out of c/storage - it looks like we're getting all images via `store.Images()`, which returns a number of layers, but then subsequently asking c/storage about the image in question is causing errors? Hard to tell where, the error isn't being wrapped anywhere between cmd/podman and c/storage

**Comment by mheon** [comment] 2019-06-11 20:30
Confirmed that I can reproduce on master

**Comment by mheon** [comment] 2019-06-11 20:32
Interesting: `podman rmi --all --force` only catches one of the errors, I see a lot more on `podman images`

**Comment by mheon** [comment] 2019-06-11 20:34
Identical errors out of `buildah images`. I think this is definitely c/storage.

I'll ping @nalind but he's on vacation this week.

**Comment by mheon** [comment] 2019-06-11 20:37
Slightly more illuminating error in `podman image tree` on one of the remaining images:
```
sudo ./bin/podman image tree docker.io/library/alpine                                                                                                                                                                                      125 ↵
Error: error while retrieving layers of image "docker.io/library/alpine": top-layer for image 2f3dd30cc019e83aa6436ffeb307da4764be7d6883c0b99953c901573d1e1d38 not found local store
```

**Comment by mheon** [comment] 2019-06-11 20:37
So we've somehow ended up with images that are missing layers.

**Comment by mheon** [comment] 2019-06-11 20:38
Re-pulling the image doesn't fix it.

**Comment by mheon** [comment] 2019-06-11 20:38
@rhatdan PTAL, this one looks pretty bad

**Comment by mheon** [comment] 2019-06-11 20:43
I can still launch containers with affected images, and they still work as advertised - it's just removing that seems to be the problem?

**Comment by TomSweeneyRedHat** [comment] 2019-06-11 21:43
and/or @mtrmac  PTAL

**Comment by thawkins** [comment] 2019-06-12 11:27
has anybody checked the ownership of the container files in ~/.local/share/containers , I have been fighting with a problem in "toolbox" where i get this issue, and it appears the files are being created with the mappeduid and mappedgid uid/gid

executing the following makes them accessible and hence removable. 

sudo chown -R $USER:$USER /home/$USER/.local/share/containers

If the files where created with mappeduid:gid or uid:mappedgid that would probably work, allowing the $USER host context and the container context access to them

**Comment by mheon** [comment] 2019-06-12 13:03
Hmm. I'm running as root, so we're probably looking at two separate issues
here - but I'll give it a look

**Comment by bmaupin** [comment] 2019-06-12 13:48
> I can still launch containers with affected images, and they still work as advertised - it's just removing that seems to be the problem?

Yes, the only actual issues I noticed were that I couldn't remove the images and that more images were created than should've been (I would have expected no more than 1 image to be created since I wasn't using `ADD`, `COPY`, or `RUN`).

> has anybody checked the ownership of the container files in ~/.local/share/containers

I just checked and everything appeared to be owned by my  user. As such, `sudo chown -R $USER:$USER /home/$USER/.local/share/contain` doesn't seem to help unfortunately.

Thanks!

**Comment by mheon** [comment] 2019-06-18 15:37
@nalind PTAL - think we have a serious storage issue here

**Comment by nalind** [comment] 2019-06-28 18:30
@thawkins owner information on containers and images stored in your home directory gets mapped from their originally-specified range to ranges which `/etc/subuid` and `/etc/subgid` mark as available for your use, but since your typical shell session is still running as an unprivileged user, you can't always access their contents directly.  Running `podman unshare` opens a shell in a new user namespace where your own IDs appear to be uid=0:gid=0 from inside of the namespace, and the ranges from `/etc/subuid` and `/etc/subgid` are set up to appear to be the ranges starting at uid=1 and gid=1.  From that shell, you should be able to directly manipulate their contents, or remove them, without errors.

The changes in #3422 should be taking care of errors that we were hitting when an image didn't have any layers, at least for the `history`, `inspect`, `images`, `image list`, and `image tree` commands.

**Comment by pkubatrh** [comment] 2019-07-02 10:47
Can confirm #3422 fixed the issues I had with unremovable images.

**Comment by rhatdan** [comment] 2019-07-02 10:49
Can we close this issue?

**Comment by nalind** [comment] 2019-07-02 14:17
Yup!

**Closed by nalind** 2019-07-02 14:17 UTC
Labels: containers-storage, kind/bug
