### ISSUE TITLE
Cannot restore segment prot after reloc: Permission denied

### ISSUE THREAD

**Issue by gastaldi** [containers/libpod#3859] opened 2019-08-20 16:10 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I uninstalled Docker in my Fedora 30 and installed `podman` and `podman-docker`. However I get the following error when building my project (which uses Docker):

```
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] docker run -v /home/ggastald/workspace/quarkus/integration-tests/jgit/target:/project:z --rm --user 1000:1000 quay.io/quarkus/ubi-quarkus-native-image:19.1.1 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dio.netty.leakDetection.level=DISABLED -J-Dvertx.disableDnsResolver=true -J-Dio.netty.noUnsafe=true --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar quarkus-integration-test-jgit-999-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
Error occurred during initialization of VM
Unable to load JVMCI shared library: /opt/graalvm/jre/lib/amd64/libjvmcicompiler.so: cannot restore segment prot after reloc: Permission denied
```

**Steps to reproduce the issue:**

1. `git clone git@github.com:quarkusio/quarkus.git`

2. `cd quarkus && ./mvnw clean install -DskipTests`

3. `./mvnw install -Dnative -Dnative-image.docker-build=true -pl integration-tests/jgit`

**Describe the results you received:**
```
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:native-image (native-image) @ quarkus-integration-test-jgit ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on OpenJDK 64-Bit Server VM
Error: Could not create directory /project/.native-image/machine-id-
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] docker run -v /home/ggastald/workspace/quarkus/integration-tests/jgit/target:/project:z --rm --user 1000:1000 quay.io/quarkus/ubi-quarkus-native-image:19.1.1 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dio.netty.leakDetection.level=DISABLED -J-Dvertx.disableDnsResolver=true -J-Dio.netty.noUnsafe=true --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar quarkus-integration-test-jgit-999-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
Error occurred during initialization of VM
Unable to load JVMCI shared library: /opt/graalvm/jre/lib/amd64/libjvmcicompiler.so: cannot restore segment prot after reloc: Permission denied
Error: Image build request failed with exit status 1
```

**Describe the results you expected:**
Build success (it works with Docker installed)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:** 

```
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.7
  podman version: 1.5.1
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: podman-1.5.1-3.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.0, commit: d728afa06cd2df86a27f32a4692c7099a56acc97-dirty'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 17401413632
  MemTotal: 33072443392
  OCIRuntime:
    package: containerd.io-1.2.6-3.3.fc28.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8
      commit: 425e105d5a03fabd737a126ad93d62a9eeede87f
      spec: 1.0.1-dev
  SwapFree: 16129261568
  SwapTotal: 16605245440
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: ggastald-laptop
  kernel: 5.2.8-200.fc30.x86_64
  os: linux
  rootless: true
  uptime: 55h 12m 32.36s (Approximately 2.29 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/ggastald/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/ggastald/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /run/user/1000
  VolumePath: /home/ggastald/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.5.1-3.fc30.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on Fedora 30

**Comment by rhatdan** [comment] 2019-08-20 16:12
Looks like SELinux
ausearch -m avc -ts recent

**Comment by gastaldi** [comment] 2019-08-20 16:13
Running `sudo ausearch -m avc -ts recent` I get:
 `<no matches>`

**Comment by gastaldi** [comment] 2019-08-20 16:16
When disabling SELinux with: 
```
sudo /usr/sbin/setenforce 0
```

I get a different error:

```
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:native-image (native-image) @ quarkus-integration-test-jgit ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on OpenJDK 64-Bit Server VM
Error: Could not create directory /project/.native-image/machine-id-
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] docker run -v /home/ggastald/workspace/quarkus/integration-tests/jgit/target:/project:z --rm --user 1000:1000 quay.io/quarkus/ubi-quarkus-native-image:19.1.1 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dio.netty.leakDetection.level=DISABLED -J-Dvertx.disableDnsResolver=true -J-Dio.netty.noUnsafe=true --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar quarkus-integration-test-jgit-999-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[quarkus-integration-test-jgit-999-SNAPSHOT-runner:29]    classlist:   8,607.24 ms
[quarkus-integration-test-jgit-999-SNAPSHOT-runner:29]        (cap):   1,268.53 ms
[quarkus-integration-test-jgit-999-SNAPSHOT-runner:29]        setup:   2,569.59 ms
16:15:06,439 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta5
[quarkus-integration-test-jgit-999-SNAPSHOT-runner:29]   (typeflow):  19,667.03 ms
[quarkus-integration-test-jgit-999-SNAPSHOT-runner:29]    (objects):  15,855.84 ms
[quarkus-integration-test-jgit-999-SNAPSHOT-runner:29]   (features):   2,679.58 ms
[quarkus-integration-test-jgit-999-SNAPSHOT-runner:29]     analysis:  40,168.94 ms
Fatal error: jdk.vm.ci.common.JVMCIError: jdk.vm.ci.common.JVMCIError: java.nio.file.AccessDeniedException: /project/reports
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:457)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:308)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:446)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:112)
Caused by: jdk.vm.ci.common.JVMCIError: java.nio.file.AccessDeniedException: /project/reports
	at jdk.vm.ci.common.JVMCIError.shouldNotReachHere(JVMCIError.java:54)
	at com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:81)
	at com.oracle.graal.pointsto.reports.CallTreePrinter.print(CallTreePrinter.java:64)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:753)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:522)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:440)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.nio.file.AccessDeniedException: /project/reports
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:69)
	... 9 more
Error: Image build request failed with exit status 1

```

**Comment by gastaldi** [comment] 2019-08-20 16:22
It looks like it is caused by `--user 1000:1000`. Does that ring a bell @rhatdan ?

**Comment by rhatdan** [comment] 2019-08-20 16:25
If you run as root it works?  and if you run it with Docker it works?

**Comment by rhatdan** [comment] 2019-08-20 16:27
Could be in linux capabilities.

```
# podman run --user 1000:1000 fedora grep Cap /proc/self/status 
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	00000000a80425fb
CapAmb:	0000000000000000
# docker run --user 1000:1000 fedora grep Cap /proc/self/status 
CapInh:	00000000a80425fb
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	00000000a80425fb
CapAmb:	0000000000000000
````

Notice the CapInh?

**Comment by rhatdan** [comment] 2019-08-20 16:28
Could you try running the command with
--cap-add all?
If this fails try
--security-opt seccomp:unconfined

**Comment by rhatdan** [comment] 2019-08-20 16:29
Also are you executing this command with podman as root or non-root.

If non-root, please try it as root.

**Comment by gastaldi** [comment] 2019-08-20 16:35
I am running podman as non-root. It works if:
- I run with Docker (not the podman alias);
- I run as root.

**Comment by gastaldi** [comment] 2019-08-20 16:37
@rhatdan apparently I am unable to change the `docker run` statement since it's triggered inside my build which makes adding `--cap-add all` or `--security-opt seccomp:undefined` hard to add . Is it possible to set these options as default in Podman?

**Comment by rhatdan** [comment] 2019-08-20 18:01
No I think the issue is that you are running rootless.  Now we would need to figure out what is causing the issues when running rootless.

If you run rootless without --user 1000:1000, does it work?

**Comment by gastaldi** [comment] 2019-08-21 12:40
@rhatdan sorry, same error happens without `--user 1000:1000`:

```
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] podman run -v /home/ggastald/workspace/quarkus/integration-tests/jgit/target:/project:z --rm quay.io/quarkus/ubi-quarkus-native-image:19.1.1 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dio.netty.leakDetection.level=DISABLED -J-Dvertx.disableDnsResolver=true -J-Dio.netty.noUnsafe=true --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar quarkus-integration-test-jgit-999-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
Error occurred during initialization of VM
Unable to load JVMCI shared library: /opt/graalvm/jre/lib/amd64/libjvmcicompiler.so: cannot restore segment prot after reloc: Permission denied
```

**Comment by gastaldi** [comment] 2019-08-21 12:47
@rhatdan Good news, using `--cap-add=all` makes the build pass.

**Comment by rhatdan** [comment] 2019-08-21 12:55
Well I guess we would want to know what capability actually allowed you to succeed.  Two I would try would be SYS_ADMIN and NET_ADMIN, 
You could look at man capabilities to give you an idea of what CAPABILITIES are involved.

**Comment by gastaldi** [comment] 2019-08-21 13:11
Hum, spoke too soon, `--cap-add=all` only works after I disable SELinux (with run `sudo /usr/sbin/setenforce 0`), otherwise the same error appears

**Comment by rhatdan** [comment] 2019-08-21 13:35
Yes I think SELinux is blocking the first issue.
Which is why I want to catch the AVC.
ausearch -m avc -ts recent is not showing anything?

**Comment by gastaldi** [comment] 2019-08-21 13:37
Ah I see this now:
```
----
time->Wed Aug 21 10:37:11 2019
type=AVC msg=audit(1566394631.796:1496): avc:  denied  { execmod } for  pid=9107 comm=4A564D43492D6E617469766520436F path="/opt/graalvm/jre/lib/amd64/libjvmcicompiler.so" dev="fuse" ino=6426
427 scontext=system_u:system_r:container_t:s0:c8,c910 tcontext=system_u:object_r:fusefs_t:s0 tclass=file permissive=0
```

**Comment by rhatdan** [comment] 2019-08-21 13:49
Awesome that is what I needed.  I will update container selinux...

**Comment by rhatdan** [comment] 2019-08-21 13:57
Fixed in container-selinux-2.115.0-1.gitfddfbbb

**Comment by gastaldi** [comment] 2019-08-21 13:59
Amazing, now how do I use this new version? :smile:

**Comment by rhatdan** [comment] 2019-08-21 14:04
If you are running fedora 30 you can grab it here:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1361875

**Comment by gastaldi** [comment] 2019-08-21 14:15
Fantastic! Now I am getting the error described in https://github.com/containers/libpod/issues/3859#issuecomment-523087307 but at least I don't need to disable SELinux

**Comment by rhatdan** [comment] 2019-08-21 14:34
Have you tried individual Capabilties to try to identify which one you are missing?

**Comment by gastaldi** [comment] 2019-08-21 14:53
@rhatdan do I need to try each one individually or can I consider that the ones listed in the ``--cap-drop=CAP_xxx` section in  https://github.com/containers/libpod/blob/master/docs/podman-build.1.md are already set?

**Comment by gastaldi** [comment] 2019-08-21 14:54
Found it! It's `CAP_DAC_OVERRIDE`

**Comment by gastaldi** [comment] 2019-08-21 16:08
One interesting thing I noticed is that the user and group set for the artifacts produced in the mounted volume are different compared to the Docker client

# Podman 
```
-rwxr-xr-x.  1   101000   101000 50995264 Aug 21 12:34 quarkus-integration-test-jgit-999-SNAPSHOT-runner
```

# Docker
```
-rwxr-xr-x.  1   ggastald   ggastald 50995264 Aug 21 12:34 quarkus-integration-test-jgit-999-SNAPSHOT-runner
```

This is the output of my `id` command: 
```
uid=1000(ggastald) gid=1000(ggastald) groups=1000(ggastald),10(wheel),975(libvirt),977(docker) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```

**Comment by rhatdan** [comment] 2019-08-21 16:17
@giuseppe FYI.
Looks like the file got created as UID 1001 in side your user namespace Rather then as root inside?

Could you do a 

$ podman unshare cat /proc/self/uid_map

**Comment by gastaldi** [comment] 2019-08-21 16:55
This is the output of the unshare command:
```
➜  podman unshare cat /proc/self/uid_map
         0       1000          1
         1     100000      65536
```

I managed to keep the same behavior by using `--userns=keep-id`.

**Comment by gastaldi** [comment] 2019-08-21 16:59
I think this issue can be closed? https://github.com/containers/container-selinux/commit/fddfbbb7836cabeb28feffb4602f4a3ae5016cdb seems to have fixed the original problem

**Closed** 2019-08-21 17:08 UTC
Labels: kind/bug

**Comment by rhatdan** [comment] 2019-08-21 17:43
Yes that makes sense.  Or drop the --user flag altogether to get the file owned by you.  
Nice that we were able to get this to work.
