### ISSUE TITLE
 unable to find user root: no matching entries in passwd file

### ISSUE THREAD

**Issue by cjeanner** [containers/libpod#1817] opened 2018-11-15 12:58 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

[//]: # Uncomment only one, leave it on its own line:

# **kind bug**

[//]: # **kind feature**

**Description**
Sometime, we hit the following error while deploying a bunch of containers:
```
2018-11-13 18:16:19 | "2018-11-13 18:13:39,018 ERROR: 4514 -- error mounting image volumes: unable to find user root: no matching entries in passwd file",
```

**Steps to reproduce the issue:**

Appears at random.

**Describe the results you received:**
It's randomly failing

**Describe the results you expected:**
It should run as expected, using the "--user <value>"  we set with `podman exec`

**Additional information you deem important (e.g. issue happens only occasionally):**
So it's random, and happens a couple of time on our CI.

**Output of `podman version`:**

```
Version:       0.11.1
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.11.1-2.gita4adfe5.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 02be8b05693994d520f0802560f1195296aadbae-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 976379904
  MemTotal: 8365137920
  OCIRuntime:
    package: runc-1.0.0-55.dev.git2abd837.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 5581828096
  SwapTotal: 8588881920
  arch: amd64
  cpus: 8
  hostname: undercloud.localdomain
  kernel: 3.10.0-862.14.4.el7.x86_64
  os: linux
  uptime: 2h 24m 55.42s (Approximately 0.08 days)
insecure registries:
  registries:
  - 192.168.24.1:8787
  - 192.168.24.3:8787
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 88
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 35
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cjeanner** [comment] 2018-11-15 14:56
Some more info I could dig in some previous run, with debug:
```
    "Error running ['podman', '--log-level=debug', 'run', '--name', 'iscsid', '--label', 'config_id=tripleo_step3', '--label', 'container_name=iscsid', '--label', 'managed_by=paunch', '--label', 'config_data={\"start_order\": 2, \"healthcheck\": {\"test\": \"/openstack/healthcheck\"}, \"image\": \"docker.io/tripleomaster/centos-binary-iscsid:9ad93affedba8870315dd72c714770875ce24759_b72f0c42\", \"environment\": [\"KOLLA_CONFIG_STRATEGY=COPY_ALWAYS\"], \"volumes\": [\"/etc/hosts:/etc/hosts:ro\", \"/etc/localtime:/etc/localtime:ro\", \"/etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro\", \"/etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro\", \"/etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro\", \"/etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro\", \"/etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro\", \"/dev/log:/dev/log\", \"/etc/ssh/ssh_known_hosts:/etc/ssh/ssh_known_hosts:ro\", \"/etc/puppet:/etc/puppet:ro\", \"/var/lib/kolla/config_files/iscsid.json:/var/lib/kolla/config_files/config.json:ro\", \"/dev/:/dev/\", \"/run/:/run/\", \"/sys:/sys\", \"/lib/modules:/lib/modules:ro\", \"/etc/iscsi:/var/lib/kolla/config_files/src-iscsid:ro\"], \"net\": \"host\", \"privileged\": true, \"restart\": \"always\"}', '--detach=true', '--env=KOLLA_CONFIG_STRATEGY=COPY_ALWAYS', '--net=host', '--privileged=true', '--volume=/etc/hosts:/etc/hosts:ro', '--volume=/etc/localtime:/etc/localtime:ro', '--volume=/etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro', '--volume=/etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro', '--volume=/etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro', '--volume=/etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro', '--volume=/etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro', '--volume=/dev/log:/dev/log', '--volume=/etc/ssh/ssh_known_hosts:/etc/ssh/ssh_known_hosts:ro', '--volume=/etc/puppet:/etc/puppet:ro', '--volume=/var/lib/kolla/config_files/iscsid.json:/var/lib/kolla/config_files/config.json:ro', '--volume=/dev/:/dev/', '--volume=/run/:/run/', '--volume=/sys:/sys', '--volume=/lib/modules:/lib/modules:ro', '--volume=/etc/iscsi:/var/lib/kolla/config_files/src-iscsid:ro', 'docker.io/tripleomaster/centos-binary-iscsid:9ad93affedba8870315dd72c714770875ce24759_b72f0c42']. [127]", 
    "stderr: time=\"2018-09-05T15:25:51Z\" level=debug msg=\"[graphdriver] trying provided driver \"overlay\"\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"overlay: override_kernelcheck=true\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"overlay test mount with multiple lowers succeeded\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=info msg=\"Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"Set libpod namespace to \"\"\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]docker.io/tripleomaster/centos-binary-iscsid:9ad93affedba8870315dd72c714770875ce24759_b72f0c42\"\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"parsed reference into \"[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@d49a0f2d76edbc290ffcf9e459bfdca21723912ac4547011e4308aab3bce09e9\"\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"exporting opaque data as blob \"sha256:d49a0f2d76edbc290ffcf9e459bfdca21723912ac4547011e4308aab3bce09e9\"\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"Using host netmode\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"appending name iscsid\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"created container \"3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270\"\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"container \"3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270\" has work directory \"/var/lib/containers/storage/overlay-containers/3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270/userdata\"\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"container \"3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270\" has run directory \"/var/run/containers/storage/overlay-containers/3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270/userdata\"\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"New container created \"3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270\"\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"container \"3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270\" has CgroupParent \"machine.slice/libpod-3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270.scope\"\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"mounted container \"3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270\" at \"/var/lib/containers/storage/overlay/6f1263c5faa5f32a5d2d269b0463a1e45975a9ac914ed396540499c69e7ba801/merged\"\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"Created root filesystem for container 3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270 at /var/lib/containers/storage/overlay/6f1263c5faa5f32a5d2d269b0463a1e45975a9ac914ed396540499c69e7ba801/merged\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"/etc/system-fips does not exist on host, not mounting FIPS mode secret\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=warning msg=\"User mount overriding libpod mount at \"/etc/hosts\"\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=warning msg=\"failed to parse language \"en_US.UTF-8\": language: tag is not well-formed\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"reading hooks from /usr/share/containers/oci/hooks.d\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"added hook /usr/share/containers/oci/hooks.d/oci-register-machine.json\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"added hook /usr/share/containers/oci/hooks.d/oci-systemd-hook.json\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"added hook /usr/share/containers/oci/hooks.d/oci-umount.json\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"hook oci-register-machine.json did not match\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"hook oci-systemd-hook.json did not match\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"hook oci-umount.json matched; adding to stages [prestart]\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"Setting CGroups for container 3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270 to machine.slice:libpod:3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"Created OCI spec for container 3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270 at /var/lib/containers/storage/overlay-containers/3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270/userdata/config.json\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"/usr/libexec/podman/conmon messages will be logged to syslog\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"running conmon: /usr/libexec/podman/conmon\" args=[-s -c 3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270 -u 3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270 -r /usr/bin/runc -b /var/lib/containers/storage/overlay-containers/3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270/userdata -p /var/run/containers/storage/overlay-containers/3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270/userdata/pidfile -l /var/lib/containers/storage/overlay-containers/3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270/userdata/ctr.log --exit-dir /var/run/libpod/exits --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /var/lib/containers/storage --exit-command-arg --runroot --exit-command-arg /var/run/containers/storage --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /var/run/libpod --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270 --socket-dir-path /var/run/libpod/socket --log-level debug --syslog] ", 
    "time=\"2018-09-05T15:25:51Z\" level=info msg=\"Running conmon under slice machine.slice and unitName libpod-conmon-3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270.scope\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"Received container pid: -1\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"Cleaning up container 3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"Network is already cleaned up, skipping...\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=debug msg=\"unmounted container \"3878e48d01c840d35936fafecfb14170031554b7a9be721ce477209b0eaeb270\"\" ", 
    "time=\"2018-09-05T15:25:51Z\" level=error msg=\"container create failed: container_linux.go:336: starting container process caused \"setup user: no such file or directory\"", 
    ": internal libpod error\" ", 
```

**Comment by rhatdan** [comment] 2018-11-15 15:24
I take it you do have a root user in /etc/passwd?  Or are you missing /etc/passwd?

**Comment by rhatdan** [comment] 2018-11-15 15:24
@cjeanner What is the actual command you are running?

**Comment by mheon** [comment] 2018-11-15 15:31
@cjeanner Is the error message consistent? Or does it vary between runs? We call this function more than once per container, so I'm curious as to whether it's failing in different places each time, or consistently when we try and set up image volumes

**Comment by cjeanner** [comment] 2018-11-15 15:33
@rhatdan so the user does exist in the container. Else it would be consistent, on a specific set of container. But this isn't the case.

@mheon nope, not consistent. It hits "sometimes", and not always for the same container - so it's really, really hard to reproduce (I've spend my day trying really hard... no chance)

**Comment by rhatdan** [comment] 2018-11-15 16:04
So this is runc blowing up?

**Comment by mheon** [comment] 2018-11-15 16:11
It could be the runc passwd parse code? We're using it as part of libpod's lookup functions...

**Comment by mheon** [comment] 2018-11-26 16:17
Going to try and find some time to look at this in the afternoon. Can you confirm it's still occurring?

**Comment by cjeanner** [comment] 2018-11-27 05:33
Hello @mheon 
Yep, can confirm, it still appears randomly.
Thank you for your time!

**Comment by mheon** [comment] 2018-12-11 16:15
#1978 may offer a fix - it removes the offending piece of code. This could only move the race elsewhere, but it may well be enough to stop it.

**Comment by mheon** [comment] 2018-12-11 21:19
I'm going to reopen this until @cjeanner and @EmilienM can confirm the issue is fixed on their end

**Comment by mheon** [comment] 2018-12-27 16:43
Huh. This is not an error I would have expected to be related to that.

@rhatdan Should we add a warning against :z/:Z on some system mountpoints?

**Comment by EmilienM** [comment] 2018-12-27 16:46
I might have been confused with another bug. From what I can tell we
haven't seen that bug around anyway.

---
Emilien Macchi

**Comment by rhatdan** [comment] 2018-12-28 13:41
@mheon There are some warnings built into opencontainers/selinux to prevent user attempts to relabel system directories.

```
	exclude_paths := map[string]bool{"/": true, "/usr": true, "/etc": true, "/tmp": true, "/home": true, "/run": true, "/var": true, "/root": true}
	if exclude_paths[path] {
		return fmt.Errorf("SELinux relabeling of %s is not allowed", path)
	}
```

**Comment by EmilienM** [comment] 2019-01-09 15:05
Note that we still hit that but ([5 hits in 7 days](http://logstash.openstack.org/#dashboard/file/logstash.json?query=build_name%3A%20*tripleo-ci*%20AND%20build_status%3A%20FAILURE%20AND%20message%3A%20%5C%22no%20matching%20entries%20in%20passwd%20file%5C%22), not that bad).

**Comment by mheon** [comment] 2019-01-09 15:07
So it seems there is still a race somewhere, but removing one of the cases where we would hit that race has majorly reduced the probability of it happening.

**Comment by rhatdan** [comment] 2019-03-08 15:36
@cjeanner Have you seen this since the fix.  Reopen if you have.

**Closed by rhatdan** 2019-03-08 15:36 UTC

**Comment by naveedkamran** [comment] 2019-03-22 12:43
We are also having same issue. The docker image is based on 

FROM jboss/wildfly:9.0.2.Final

Did someone really found a solution?

**Comment by mheon** [comment] 2019-03-22 12:46
What Podman version?

**Comment by naveedkamran** [comment] 2019-03-22 12:57
We are not using podman. We are using only docker.
Here is the partial code of the Dockerfile

```
FROM jboss/wildfly:9.0.2.Final
# FROM jboss/wildfly:latest

ENV JBOSS_HOME /opt/jboss/wildfly
ENV JAVA_CACERTS /etc/pki/ca-trust/extracted/java/cacerts

# go root to do copy and rights stuff
USER root

# install needed packages

#RUN yum -y update; yum clean all
# RUN yum -y install openssh-clients; yum clean all
# RUN yum -y install epel-release
# RUN yum -y install ansible

# create folders and copy data into
RUN mkdir /start
RUN mkdir /certs

ADD bin/ /start
ADD customization $JBOSS_HOME/customization/
ADD modules/ $JBOSS_HOME/modules
```

It gives this error:


fatal: [my-all-test]: FAILED! => {"changed": true, "cmd": "sudo docker build -t controller:v1.0 /opt/docker/pm-controller-basic-image/", "delta": "0:00:25.920795", "end": "2019-03-22 13:22:13.867015", "msg": "non-zero return code", "rc": 1, "start": "2019-03-22 13:21:47.946220", "stderr": "linux spec user: unable to find user root: no matching entries in passwd file", "stderr_lines": ["linux spec user: unable to find user root: no matching entries in passwd file"], "stdout": "Sending build context to Docker daemon 

........... COME LINES OMITTED ...........
Step 3/43 : ENV JAVA_CACERTS /etc/pki/ca-trust/extracted/java/cacerts", " ---> Running in 986166f83b14", "Removing intermediate container 986166f83b14", " ---> 07414cc9c8eb", "Step 4/43 : USER root", " ---> Running in e681a5b2a1f2", "Removing intermediate container e681a5b2a1f2", " ---> aa9568fd810d", "Step 5/43 : RUN mkdir /start", " ---> Running in 2c439f065cda"]

**Comment by EmilienM** [comment] 2019-03-22 12:57
@najamelan if you're running on centos7, I suggest using this package:
https://trunk.rdoproject.org/centos7-master/deps/latest/x86_64/podman-1.0.0-3.git921f98f.el7.x86_64.rpm

Which contains a tested version of podman, which shouldn't have this bug anymore.

**Comment by naveedkamran** [comment] 2019-03-22 13:02
But we are running it on Ubuntu 16. Do you know if it also works on ubuntu or anyway around for ubuntu?

**Comment by zzzeek** [comment] 2019-07-20 01:34
I just saw this, if that matters, in openstack stein:
```

"2019-07-20 00:32:52,076 ERROR: 23573 -- ['/usr/bin/podman', 'run', '--user', 'root', '--name', 'container-puppet-iscsid', '--env', 'PUPPET_TAGS=file,file_lin
e,concat,augeas,cron,iscsid_config', '--env', 'NAME=iscsid', '--env', 'HOSTNAME=overcloud-novacompute-0', '--env', 'NO_ARCHIVE=', '--env', 'STEP=6', '--env', 'NET_HOS
T=true', '--log-driver', 'json-file', '--volume', '/etc/localtime:/etc/localtime:ro', '--volume', '/tmp/tmpcgjgc3jx:/etc/config.pp:ro', '--volume', '/etc/puppet/:/tmp
/puppet-etc/:ro', '--volume', '/etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro', '--volume', '/etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle
.crt:ro', '--volume', '/etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro', '--volume', '/etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro'
, '--volume', '/var/lib/config-data:/var/lib/config-data/:rw', '--volume', '/dev/log:/dev/log:rw', '--log-opt', 'path=/var/log/containers/stdouts/container-puppet-isc
sid.log', '--security-opt', 'label=disable', '--volume', '/usr/share/openstack-puppet/modules/:/usr/share/openstack-puppet/modules/:ro', '--volume', '/etc/iscsi:/etc/
iscsi:z', '--entrypoint', '/var/lib/container-puppet/container-puppet.sh', '--net', 'host', '--volume', '/etc/hosts:/etc/hosts:ro', '--volume', '/var/lib/container-pu
ppet/container-puppet.sh:/var/lib/container-puppet/container-puppet.sh:ro', 'brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/rhosp15/openstack-iscsid:20190715.1'
] run failed after unable to find user root: no matching entries in passwd file"
```
