### ISSUE TITLE
Run Rootless Error:  cannot specify gid= mount options for unmapped gid in rootless containers

### ISSUE THREAD

**Issue by asm582** [containers/libpod#3637] opened 2019-07-23 21:56 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1.podman run hello-world

**Describe the results you received:**

Trying to pull registry.access.redhat.com/hello-world...ERRO[0000] Error pulling image ref //registry.access.redhat.com/hello-world:latest: Error determining manifest MIME type for docker://registry.access.redhat.com/hello-world:latest: Error reading manifest latest in registry.access.redhat.com/hello-world: name unknown: Repo not found 
Failed
Trying to pull docker.io/library/hello-world...Getting image source signatures
Copying blob 1b930d010525 done
Copying config fce289e99e done
Writing manifest to image destination
Storing signatures
Error: container create failed: cannot specify gid= mount options for unmapped gid in rootless containers
: internal libpod error

**Describe the results you expected:**
I expect the hello-world container to be running
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```
-bash-4.2$ podman --version
podman version 1.3.2
```

**Output of `podman info --debug`:**
```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.8
  podman version: 1.3.2
host:
  BuildahVersion: 1.8.2
  Conmon:
    package: podman-1.3.2-1.git14fdcd0.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.14.0-dev, commit: 4780496c1f6949e21c807e17b57c183e9424c90a-dirty'
  Distribution:
    distribution: '"rhel"'
    version: "7.6"
  MemFree: 131399319552
  MemTotal: 134958702592
  OCIRuntime:
    package: runc-1.0.0-59.dev.git2abd837.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 17179865088
  SwapTotal: 17179865088
  arch: amd64
  cpus: 40
  hostname: bluejgpu6
  kernel: 3.10.0-957.21.3.el7.x86_64
  os: linux
  rootless: true
  uptime: 2h 10m 54.79s (Approximately 0.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /home/xxx/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/xxx/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /tmp/2287
  VolumePath: /home/xxx/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical host.

Static hostname: xxxx
         Icon name: computer-server
           Chassis: server
        Machine ID: 6af2c3ebedfc4df4bcdb9cc0d6789cdb
           Boot ID: 6da22ea95bd947ffbed868dd42e04b93
  Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.6:GA:server
            Kernel: Linux 3.10.0-957.21.3.el7.x86_64
      Architecture: x86-64

-bash-4.2$ runc --version
runc version spec: 1.0.0

**Comment by mheon** [comment] 2019-07-24 01:26
I believe this is usually caused by a too-old `runc` version. RHEL/CentOS 7.7 should have a new enough version to include a fix for this.

**Comment by giuseppe** [comment] 2019-07-24 09:32
yes, this is caused by runc, it raises this error even if there are enough IDs mapped inside the namespace.

Could you try with an updated runc?

Please re-open the issue if it still doesn't work and you believe the problem is Podman

**Closed by giuseppe** 2019-07-24 09:32 UTC

**Comment by asm582** [comment] 2019-07-24 17:26
@giuseppe can you help me on how to get newer  `runc` on RHEL 7.6, please?

**Comment by giuseppe** [comment] 2019-07-25 07:45
@asm582 I'd just build it from upstream: https://github.com/opencontainers/runc

**Comment by asm582** [comment] 2019-07-26 11:26
Thank you.

On Thu, Jul 25, 2019 at 3:45 AM Giuseppe Scrivano <notifications@github.com>
wrote:

> @asm582
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_asm582&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=EoJzDBOIwVt7lOICrHk1lQ&m=o7XcLcpyIjEvgtFEiJjqHCSxeSnJCDIuUokOJXjhVJA&s=Co5WmSlCGWp25jT7shFoqDyMW3wYDGZdF1SJhMlMknc&e=>
> I'd just build it from upstream: https://github.com/opencontainers/runc
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_opencontainers_runc&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=EoJzDBOIwVt7lOICrHk1lQ&m=o7XcLcpyIjEvgtFEiJjqHCSxeSnJCDIuUokOJXjhVJA&s=Dfq2civigmjjKVGcFoHfrb4QKFqkfiQQJsmYxjFYbJ0&e=>
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_containers_libpod_issues_3637-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DABNACPLH72LIK2ACIBKDY7TQBFK2XA5CNFSM4IGJ7RNKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2YU2WI-23issuecomment-2D514936153&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=EoJzDBOIwVt7lOICrHk1lQ&m=o7XcLcpyIjEvgtFEiJjqHCSxeSnJCDIuUokOJXjhVJA&s=421Ygd8WWqCCWAyC0133O-hb7IuUAHpNIe6L3e1dLzU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABNACPNDC3DIA633BFYNT63QBFK2XANCNFSM4IGJ7RNA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=EoJzDBOIwVt7lOICrHk1lQ&m=o7XcLcpyIjEvgtFEiJjqHCSxeSnJCDIuUokOJXjhVJA&s=6i5TPusVNe0AswsRitWg39CmTZvACy7pYC_qQLD3cWU&e=>
> .
>
-- 
Regards,

Abhishek Malvankar
