### ISSUE TITLE
podman-remote: sometimes shows container status as 'stopped'

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2962] opened 2019-04-17 17:03 UTC
A fast sequence of `podman-remote run, stop, inspect` will sometimes show container status as 'stopped' (expected: 'exited'). A subsequent inspect will show `exited` as expected. I thought 'stopped' had been deprecated? 

Reproducer:
```bash
#!/bin/sh

PODMAN=${PODMAN:-./bin/podman-remote}

while :; do
    cid=$(sudo $PODMAN run --name foo -d alpine sleep 60)
    sudo $PODMAN stop foo >/dev/null
    status=$(sudo $PODMAN inspect --format '{{.State.Status}}' foo)
    echo $status
    if [ "$status" = "exited" ]; then
        sudo $PODMAN rm foo >/dev/null
    else
        echo "*** TRIGGERED ***"
        while [ "$status" != "exited" ]; do
            status=$(sudo $PODMAN inspect --format '{{.State.Status}}' foo)
            echo "-- " $status
        done
        echo "-- ok"
        exit 1
    fi
done
```
It has never taken more than five iterations to trigger; usually it's one or two. I cannot get it to trigger using plain `podman` (not remote).

Sample output:
```
exited
exited
exited
stopped
*** TRIGGERED ***
--  exited
-- ok
```

master @ 8d93b72b5511321e394e1490c66cda378bdb1514

**Comment by mheon** [comment] 2019-04-17 18:30
`stopped` is still a potential state, however we should be transitioning out of it very quickly - on my local system, cleanup seems to happen around .25-.5 seconds after container exit, so we spend that time in the `stopped` state before transitioning to `exit`. I imagine that cleanup would take longer on a testing VM, so you could be seeing that here - a few seconds delay as cleanup runs and takes the container from stopped to exited.

We mostly deprecated filtering against `stopped` because I thought we'd basically never hit that small timing window. It might be worth adding it back if we spend multiple seconds per container transitioning.

**Comment by baude** [comment] 2019-05-29 15:33
@mheon do you want to add the stopped back in ?

**Comment by baude** [comment] 2019-08-02 16:26
whats the deal here @mheon

**Comment by mheon** [comment] 2019-08-02 16:27
This is a mismatch between `ps` filtering and display. We can fix it, but it's potentially confusing - I don't think our stopped/exited matches Docker, so the intent of filters may be lost.

I'll poke around.

**Comment by mheon** [comment] 2019-08-02 16:32
Hm. It looks like we can restore the distinction between `stopped` and `exited` without serious issue for Docker compat, though I am worried that it would regress versus Podman 1.0, where all containers were both 'stopped' and 'exited' when they stopped.

**Comment by mheon** [comment] 2019-08-06 19:36
I'm closing this because of risk of regressions vs 1.0... If people feel strongly, we can revisit

**Closed by mheon** 2019-08-06 19:36 UTC
Labels: remote
