### ISSUE TITLE
podman 'play kube' fails when editing libpod.conf

### ISSUE THREAD

**Issue by jttrail0** [containers/libpod#3533] opened 2019-07-09 14:59 UTC
When modifying the "infra_image" variable set in /usr/share/containers/libpod.conf running "podman play kube mypod.yaml" returns "Error: pod was given but no pod is specified: invalid argument"

/kind bug

**Description**

I need to modify the infra container used because the host does not have internet access.  When I return the libpod.conf back to the original value the command runs, but returns an error because "k8s.gcr.io/pause:3.1" cannot be pulled nor can it be pinged.  (Sorry for the general description I cannot copy and paste directly from the environment I am describing but I'm assuming this is known because the default pause container cannot be pulled).

The image I am replacing was pulled and loaded so the registry is localhost/kubernetes/pause:go. 

I have seen hints of some podman play kube commands being fixed in 1.4 in issues... is this issue solved as well.  It is a must to test pods in an environment that does not have open internet access and requires effort/time to pull in external containers.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.3.2
```

**Comment by mheon** [comment] 2019-07-09 15:26
Fixed upstream already - dupe of https://github.com/containers/libpod/issues/3157

**Comment by mheon** [comment] 2019-07-09 15:27
We're shipping a 1.4.x release in 7.6.6 which should resolve this.

**Comment by jttrail0** [comment] 2019-07-09 17:53
thanks!

**Comment by haircommander** [comment] 2019-07-17 16:49
closing this because it's fixed upstream. Please re-open if you disagree @jttrail0

**Closed by haircommander** 2019-07-17 16:49 UTC
Labels: kind/bug
