### ISSUE TITLE
Pulling cross platform images

### ISSUE THREAD

**Issue by jschlyter** [containers/libpod#4849] opened 2020-01-13 10:39 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

BUG REPORT

**Description**

I'm trying to pull a arm32v7 image on amd64, for later use with QEMU & `qemu-user-static`. I'm pretty sure this worked in previous releases of podman and it does work on vanilla `docker-ce` on Fedora 30.

**Steps to reproduce the issue:**

1. `podman pull arm32v7/debian:stretch` on amd64

**Describe the results you received:**

```
Trying to pull docker.io/arm32v7/debian:stretch...
  Image architecture mismatch: image uses "arm", expecting "amd64"
```

**Describe the results you expected:**

A working pull.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.5
  podman version: 1.7.0
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.2-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: 186a550ba0866ce799d74006dab97969a2107979'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 27327242240
  MemTotal: 33652678656
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 34359734272
  SwapTotal: 34359734272
  arch: amd64
  cpus: 12
  eventlogger: journald
  hostname: pwmech
  kernel: 5.3.15-300.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 58m 48.09s
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/jakob/.config/containers/storage.conf
  ContainerStore:
    number: 24
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/jakob/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 109
  RunRoot: /run/user/1000
  VolumePath: /home/jakob/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.7.0-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment] 2020-01-13 15:40
@nalind PTAL

**Comment by rhatdan** [comment] 2020-01-13 20:28
@vrothberg @mtrmac I believe this is a change in containers/image?

**Comment by mtrmac** [comment] 2020-01-13 20:38
Yes, this is https://github.com/containers/image/pull/752 behaving as intended: with this check, pulling incorrect-architecture images fails early instead of with a more confusing error (`exec user process caused "exec format error"`) on trying to execute the executables form the container.

(Are there any objections in this behavior in principle?)

Short-term, the `--override-arch` flag should allow overriding this check.

Eventually, https://github.com/containers/image/pull/786 should add some concept of supporting multiple variants versions of an architecture. Right now, that would of course still mean rejecting ARM images on non-ARM systems, but it could then be reasonable to teach Podman “ARM images can be run via Qemu” (is Podman involved in that at all?) and have that impacted in this check.

**Comment by rhatdan** [comment] 2020-01-13 20:45
`--overide-arch` is currently only available on Skopeo, should we add this to podman pull?

**Comment by mtrmac** [comment] 2020-01-13 20:47
```
cmd/podman/pull.go:     flags.StringVar(&pullCommand.OverrideArch, "override-arch", "", "use `ARCH` instead of the architecture of the machine for choosing images")
```
… OTOH it’s marked as hidden, I guess it was intended for testing only or something like that.

**Comment by rhatdan** [comment] 2020-01-13 21:04
Ok so fairly easy to turn on, if people want it.

**Comment by jschlyter** [comment] 2020-01-14 07:53
I can confirm that `podman pull --override-arch=arm arm32v7/debian:stretch` works as well as that building/running works as expected (given another `--override-arch`) argument.

I would be quite helpful if this option wasn't hidden :-)

**Comment by vrothberg** [comment] 2020-01-14 09:42
Thanks for checking! @jschlyter, are you interested in creating a PR to make the flag visible?

**Comment by abrahm** [comment] 2020-01-20 18:21
I ran into a possibly related problem. I have a container image based on i386/centos:6 that I've archived with "podman save". Podman 1.7 won't let me "podman load" the image (Image architecture mismatch: image uses "i386", expecting "amd64") and doesn't like --overide-arch. Downgrading to podman 1.6 gets everything working again.

**Comment by mtrmac** [comment] 2020-01-20 19:18
Yes, I suppose `podman load` should have the same option (it does not exist at all, unlike `podman pull`, where it exists but is not documented).

**Comment by vrothberg** [comment] 2020-01-21 12:22
> I ran into a possibly related problem. I have a container image based on i386/centos:6 that I've archived with "podman save". Podman 1.7 won't let me "podman load" the image (Image architecture mismatch: image uses "i386", expecting "amd64") and doesn't like --overide-arch. Downgrading to podman 1.6 gets everything working again.

I create a dedicated issue for this one.

**Closed** 2020-01-28 19:39 UTC
Labels: containers-images, kind/bug
