### ISSUE TITLE
GPU not recognized with oci-nvidia-hook

### ISSUE THREAD

**Issue by mjlbach** [containers/libpod#3155] opened 2019-05-18 16:50 UTC
/kind bug

**Description**

On Fedora 30, I added the centos 7 repos from [here](https://nvidia.github.io/nvidia-container-runtime/) and installed nvidia-container-runtime-hook (which installs libnvidia-container and the oci hook).

oci-nvidia-hook.json is present in /etc/containers/oci/hooks.d, /usr/share/containers/oci/hooks.d, and /usr/libexec/oci/hooks.d along with the oci-nvidia-hook shell script in the last folder only.

When I try to pull any of the nvidia docker containers, my GPU is not visible to the container.

**Steps to reproduce the issue:**

1. Install nvidia drivers (418), Cuda (10.0), and  nvidia-container-runtime-hook on Fedora 30

2. podman run --rm nvidia/cuda:9.0-base nvidia-smi

3. No GPU is found, hook is not loaded (see output of podman with debug log level [here](https://pastebin.com/PkBCXVCx)

**Describe the results you received:**

GPU not visible to the container.

**Describe the results you expected:**

GPU visible to the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12
  podman version: 1.2.0
host:
  BuildahVersion: 1.7.2
  Conmon:
    package: podman-1.2.0-2.git3bd528e.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: a13eadcaf0f07ba590c96d845a03ac3a0da7c56d'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 11987419136
  MemTotal: 16619220992
  OCIRuntime:
    package: runc-1.0.0-92.dev.gitc1b8c57.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc7+dev
      commit: d38f8a2d00ff444e52d16ab1ea5bbe5c1cb471e8
      spec: 1.0.1-dev
  SwapFree: 8380215296
  SwapTotal: 8380215296
  arch: amd64
  cpus: 8
  hostname: mjlbach-desktop.stanford.edu
  kernel: 5.0.16-300.fc30.x86_64
  os: linux
  rootless: true
  uptime: 20h 50m 4.45s (Approximately 0.83 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/michael/.config/containers/storage.conf
  ContainerStore:
    number: 7
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/michael/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 11
  RunRoot: /tmp/1000
  VolumePath: /home/michael/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment] 2019-05-19 05:43
From debugging this earlier, it sounded like the hook in question had its activation criteria set to "Always", but it doesn't appear to be registered by the hooks code.

@wking Mind taking a look at this one?

**Comment by wking** [comment] 2019-05-19 14:13
Can you attach the full hook JSON?

**Comment by wking** [comment] 2019-05-19 14:14
And probably also the Podman config, in case it set custom hook paths.

**Comment by mjlbach** [comment] 2019-05-19 17:54
The full hook is: 
```
  {
      "version": "1.0.0",
      "hook": {
          "path": "/usr/bin/nvidia-container-runtime-hook",
          "args": ["nvidia-container-runtime-hook", "prestart"],
          "env": [
              "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin              "
          ]
      },
      "when": {
          "always": true,
          "commands": [".*"]
      },
      "stages": ["prestart"]
  }
```

And my lipbod.conf

```
  volume_path = "/home/michael/.local/share/containers/storage/volumes"
  image_default_transport = "docker://"
  runtime = "runc"
  conmon_path = ["/usr/libexec/podman/conmon", "/usr/libexec/crio/conmon", "/usr/local/lib/podman/conmon", "/usr/local/libexec/crio/conmon", "/usr/bin/conmon", "/usr/sbin/conmon", "/  usr/lib/podman/bin/conmon", "/usr/lib/crio/bin/conmon"]
  conmon_env_vars = ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"]
  cgroup_manager = "cgroupfs"
  init_path = "/usr/libexec/podman/catatonit"
  static_dir = "/home/michael/.local/share/containers/storage/libpod"
  tmp_dir = "/run/user/1000/libpod/tmp"
  max_log_size = -1
  no_pivot_root = false
  cni_config_dir = "/etc/cni/net.d/"
  cni_plugin_dir = ["/usr/libexec/cni", "/usr/lib/cni", "/usr/local/lib/cni", "/opt/cni/bin"]
  infra_image = "k8s.gcr.io/pause:3.1"
  infra_command = "/pause"
  enable_port_reservation = true
  label = true
  network_cmd_path = ""
  num_locks = 2048
  EventsLogFilePath = ""

  [runtimes]
    runc = ["/usr/bin/runc", "/usr/sbin/runc", "/usr/local/bin/runc", "/usr/local/sbin/runc", "/sbin/runc", "/bin/runc", "/usr/lib/cri-o-runc/sbin/runc"]
```

**Comment by baude** [comment] 2019-05-29 16:12
@wking mind poking at this ?

**Comment by mjlbach** [comment] 2019-05-30 00:15
It appears to be working when running podman as root with the --privileged flag

**Comment by wking** [comment] 2019-05-30 02:13
> It appears to be working when running podman as root with the --privileged flag.

So the issue is logging hook-execution to make it easier to see that lack-of-privilege is the problem?

**Comment by wking** [comment] 2019-05-30 03:20
Poking, no `hooks_dir` in the `libpod.conf`, which means we get [the defaults][1] (also, shame on your packager for relying on those defaults :wink:.  As the linked docs say, they're deprecated).  That means we're matching the highest-precedence `/etc/containers/oci/hooks.d` hook.  Dropping a dummy in for testing with Podman 0.12 and poking around I turned up #3233.


[1]: https://github.com/containers/libpod/blame/v1.2.0/docs/podman.1.md#L46

**Comment by eriksjolund** [comment] 2019-06-16 11:08
Quote from:
https://github.com/containers/libpod/blob/master/docs/podman.1.md

---

If `--hooks-dir` is unset for root callers, Podman and libpod will currently default to `/usr/share/containers/oci/hooks.d` and `/etc/containers/oci/hooks.d` in order of increasing precedence.  Using these defaults is deprecated, and callers should migrate to explicitly setting `--hooks-dir`.

---

As I interpret the documentation, it looks that your command 

`podman run --rm nvidia/cuda:9.0-base nvidia-smi`

will not run any hooks if it is run by a non-root user (i.e. run rootless).

And there is no `hooks_dir` in your `libpod.conf` that could change that.

I guess you need to either explicitly specify  `--hooks-dir=` as an option to the `podman run` command
or add `hooks_dir` to your `libpod.conf`.

**Comment by baude** [comment] 2019-08-02 17:24
where do we stand here

**Comment by mheon** [comment] 2019-08-02 17:42
We are adding `hooks_dir = ["/usr/share/containers/oci/hooks.d", "/etc/containers/oci/hooks.d"]
` to rootless libpod.conf automatically as of now - though that may be dependent on the contents of root's libpod.conf, which we use for defaulting rootless.

**Comment by rhatdan** [comment] 2019-08-04 10:32
Ok I am going to assume this is fixed in podman1.5, @mjlbach reopen if I am mistaken.

**Closed by rhatdan** 2019-08-04 10:32 UTC
Labels: kind/bug

**Comment by mheon** [comment] 2019-08-04 14:03
I don't believe it is, but at the same time my impression is that the hook
in question requires root privileges?

**Comment by rhatdan** [comment] 2019-08-05 12:25
Well a hook that requires root privs will not work with rootless mode.  One thing we might need to deal with in the future would be a way to disable some hooks when running in rootless mode.

**Comment by wking** [comment] 2019-08-05 13:53
> One thing we might need to deal with in the future would be a way to disable some hooks when running in rootless mode.

Configure a hook directory without those hooks in it?  Or add a higher-priority dir to the existing stack with masking, no-op hooks covering the root-only ones?

**Comment by rhatdan** [comment] 2019-08-05 19:50
I am wondering if there is a way to do this in the homedir right now.  Basically allowing a rootless user to configure hooks that he wants to run, and eliminate hooks from the system that are not allowed to run in rootless mode.

**Comment by zeroepoch** [comment] 2020-01-11 06:47
I know this issue has already been closed, but the following tip might help anyone looking at this issue since it's pretty much the only documentation on the web for how to get `nvidia-container-runtime` working on Fedora 30+.

If you create `~/.config/containers/libpod.conf` with the contents below then you can run a GPU container as a normal user without having to add `--hooks-dir` each time you run `podman`.

```
hooks_dir = ["/usr/share/containers/oci/hooks.d", "/etc/containers/oci/hooks.d"]
```

Since it appears to extends the system `libpod.conf` this would be safer than modifying system files which may be replaced on package upgrades.  After making this change then the instructions provided in comment https://github.com/containers/libpod/issues/3155#issuecomment-497153536 by @mjlbach will work even without sudo in front.  It still requires `--privileged`, which wasn't true with docker (which instead required `--gpus=all`), but it's not too bad and best of all you can run a container without root access or adding yourself to a special group.
