### ISSUE TITLE
Not possible to pull image using IPv6 IP address

### ISSUE THREAD

**Issue by hjensas** [containers/libpod#3516] opened 2019-07-08 15:34 UTC
# Not possible to pull image using IPv6 IP address #

/kind bug

**Description**

It is not possible to pull images from an IPv6 server by it's IP address.

**Steps to reproduce the issue:**

1. podman pull [fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api:current-tripleo
or 
2. podman pull fd12:3456:789a:1::1:8787/tripleomaster/centos-binary-ironic-api:current-tripleo

**Describe the results you received:**

> Error: error pulling image "[fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api:current-tripleo": unable to pull [fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api:current-tripleo: error getting default registries to try: invalid reference format

or

> Error: error pulling image "fd12:3456:789a:1::1:8787/tripleomaster/centos-binary-ironic-api:current-tripleo": unable to pull fd12:3456:789a:1::1:8787/tripleomaster/centos-binary-ironic-api:current-tripleo: error getting default registries to try: invalid reference format

**Describe the results you expected:**

Expect podman to connect to the registry an pull the image.

**UPDATE**
 Of the above examples we probably can only make the one with brackets around the IPv6 address work. i.e `podman pull [fd12:3456:789a:1::1]:8787/namespace/image:tag` should work.

**Output of `podman version`:**

```
Version:            1.4.5-dev
RemoteAPI Version:  1
Go Version:         go1.10.2
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.2
  podman version: 1.4.5-dev
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-1.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.2.0, commit: da19d4db03f799783380e6a056cfc6b2bf7f0e18'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 484212736
  MemTotal: 12428623872
  OCIRuntime:
    package: runc-1.0.0-60.dev.git2abd837.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 6
  hostname: undercloud.rdocloud
  kernel: 3.10.0-957.21.3.el7.x86_64
  os: linux
  rootless: false
  uptime: 98h 3m 48.54s (Approximately 4.08 days)
registries:
  blocked: null
  insecure:
  - fd12:3456:789a:1::1
  - fd12:3456:789a:1::3
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 91
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 37
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Comment by hjensas** [comment] 2019-07-15 13:16
There seem to be a layer of issues handling IPv6 addresses.
1. ReferenceRegexp in [1] returns an empty array.
2. When I try to statically override the regular expression parsing with the below code it looks like the host/port part is stripped from the request URL:

```
189 func Parse(s string) (Reference, error) {
190         // matches := ReferenceRegexp.FindStringSubmatch(s)
191         matches := []string{}
192         matches = append(matches, "[fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api")
193         matches = append(matches, "[fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api")
194         matches = append(matches, "current-tripleo")
195         matches = append(matches, "")
```

```
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /var/lib/containers/storage 
DEBU[0000] Using run root /var/run/containers/storage   
DEBU[0000] Using static dir /var/lib/containers/storage/libpod 
DEBU[0000] Using tmp dir /var/run/libpod                
DEBU[0000] Using volume path /var/lib/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] cached value indicated that metacopy is not being used 
DEBU[0000] cached value indicated that native-diff is usable 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend file              
INFO[0000] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage][fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api:current-tripleo" 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage][fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api:current-tripleo" 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage][fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api:current-tripleo" 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage][fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api:current-tripleo" 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage][fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api:current-tripleo"
Trying to pull [fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api:current-tripleo...DEBU[0000] reference rewritten from '[fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api:current-tripleo' to '[fd12:3456:789a:1::1]:8787/tripleomaster/centos-bi
nary-ironic-api:current-tripleo' 
DEBU[0000] Trying to pull "[fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api:current-tripleo" 
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for [fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api:current-tripleo 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d 
DEBU[0000] GET https:///v2/                             
DEBU[0000] Ping https:///v2/ err Get https:///v2/: http: no Host in request URL (&url.Error{Op:"Get", URL:"https:///v2/", Err:(*errors.errorString)(0xc0001ea7e0)}) 
DEBU[0000] GET http:///v2/                              
DEBU[0000] Ping http:///v2/ err Get http:///v2/: http: no Host in request URL (&url.Error{Op:"Get", URL:"http:///v2/", Err:(*errors.errorString)(0xc0001ea8e0)}) 
DEBU[0000] GET https:///v1/_ping                        
DEBU[0000] Ping https:///v1/_ping err Get https:///v1/_ping: http: no Host in request URL (&url.Error{Op:"Get", URL:"https:///v1/_ping", Err:(*errors.errorString)(0xc0001ea9e0)}) 
DEBU[0000] GET http:///v1/_ping                         
DEBU[0000] Ping http:///v1/_ping err Get http:///v1/_ping: http: no Host in request URL (&url.Error{Op:"Get", URL:"http:///v1/_ping", Err:(*errors.errorString)(0xc0001eaae0)}) 
ERRO[0000] Error pulling image ref //[fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api:current-tripleo: Error initializing source docker://[fd12:3456:789a:1::1]:8787/tripleomaster/centos-binary-ironic-api:current-tripleo: pinging docker registry returned: G
et http:///v2/: http: no Host in request URL 
Failed
```

[1] https://github.com/containers/image/blob/master/docker/reference/regexp.go#L68-L70

**Comment by mheon** [comment] 2019-07-15 13:17
Hm. Seems like c/image - could you file an issue against them as well? https://github.com/containers/image

**Comment by vrothberg** [comment] 2019-07-15 13:23
Hi @hjensas, thanks for opening the issue.  The problem is that it's an invalid docker reference and can't be supported without changing pretty much every Docker-reference parser in the wild. Docker doesn't support it either.

A workaround is adding an entry for ` fd12:3456:789a:1::1:` to `/etc/hosts` and use the DNS entry for referencing images on the registry.

**Comment by vrothberg** [comment] 2019-07-15 13:24
I am closing the issue (as we can't fix it) but we can keep the discussion going.

**Closed by vrothberg** 2019-07-15 13:24 UTC
Labels: containers-images, kind/bug

**Comment by hjensas** [comment] 2019-07-16 08:10
@mheon agreed, there is an issue in container/image. This issue with a proposed fix seems to be related: https://github.com/docker/distribution/pull/2899, however the fix does'nt seem to work.

@vrothberg, It's absurd that software built after 2010 does'nt support ipv6 ...

Afaict the reference spec is something like these:
* Without host: `[PATH/]IMAGE_NAME[:TAG]`
* With host: `ADDRESS[:PORT][/PATH]/IMAGE_NAME[:TAG]`.

**Is the docker reference format is un-parsable?**
If [PATH/] can have multiple levels there is no way to determine the difference between `path0/path1/image:tag` and `host-shortname/path/image:tag`?

If this is the case it's about time the container community start introducing a way to reference images. May a suggest using a well established standard such as the Uniform Resource Identifier[[1]](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax) (URI) schema.

[1] https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax

**Comment by vrothberg** [comment] 2019-07-16 08:36
> @vrothberg, It's absurd that software built after 2010 does'nt support ipv6 ...

I understand the frustration but note that "not supporting ipv6" isn't entirely accurate. The Docker-reference format just doesn't allow to encode ipv6 addresses. Using DNS still allows for communication with the registry.

> **Is the docker reference format is un-parsable?**
> If [PATH/] can have multiple levels there is no way to determine the difference between `path0/path1/image:tag` and `host-shortname/path/image:tag`?

There are countless corner cases, the heavy use of unqualified images (e.g., `alpine:latest` vs `docker.io/library/alpine:latest`), special treatment of `localhost` but only by _some_ tools, implicitly adding `:latest` if no tag is specified, etc.

Pretty much all parsers rely on `docker/distribution` and that's where it must be addressed. The `containers/image` library can't diverge as the risk of introducing regressions is high.
