### ISSUE TITLE
podman rootless example fails

### ISSUE THREAD

**Issue by hadess** [containers/libpod#2231] opened 2019-01-29 17:16 UTC
Trying to run the example code from the Fedora magazine article fails:
https://fedoramagazine.org/running-containers-with-podman/

```sh
$ sudo dnf install podman
<snip>
Installed:
  podman-1:1.0.0-1.git82e8011.fc29.x86_64             criu-3.11-1.fc29.x86_64                                   fuse-overlayfs-0.3-1.dev.git6d269aa.fc29.x86_64   slirp4netns-0.1-2.dev.git0037042.fc29.x86_64     
  container-selinux-2:2.80-1.git1b655d9.fc29.noarch   containers-common-1:0.1.34-1.dev.gite96a9b0.fc29.x86_64   runc-2:1.0.0-67.dev.git12f6a99.fc29.x86_64        containernetworking-plugins-0.7.3-2.fc29.x86_64  
  fuse3-libs-3.2.3-14.fc29.x86_64                     libnet-1.1.6-16.fc29.x86_64                              

Complete!
$ podman --log-level debug run --rm -it fedora:29 echo "Hello world!"
INFO[0000] running as rootless                          
DEBU[0000] Initializing boltdb state at /home/hadess/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/hadess/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000                
DEBU[0000] Using static dir /home/hadess/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] Not configuring container store              
ERRO[0000] error creating libpod runtime: exit status 1 
```

**Comment by rhatdan** [comment] 2019-01-29 17:50
Can you try it as root?

**Comment by hadess** [comment] 2019-01-29 18:02
> Can you try it as root?

That seems to do something (like downloading images, and printing "Hello world")

**Comment by rhatdan** [comment] 2019-01-29 18:51
Did you install fuse-overlayfs?

cat ~/.config/containers/storage.conf

**Comment by rhatdan** [comment] 2019-01-29 18:52
@giuseppe Sould we add a recommends for fuse-overlayfs?  @lsm5 ?

**Comment by hadess** [comment] 2019-01-29 19:00
> Did you install fuse-overlayfs?

No. I literally just installed podman.

> cat ~/.config/containers/storage.conf

I guess it was created on the first run of podman, before I set the debug level:
```sh
$ cat ~/.config/containers/storage.conf
[storage]
  driver = "overlay"
  runroot = "/run/user/1000"
  graphroot = "/home/hadess/.local/share/containers/storage"
  [storage.options]
    mount_program = "/usr/bin/fuse-overlayfs"
```

I didn't touch that file.

**Comment by hadess** [comment] 2019-01-29 19:01
> > Did you install fuse-overlayfs?
> 
> No. I literally just installed podman.

Yes, it is installed, it's listed in the original comment.

```
fuse-overlayfs-0.3-1.dev.git6d269aa.fc29.x86_64
```

**Comment by rhatdan** [comment] 2019-01-29 19:08
Could you see if there is anything in the journal from conmon?

**Comment by mheon** [comment] 2019-01-29 19:26
That's not common - not even getting there. Probably a username issue. What
kernel are we dealing with here

**Comment by giuseppe** [comment] 2019-01-29 19:35
> @giuseppe Sould we add a recommends for fuse-overlayfs? @lsm5 ?

from the logg file, it seems fuse-overlayfs was installed.

How does your `/etc/subuid` file look like?

**Comment by hadess** [comment] 2019-01-29 19:47
> How does your `/etc/subuid` file look like?

```sh
$ cat  /etc/subuid
akmods:100000:65536
rupert:165536:65536
tss:231072:65536
# empty default subuid/subgid file
deluge:296608:65536
```

My user isn't in there, should it be? I never touched this file myself...

**Comment by giuseppe** [comment] 2019-01-29 19:50
yes please, you must add your user and a range of additional IDs (you can use `usermod --add-subuids` and `usermod --add-subgids`).

We added a check recently to fail in a nicer way, I will double check it.

**Comment by hadess** [comment] 2019-01-29 20:56
> yes please, you must add your user and a range of additional IDs (you can use `usermod --add-subuids` and `usermod --add-subgids`).

I have no idea what "sub" UIDs and GIDs I'm supposed to use. Which piece of the OS is supposed to create that file with some decent values? It seems to be owned by `setup`.

> We added a check recently to fail in a nicer way, I will double check it.

Let me know if you have something you want me to test.

**Comment by giuseppe** [comment] 2019-01-30 08:22
@hadess `adduser` should take care of it for newly created users.

Given the configuration you've showed earlier, you could add:

```
$YOUR_USERNAME:362144:65536
```

to both `/etc/subuid` and `/etc/subgid`

**Comment by giuseppe** [comment] 2019-01-30 13:45
@hadess it is already there, I wonder why it wasn't printed.  I've done some tests locally and it works, if I remove my user from `/etc/subuid` I get:
```
ERRO[0000] No subuid ranges found for user "gscrivano" in /etc/subuid 
```

**Comment by hadess** [comment] 2019-01-30 14:43
> @hadess it is already there

Not in the distribution package I'm using, otherwise I wouldn't have filed a bug. I'm guessing it might be @rhatdan's job to do that, right?

**Comment by giuseppe** [comment] 2019-01-30 14:56
podman 1.0 should have that fixed, this is why I am wondering what is going on :)

@rhatdan I've tried both combinations, but I still get it to fail with a nicer error message here

**Comment by lsm5** [comment] 2019-01-30 15:01
> @giuseppe Sould we add a recommends for fuse-overlayfs? @lsm5 ?

Already there on fedora > 28

**Comment by hadess** [comment] 2019-01-30 16:51
> @rhatdan I've tried both combinations, but I still get it to fail with a nicer error message here

And undoing the changes I made to those 2 files earlier, I can now get it to fail with the same "nice" error message... So there was probably something else missing.

I undid the `/etc/subuid` and `/etc/subgid` changes, nuked `~/.local/share/containers/` and `/var/lib/containers` and can't get it to fail as it originally did.

I then nuked `/run/user/1000/libpod/` and got it to fail again:
```
$ podman --log-level debug run --rm -it fedora:29 echo "Hello world!"
INFO[0000] running as rootless                          
DEBU[0000] Initializing boltdb state at /home/hadess/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/hadess/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000                
DEBU[0000] Using static dir /home/hadess/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] Not configuring container store              
DEBU[0000] Using slirp4netns netmode                    
ERRO[0000] No subuid ranges found for user "hadess" in /etc/subuid 
$ rm -rf /run/user/1000/libpod/
$ podman --log-level debug run --rm -it fedora:29 echo "Hello world!"
INFO[0000] running as rootless                          
DEBU[0000] Initializing boltdb state at /home/hadess/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/hadess/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000                
DEBU[0000] Using static dir /home/hadess/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] Not configuring container store              
ERRO[0000] error creating libpod runtime: exit status 1 
$ ls -l /run/user/1000/libpod/tmp
total 0
-rw-------. 1 hadess hadess  0 Jan 30 17:49 alive.lck
drwxr-x---. 2 hadess hadess 40 Jan 30 17:49 exits
drwxr-xr-x. 2 hadess hadess 40 Jan 30 17:49 lock
drwxr-x---. 2 hadess hadess 40 Jan 30 17:49 socket
```

**Comment by miabbott** [comment] 2019-01-30 16:58
I encountered the same issue described here and had to nuke `~/.config/containers/storage.conf` because the format looked incorrect:

```
$ cat ~/.config/containers/storage.conf 
RunRoot = "/run/user/1000"
GraphRoot = "/var/home/miabbott/.local/share/containers/storage"
GraphDriverName = "overlay"
GraphDriverOptions = ["overlay.mount_program=/usr/bin/fuse-overlayfs"]
```

This got me a little further, but then I started hitting SELinux denials as described in #2245

**Comment by hadess** [comment] 2019-01-30 17:14
The config file isn't the problem for me, as I can make it run properly if I modify the subuid/subgid files. SELinux is set as permissive on my system.

**Comment by rhatdan** [comment] 2019-01-30 21:44
It looks to me like silverblue does not have the current SELinux policy installed correctly.  Does it work in enforcing mode if you run semodule -B

**Comment by hadess** [comment] 2019-01-30 23:57
> It looks to me like silverblue does not have the current SELinux policy installed correctly.

I don't use Silverblue, so that's not the problem in my case.

**Comment by paller** [comment] 2019-02-18 18:02
I'm having the same issue as initial reported and found this in the journal.

`kernel: overlayfs: unrecognized mount option "nodev" or missing value`

**Comment by mheon** [comment] 2019-02-18 18:04
@paller What distribution, and how do you trigger it? Any command?
Also, can you pastebin your `~/.config/containers/storage.conf`

**Comment by paller** [comment] 2019-02-18 18:30
Adding subuid and subgid as mentioned above solved the problem.

Could my "nodev" error be caused by a missing storage.conf file? I did delete it in an attempt to solve my problem.

Anyway,

Fedora: 29
Kernel: 4.20.8-200.fc29.x86_64
storage.conf: https://pastebin.com/EGBdyWnA

**Comment by mheon** [comment] 2019-02-18 18:31
An incorrectly-formatted storage.conf might have caused it. Missing ought to be fine - we recreate from sane defaults in that case

**Comment by giuseppe** [comment] 2019-02-18 19:57
I think the issue can be caused by fuse-overlayfs that fails on "nodev", I've added a patch to address it:

https://github.com/containers/fuse-overlayfs/pull/45/commits/130e0000e5c1a474a1fbb9f8d2cd8507e22c5296

**Comment by paller** [comment] 2019-02-18 20:51
> Could you see if there is anything in the journal from conmon?

Just found out that conmon isn't installed as a dependency for podman on Fedora 29. That's probably why there's nothing logged.

**Comment by mheon** [comment] 2019-02-18 20:53
We package our own version in the Podman package (the `conmon` package is usually very old, since it has to sync with CRI-O , which releases at a much slower pace). If `conmon` wasn't installed, we'd throw very angry error messages on Podman startup to that effect - we can't do any container operations without it

**Comment by paller** [comment] 2019-02-18 21:04
In that case I will remove the stand-alone conmon package again.

I have deleted the subuid/subgid and I'm back at
`error creating libpod runtime: exit status 1`

If there's any testing I can do let me know.

**Comment by mheon** [comment] 2019-02-18 21:26
The two files do need to be there - if /etc/subuid and /etc/subgid are missing we can't use rootless.

**Comment by mheon** [comment] 2019-02-18 21:26
(Though they really ought to be created by your distro when the newuidmap and newgidmap executables are installed)

**Comment by paller** [comment] 2019-02-19 17:52
> (Though they really ought to be created by your distro when the newuidmap and newgidmap executables are installed)

I have a similar Fedora 29 setup that doesn't have any problems. The subuid and subgid are preset and I didn't put them there manually. I'm guessing, but it could be something about the upgrade path. The problematic PC has been updated since Fedora 25 or 24, while the other only went from 28 to 29.

**Comment by hadess** [comment] 2019-02-19 17:58
> I have a similar Fedora 29 setup that doesn't have any problems. The subuid and subgid are preset and I didn't put them there manually. I'm guessing, but it could be something about the upgrade path. The problematic PC has been updated since Fedora 25 or 24, while the other only went from 28 to 29.

I think the problem is understood, including how to fix it, this issue is now about podman (or something in the layers underneath) not throwing a helpful error message when it encounters that problem.

**Comment by mheon** [comment] 2019-02-19 19:09
@giuseppe Can we extract anything from the process in the userns here? Leak a pipe in for error messages, like we do with `conmon`?

**Comment by rhatdan** [comment] 2019-02-20 12:15
This Issue seems to have drifted all over.  What is the current issue people are seeing?
Can we close this issue, and open a new one with a clear description of what is the problem.

**Comment by hadess** [comment] 2019-02-20 12:30
> This Issue seems to have drifted all over. What is the current issue people are seeing?
> Can we close this issue, and open a new one with a clear description of what is the problem.

The problem is still the same. On some (usually upgraded) systems, the `/etc/sub{u,g}id` files don't include the current user. This is easily fixable if the user knows what the problem is, but the error reporting is lacking. The discussion is now about how the error should be extracted from inside the namespaced process back up to the caller, so it can be printed for the user to act upon.

**Comment by rhatdan** [comment] 2019-02-20 16:55
I am seeing in podman this error.

podman images
ERRO[0000] No subuid ranges found for user "dwalsh" in /etc/subuid 

If dwalsh is not in the /etc/subuid file?  Do you see something different?

**Comment by hadess** [comment] 2019-02-20 17:51
> podman images
> ERRO[0000] No subuid ranges found for user "dwalsh" in /etc/subuid
> 
> If dwalsh is not in the /etc/subuid file? Do you see something different?

Same thing with this command, but that's not the command I typed.

```sh
$ podman images
ERRO[0000] No subuid ranges found for user "hadess" in /etc/subuid 
$ podman --log-level debug run --rm -it fedora:29 echo "Hello world!"
INFO[0000] running as rootless                          
DEBU[0000] Initializing boltdb state at /home/hadess/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/hadess/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000                
DEBU[0000] Using static dir /home/hadess/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] Not configuring container store              
ERRO[0000] error creating libpod runtime: exit status 1 
```

Both should have the same error message (the useful one ;)

**Comment by giuseppe** [comment] 2019-02-21 09:00
I get the same error message when using `podman run`

**Comment by rhatdan** [comment] 2019-02-21 14:43
```
podman --log-level debug run --rm -it fedora:29 echo "Hello world!"
INFO[0000] running as rootless                          
DEBU[0000] Initializing boltdb state at /home/dwalsh/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/dwalsh/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/3267                
DEBU[0000] Using static dir /home/dwalsh/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/3267/libpod/tmp      
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] Not configuring container store              
DEBU[0000] Using slirp4netns netmode                    
ERRO[0000] No subuid ranges found for user "dwalsh" in /etc/subuid 
```

**Comment by mheon** [comment] 2019-02-21 14:52
What versions are we looking at here? Is this fixed in upstream, but present in 1.0, or are we looking at an environment issue causing @hadess to get different output?

**Comment by hadess** [comment] 2019-02-21 15:25
> What versions are we looking at here?

`podman-1.0.0-1.git82e8011.fc29.x86_64`

That's in the first comment.

> Is this fixed in upstream, but present in 1.0, or are we looking at an environment issue causing @hadess to get different output?

I already explained how I reproduced the exact error in https://github.com/containers/libpod/issues/2231#issuecomment-459019496

**Comment by rhatdan** [comment] 2019-02-21 15:32
```
# mv /run/user/3267/libpod  /run/user/3267/libpod.old
# exit
$ podman run fedora echo hello
error creating libpod runtime: exit status 1
```
Ok I get this now.

**Comment by mheon** [comment] 2019-02-21 15:35
Oh! This has to be the refresh code - that reexecs a fresh `podman info`, and we're probably not sharing STDOUT/STDERR with it.

**Comment by rhatdan** [comment] 2019-02-21 16:01
Yes I am working on a patch for this now.  Just need to add the output command from podman info.

**Comment by rhatdan** [comment] 2019-03-08 16:37
I believe this is fixed in master. Please reopen if I am mistaken.

**Closed by rhatdan** 2019-03-08 16:37 UTC
