### ISSUE TITLE
podman push fails with error unmounting invalid argument

### ISSUE THREAD

**Issue by tmds** [containers/libpod#4545] opened 2019-11-21 14:02 UTC
/kind bug

**Description**

podman push fails with 
* "error unmounting /var/lib/containers/storage/overlay/5b8acfe925e03f8a94a5e5350a5fd82312a2874a2031cc14f963b857096009c1/merged: invalid argument"
* ...
* Error: Error copying image to the remote destination: Error reading blob sha256:49f80dff343c4e335edd514183872788671fe3d00492380c190a09c9c1b46c72: error creating overlay mount to /var/lib/containers/storage/overlay/3ab8392de799e2ac9cb455baf11b7f2d0f32d63b54dee5e725eca0136cef299b/merged: device or resource busy

**Describe the results you received:**

```
+ sudo podman push quay.io/fedora-dotnet/dotnet:3.1
Getting image source signatures
Copying blob sha256:d5c4792b7b09ad540a878569fc25faf9f43b19b8b2935f6cee4a3aba4ec76fc6
time="2019-11-20T19:06:23Z" level=error msg="error unmounting /var/lib/containers/storage/overlay/cb321239cf202dadb69564ceafe82a9813a2dad3cc5fbc1b78dd1a255e8718bb/merged: invalid argument"
Copying blob sha256:cf768f432945daf5207b1c42964875efc7350cad6bc67180128cc9cc80ed6948
Copying blob sha256:2ae3cee18c8ef9e0d448649747dab81c4f1ca2714a8c4550eff49574cab262c9
time="2019-11-20T19:06:23Z" level=error msg="error unmounting /var/lib/containers/storage/overlay/3ab8392de799e2ac9cb455baf11b7f2d0f32d63b54dee5e725eca0136cef299b/merged: invalid argument"
time="2019-11-20T19:06:23Z" level=error msg="error unmounting /var/lib/containers/storage/overlay/0c2b7a8835318870d74c0d0de3223112c256dc9dbfe4df8f5a7731f6fff0a103/merged: invalid argument"
time="2019-11-20T19:06:23Z" level=error msg="error unmounting /var/lib/containers/storage/overlay/5b8acfe925e03f8a94a5e5350a5fd82312a2874a2031cc14f963b857096009c1/merged: invalid argument"
time="2019-11-20T19:06:23Z" level=error msg="error unmounting /var/lib/containers/storage/overlay/c44255f3bf3ab0967b184c9d8808c5e4b4f020ebfd83ed1519e09f05a1393865/merged: invalid argument"
time="2019-11-20T19:06:23Z" level=error msg="error unmounting /var/lib/containers/storage/overlay/12bcba531f544a013fbf17c9aaa7b69fd284020a7ea2dabcde2a1cdbb876ea58/merged: invalid argument"
time="2019-11-20T19:06:23Z" level=error msg="error unmounting /var/lib/containers/storage/overlay/cdedbabb2fc4f8d0cad5bff0c1fe993ac699845c81df2176e333ed716f967ac5/merged: invalid argument"
time="2019-11-20T19:06:23Z" level=error msg="error unmounting /var/lib/containers/storage/overlay/97e1ac207e49e809759bb28c19d7dd709b6fd2f54b82df65d9e5cc2aa9fb4f8c/merged: invalid argument"
time="2019-11-20T19:06:23Z" level=error msg="error unmounting /var/lib/containers/storage/overlay/51d41a6437db18db1fc2fec7b0225c3a44a9e2afdc7fda4cf659c796efc736a0/merged: invalid argument"
time="2019-11-20T19:06:23Z" level=error msg="error unmounting /var/lib/containers/storage/overlay/e1d0f2e91c4cdf590a1041b83fe20a5e48aeaea76e7910fe08198064bdbbe917/merged: invalid argument"
Error: Error copying image to the remote destination: Error reading blob sha256:49f80dff343c4e335edd514183872788671fe3d00492380c190a09c9c1b46c72: error creating overlay mount to /var/lib/containers/storage/overlay/3ab8392de799e2ac9cb455baf11b7f2d0f32d63b54dee5e725eca0136cef299b/merged: device or resource busy
```

**Describe the results you expected:**

**Environment**:

Fedora 30 in VM.

`Linux localhost.localdomain 5.2.9-200.fc30.x86_64 #1 SMP Fri Aug 16 21:37:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

`podman 2:1.6.2-2.fc30`

**Comment by rhatdan** [comment] 2019-11-21 14:21
Do the other Podman commands work for you?  IE can you run a container?

**Comment by tmds** [comment] 2019-11-21 15:18
> Do the other Podman commands work for you? IE can you run a container?

Yes. The image is first built.
Then a test suite is ran successfully which involves running containers and building more images on top of the base.
The last step is pushing to quay.io which is when the error occurs.

**Comment by rhatdan** [comment] 2019-11-21 15:52
@nalind @giuseppe Any ideas?

**Comment by giuseppe** [comment] 2019-11-22 09:02
@tmds how easily can you reproduce this issue?

Can you please show the output for `cat /proc/self/mountinfo` and the `/tmp/podman-log` file you got with `sudo strace -o /tmp/podman-log -f -Z podman push quay.io/fedora-dotnet/dotnet:3.1` (assuming the last command fails as above)?

**Comment by tmds** [comment] 2019-11-22 11:01
@giuseppe I've send some info via mail.

I'll look into providing these trace files next week.

**Comment by giuseppe** [comment] 2019-11-22 13:22
@tmds thanks for the info!  That was really helpful.

I was able to reproduce it once I've started using the kernel version you specified above.

The latest kernel available on Fedora 30 seems to work fine.

Duplicate of: https://github.com/containers/libpod/issues/3540

**Closed by giuseppe** 2019-11-22 13:22 UTC
Labels: kind/bug

**Comment by dezza** [comment] 2023-09-04 00:39
In case anyone is stuck in this state here is how I fixed it. How it happened for me was that cgroup.slice was accidentally started on the wrong user at one point and didn't remove containers completely once attempted on the other user.

I did attempt `podman system reset` first which gave

```sh
podman system reset
WARNING! This will remove:
        - all containers
        - all pods
        - all images
        - all networks
        - all build cache
        - all machines
        - all volumes
        - the graphRoot directory: "/home/ct/.local/share/containers/storage"
        - the runRoot directory: "/tmp/containers-user-1001/containers"
WARNING! The following external containers will be purged:
        - fe5786916e96 (dns1)
        - 3c8cb8dd26b2 (dns2)
Are you sure you want to continue? [y/N] y
ERRO[0003] no container with name or ID "fe5786916e961265d8dba92264c6735f3e8149eeab70169140b6447c9cb4db16" found: no such container
ERRO[0003] image used by 3c8cb8dd26b2288e5c561ffb9e024ceea07d1e1bb4048ac4f1360b641e0d6ff7: image is in use by a container: consider listing external containers and force-removing image
```

```sh
podman rm -f dns1 dns2` was attempted
Error: container "dns1" is mounted and cannot be removed without using force: container state improper
WARN[0000] Failed to add pause process to systemd sandbox cgroup: dial unix /run/user/1001: connect: connection refused
Error: container "dns2" is mounted and cannot be removed without using force: container state improper
```

There is no mounted volumes in `/proc/self/mountinfo` and `podman inspect dns1` or `podman inspect dns2` returns `Error: no such object`

open `.local/share/containers/storage/overlay-containers/containers.json` with editor of choice (vim in this case) and place cursor on start of the 2 stuck container entries then press `d%` to delete until end-brace and repeat with the other containers.
