### ISSUE TITLE
podman pull error message is not descriptive

### ISSUE THREAD

**Issue by ibazulic** [containers/libpod#2829] opened 2019-04-02 12:28 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When a `podman pull` is issued on the registry that is not using HTTPS (internal registry for testing purposes), the error message given by `podman` doesn't say anything why the operation failed.

**Steps to reproduce the issue:**

1. set up an internal docker registry that doesn't use HTTPS

2. try `podman pull` on any image from the registry.

**Describe the results you received:**
The following result was received:

```
# podman pull --creds "username:password" docker://registry.local:80/username/test-big-image:latest
Trying to pull docker://registry.local:80/username/test-big-image:latest...Failed
(0x1840f00,0xc000226280)
```

**Describe the results you expected:**
I expect podman to provide the info why it failed. I only found out why it failed after using debug output:

```
# podman pull --creds "username:password" docker://registry.local:80/username/test-big-image:latest --log-level debug
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /var/lib/containers/storage 
DEBU[0000] Using run root /var/run/containers/storage   
DEBU[0000] Using static dir /var/lib/containers/storage/libpod 
DEBU[0000] Using tmp dir /var/run/libpod                
DEBU[0000] Using volume path /var/lib/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] overlay test mount with multiple lowers succeeded 
DEBU[0000] overlay test mount indicated that metacopy is not being used 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
INFO[0000] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.mountopt=nodev]registry.local:80/username/test-big-image:latest" 
Trying to pull docker://registry.local:80/username/test-big-image:latest...DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for registry.local:80/username/test-big-image:latest 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/ubuntu.tardis.local:80 
DEBU[0000] Using blob info cache at /var/lib/containers/cache/blob-info-cache-v1.boltdb 
DEBU[0000] GET https://registry.local:80/v2/       
DEBU[0000] Ping https://registry.local:80/v2/ err Get https://registry.local:80/v2/: http: server gave HTTP response to HTTPS client (&url.Error{Op:"Get", URL:"https://registry.local:80/v2/", Err:(*errors.errorString)(0xc000378010)}) 
DEBU[0000] GET https://registry.local:80/v1/_ping  
DEBU[0000] Ping https://registry.local:80/v1/_ping err Get https://registry.local:80/v1/_ping: http: server gave HTTP response to HTTPS client (&url.Error{Op:"Get", URL:"https://registry.local:80/v1/_ping", Err:(*errors.errorString)(0xc000352010)}) 
DEBU[0000] Error pulling image ref //registry.local:80/username/test-big-image:latest: Error determining manifest MIME type for docker://registry.local:80/username/test-big-image:latest: pinging docker registry returned: Get https://registry.local:80/v2/: http: server gave HTTP response to HTTPS client 
Failed
(0x1840f00,0xc0004568a0)
```

**Output of `podman version`:**

```
# podman version
Version:            1.1.2
RemoteAPI Version:  1
Go Version:         go1.11.5
Git Commit:         a95a49d3038462d033f84ac314ec8a3064a99cff
Built:              Tue Mar  5 19:10:31 2019
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
# podman info --debug
debug:
  compiler: gc
  git commit: a95a49d3038462d033f84ac314ec8a3064a99cff
  go version: go1.11.5
  podman version: 1.1.2
host:
  BuildahVersion: 1.7.1
  Conmon:
    package: podman-1.1.2-1.git0ad9b6b.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: a95a49d3038462d033f84ac314ec8a3064a99cff'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 8096129024
  MemTotal: 33146167296
  OCIRuntime:
    package: containerd.io-1.2.5-3.1.fc29.x86_64
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  hostname: fedora.tardis.local
  kernel: 5.0.3-200.fc29.x86_64
  os: linux
  rootless: false
  uptime: 5h 58m 27.42s (Approximately 0.21 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The registry is run inside VirtualBox.

**Comment by giuseppe** [comment] 2019-04-12 12:30
duplicate of: https://github.com/containers/libpod/issues/2710

**Comment by rhatdan** [comment] 2019-04-12 13:52
Ok I will close this issue then.

**Closed by rhatdan** 2019-04-12 13:52 UTC
Labels: kind/bug
