### ISSUE TITLE
failed to write to /proc/self/oom_score_adj: Permission denied

### ISSUE THREAD

**Issue by krashekspres** [containers/libpod#3024] opened 2019-04-26 13:10 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When running rootless podman I'm getting `failed to write to /proc/self/oom_score_adj: Permission denied` error, but container runs after it.

**Steps to reproduce the issue:**

1. `podman run -it --rm anycontainer`

**Describe the results you received:**
The container runs, but after I get an error message in the terminal

**Describe the results you expected:**
The container should start without error message.

**Additional information you deem important (e.g. issue happens only occasionally):**
Error message: `failed to write to /proc/self/oom_score_adj: Permission denied`
**Output of `podman version`:**

```
podman version 1.2.0
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.6
  podman version: 1.2.0
host:
  BuildahVersion: 1.7.2
  Conmon:
    package: podman-1.2.0-1.1.x86_64
    path: /usr/lib/podman/bin/conmon
    version: "failed to write to /proc/self/oom_score_adj: Permission denied, conmon
      version 1.14.0\ncommit: "
  Distribution:
    distribution: '"opensuse-tumbleweed"'
    version: "20190423"
  MemFree: 2402082816
  MemTotal: 11992973312
  OCIRuntime:
    package: runc-1.0.0~rc6-3.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6
      spec: 1.0.1-dev
  SwapFree: 2145845248
  SwapTotal: 2147479552
  arch: amd64
  cpus: 4
  hostname: kraken
  kernel: 5.0.8-1-default
  os: linux
  rootless: true
  uptime: 4h 43m 30.3s (Approximately 0.17 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
store:
  ConfigFile: /home/dario/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/dario/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 20
  RunRoot: /tmp/1000
  VolumePath: /home/dario/.local/share/containers/storage/volumes

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by rhatdan** [comment] 2019-04-26 13:12
Rootless?
Is this an SELinux issue?  Does it work in permissive mode?

**Comment by edsantiago** [comment] 2019-04-26 13:13
Not an SELinux issue: I'm seeing it on my Gentoo laptop, which (I know, I know!) does not have SELinux enabled.

**Comment by krashekspres** [comment] 2019-04-26 13:13
It's rootless.

**Comment by rhatdan** [comment] 2019-04-26 13:16
I tried on Fedora and it is allowed.
Could you try in --privileged and see if it allowed.

**Comment by rhatdan** [comment] 2019-04-26 13:17
It it works with --privileged then try without --privileged and try
--security-opt seccomp=unconfined

**Comment by krashekspres** [comment] 2019-04-26 13:19
Same error for both options.

**Comment by edsantiago** [comment] 2019-04-26 13:19
Same here (i.e. `--privileged` and `--security-opt seccomp=unconfined` make no difference)

**Comment by mheon** [comment] 2019-04-26 13:21
I bet this is Conmon. We put an OOM adjust in there that isn't fatal if it
fails, but for some time it logged errors every time it did. I believe it's
since been changed to do so only with debug level logging.

**Comment by vrothberg** [comment] 2019-04-26 13:23
@mheon, do you know when it has been changed? The [podman v1.2.0 package in openSUSE](https://build.opensuse.org/package/show/devel:kubic/podman) is using conmon from CRI-) 1.14.0.

**Comment by mheon** [comment] 2019-04-26 13:35
I'm pretty sure @haircommander made the change in question, so I'll tag him in for that one

**Comment by haircommander** [comment] 2019-04-26 13:35
this is conmon, I didn't know any podman was shipping with that updated of a CRI-O version. We expect this debug message, though I actually thing conmon's log handling is weird at the moment. (note, the change I made just made this error non fatal)

**Comment by haircommander** [comment] 2019-04-26 13:36
I feel like this should just silently happen tbh

**Comment by vrothberg** [comment] 2019-04-26 13:38
Looking forward to c/conmon kicking off :) @sysrich, I think the openSUSE could downgrade to an older conmon for podman to quick-fix the issue.

**Comment by haircommander** [comment] 2019-04-26 13:42
@sysrich @vrothberg release 1.13.3 should not have this problem

**Comment by haircommander** [comment] 2019-04-26 14:32
ah actually, we did fix this problem upstream, but haven't cut a new release on 1.14 with the updates yet. I will look into it, but for the time being I'd go back to 1.13.3 so users don't think rootless is failing

**Comment by edsantiago** [comment] 2019-05-02 15:18
My laptop updated cri-o this morning, 1.13.5 to 1.13.7, and the `oom_score_adj` warning is gone.

**Comment by baude** [comment] 2019-05-29 15:56
are we good to close this?

**Comment by haircommander** [comment] 2019-05-29 15:59
yes--people will need to use containers/conmon 0.2.0

**Comment by krashekspres** [comment] 2019-06-03 16:20
This was fixed for me with the last TW update.
Thanks.

**Closed** 2019-06-04 07:56 UTC
Labels: kind/bug, retiring

**Comment by tobwen** [comment] 2019-10-19 01:41
Problem returned in rootless :(

**Describe the results you received:**
```
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied
```

**Output of `podman version`:**
```
Version:            1.6.3-dev
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**
```
Version:            1.6.3-dev
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64
tobwen@pgsql:~/podman/usr/local/bin$ ./podman --tmpdir /tmp/user/1000/libpod/tmp info debug
Error: `podman system info` takes no arguments
tobwen@pgsql:~/podman/usr/local/bin$ ./podman --tmpdir /tmp/user/1000/libpod/tmp info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.5
  podman version: 1.6.3-dev
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: Unknown
    path: /home/tobwen/podman/usr/local/bin/conmon
    version: 'conmon version 2.0.3-dev, commit: bc758d8bd98a29ac3aa4f62a886575bfec0e39a1'
  Distribution:
    distribution: debian
    version: "9"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    - container_id: 65537
      host_id: 1258512
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    - container_id: 65537
      host_id: 1258512
      size: 65536
  MemFree: 35587067904
  MemTotal: 38205444096
  OCIRuntime:
    name: runc
    package: Unknown
    path: /home/tobwen/podman/usr/local/bin/runc
    version: |-
      runc version 1.0.0-rc9+dev
      commit: 4e3701702e966b4258fbab5b92efa6418c5ae6c6
      spec: 1.0.1-dev
  SwapFree: 8586784768
  SwapTotal: 8586784768
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: pgsql
  kernel: 4.19.0-0.bpo.6-amd64
  os: linux
  rootless: true
  uptime: 29h 19m 13.88s (Approximately 1.21 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/tobwen/.config/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/tobwen/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /tmp/user/1000
  VolumePath: /home/tobwen/.local/share/containers/storage/volumes
```

**Comment by rhatdan** [comment] 2019-10-20 11:29
@tobwen what command were you executing when you saw this error?  If you turn on debug logging you will still see it.

**Comment by tobwen** [comment] 2019-10-20 12:50
Due to bugs with the local config, I have to use this commandline

```
/home/tobwen/podman/usr/local/bin/podman --log-level=debug \
--tmpdir /tmp/user/1000/libpod/tmp \
--conmon /home/tobwen/podman/usr/local/bin/conmon \
--network-cmd-path /home/tobwen/podman/usr/local/bin/slirp4netns \
--runtime /home/tobwen/podman/usr/local/bin/runc \
--storage-driver overlay \
--storage-opt "overlay.mount_program=/home/tobwen/podman/usr/local/bin/fuse-overlayfs"
```

When not using _debug logging_, I don't see it. But that's interesting:
```
$ ls -al /proc/self/oom_score_adj
-rw-r--r-- 1 tobwen tobwen 0 Oct 20 12:43 /proc/self/oom_score_adj
```

**Comment by rhatdan** [comment] 2019-10-21 11:07
It might be happening within a user namespace.

Both of these are successful
```
$ echo 1 > /proc/self/oom_score_adj 
$ podman unshare echo 1 > /proc/self/oom_score_adj 
$ podman run fedora echo 1 > /proc/self/oom_score_adj

All of these work.  But

echo -1 > /proc/self/oom_score_adj 
bash: echo: write error: Permission denied
```

**Comment by rhatdan** [comment] 2019-10-21 11:10
Conmon is attempting to set this score on rootless which is not allowed.
```
conmon.c:#define OOM_SCORE "-999"
conmon.c:		if (write(oom_score_fd, OOM_SCORE, strlen(OOM_SCORE)) < 0) {
```

**Comment by jasonbrooks** [comment] 2019-10-31 16:13
I'm trying to get toolbox running in silverblue 31. It fails with:

```
Error: unable to start container "fedora-toolbox-31": writing file '/proc/46288/gid_map': Operation not permitted
setgid(0): Invalid argument: OCI runtime permission denied error
toolbox: failed to start container fedora-toolbox-31
```

Elsewhere, I saw a suggestion about running with: `systemd-run --scope --user podman --log-level debug start fedora-toolbox-31`. When I do that, I get an error like I'm seeing in here:

```
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied
```

**Comment by haircommander** [comment] 2019-10-31 16:59
@jasonbrooks that message is expected, it won't be printed without `--log-level debug`

**Comment by jasonbrooks** [comment] 2019-10-31 17:02
@haircommander Ah, so not related to my toolbox issue

**Comment by haircommander** [comment] 2019-10-31 17:05
that is correct :slightly_smiling_face:

**Comment by DaanDeMeyer** [comment] 2019-11-25 07:37
Having the same problem on Ubuntu 16.04.

Logs:

```
time="2019-11-25T08:33:48+01:00" level=debug msg="using conmon: \"/usr/bin/conmon\""
time="2019-11-25T08:33:48+01:00" level=debug msg="Initializing boltdb state at /home/daan_dm/.local/share/containers/storage/libpod/bolt_state.db"
time="2019-11-25T08:33:48+01:00" level=debug msg="Using graph driver vfs"
time="2019-11-25T08:33:48+01:00" level=debug msg="Using graph root /home/daan_dm/.local/share/containers/storage"
time="2019-11-25T08:33:48+01:00" level=debug msg="Using run root /run/user/1000"
time="2019-11-25T08:33:48+01:00" level=debug msg="Using static dir /home/daan_dm/.local/share/containers/storage/libpod"
time="2019-11-25T08:33:48+01:00" level=debug msg="Using tmp dir /run/user/1000/libpod/tmp"
time="2019-11-25T08:33:48+01:00" level=debug msg="Using volume path /home/daan_dm/.local/share/containers/storage/volumes"
time="2019-11-25T08:33:48+01:00" level=debug msg="Set libpod namespace to \"\""
time="2019-11-25T08:33:48+01:00" level=debug msg="[graphdriver] trying provided driver \"vfs\""
time="2019-11-25T08:33:48+01:00" level=debug msg="Initializing event backend journald"
time="2019-11-25T08:33:48+01:00" level=debug msg="using runtime \"/usr/sbin/runc\""
time="2019-11-25T08:33:48+01:00" level=warning msg="Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument"
time="2019-11-25T08:33:48+01:00" level=info msg="running as rootless"
time="2019-11-25T08:33:48+01:00" level=debug msg="using conmon: \"/usr/bin/conmon\""
time="2019-11-25T08:33:48+01:00" level=debug msg="Initializing boltdb state at /home/daan_dm/.local/share/containers/storage/libpod/bolt_state.db"
time="2019-11-25T08:33:48+01:00" level=debug msg="Using graph driver vfs"
time="2019-11-25T08:33:48+01:00" level=debug msg="Using graph root /home/daan_dm/.local/share/containers/storage"
time="2019-11-25T08:33:48+01:00" level=debug msg="Using run root /run/user/1000"
time="2019-11-25T08:33:48+01:00" level=debug msg="Using static dir /home/daan_dm/.local/share/containers/storage/libpod"
time="2019-11-25T08:33:48+01:00" level=debug msg="Using tmp dir /run/user/1000/libpod/tmp"
time="2019-11-25T08:33:48+01:00" level=debug msg="Using volume path /home/daan_dm/.local/share/containers/storage/volumes"
time="2019-11-25T08:33:48+01:00" level=debug msg="Set libpod namespace to \"\""
time="2019-11-25T08:33:48+01:00" level=debug msg="Initializing event backend journald"
time="2019-11-25T08:33:48+01:00" level=warning msg="Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument"
time="2019-11-25T08:33:48+01:00" level=debug msg="using runtime \"/usr/sbin/runc\""
time="2019-11-25T08:33:48+01:00" level=debug msg="Made network namespace at /run/user/1000/netns/cni-6ff85782-6b2e-b06f-39af-1577001f1c7a for container e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7"
time="2019-11-25T08:33:48+01:00" level=debug msg="mounted container \"e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7\" at \"/home/daan_dm/.local/share/containers/storage/vfs/dir/cd484c2f7db3593163d5053d103ba96ce1226a68f808fea146065a4693b6981a\""
time="2019-11-25T08:33:48+01:00" level=debug msg="slirp4netns command: /usr/bin/slirp4netns --disable-host-loopback --mtu 65520 --enable-sandbox -c -e 3 -r 4 --netns-type=path /run/user/1000/netns/cni-6ff85782-6b2e-b06f-39af-1577001f1c7a tap0"
time="2019-11-25T08:33:48+01:00" level=debug msg="Created root filesystem for container e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7 at /home/daan_dm/.local/share/containers/storage/vfs/dir/cd484c2f7db3593163d5053d103ba96ce1226a68f808fea146065a4693b6981a"
time="2019-11-25T08:33:48+01:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 nameserver 8.8.4.4]"
time="2019-11-25T08:33:48+01:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
time="2019-11-25T08:33:48+01:00" level=debug msg="/etc/system-fips does not exist on host, not mounting FIPS mode secret"
time="2019-11-25T08:33:48+01:00" level=debug msg="Created OCI spec for container e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7 at /home/daan_dm/.local/share/containers/storage/vfs-containers/e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7/userdata/config.json"
time="2019-11-25T08:33:48+01:00" level=debug msg="/usr/bin/conmon messages will be logged to syslog"
time="2019-11-25T08:33:48+01:00" level=debug msg="running conmon: /usr/bin/conmon" args="[--api-version 1 -c e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7 -u e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7 -r /usr/sbin/runc -b /home/daan_dm/.local/share/containers/storage/vfs-containers/e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7/userdata -p /run/user/1000/vfs-containers/e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7/userdata/pidfile -l k8s-file:/home/daan_dm/.local/share/containers/storage/vfs-containers/e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7/userdata/ctr.log --exit-dir /run/user/1000/libpod/tmp/exits --socket-dir-path /run/user/1000/libpod/tmp/socket --log-level debug --syslog --conmon-pidfile /run/user/1000/vfs-containers/e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/daan_dm/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /run/user/1000 --exit-command-arg --log-level --exit-command-arg error --exit-command-arg --cgroup-manager --exit-command-arg cgroupfs --exit-command-arg --tmpdir --exit-command-arg /run/user/1000/libpod/tmp --exit-command-arg --runtime --exit-command-arg runc --exit-command-arg --storage-driver --exit-command-arg vfs --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg container --exit-command-arg cleanup --exit-command-arg e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7]"
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

time="2019-11-25T08:33:48+01:00" level=debug msg="Cleaning up container e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7"
time="2019-11-25T08:33:48+01:00" level=debug msg="Tearing down network namespace at /run/user/1000/netns/cni-6ff85782-6b2e-b06f-39af-1577001f1c7a for container e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7"
time="2019-11-25T08:33:48+01:00" level=debug msg="unmounted container \"e9894c7b73b71e1666b8808c403044c278fb2ccf12a79e1c55dbb306f1023ac7\""
time="2019-11-25T08:33:48+01:00" level=error msg="unable to start container \"e9894c7b73b7\": container create failed (no logs from conmon): EOF"
```

Podman info:

```
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.3, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 29272698880
  MemTotal: 33498562560
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2147479552
  SwapTotal: 2147479552
  arch: amd64
  cpus: 12
  eventlogger: journald
  hostname: pcl001477a
  kernel: 5.0.0-37-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.2
      commit: unknown
  uptime: 14m 12.79s
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/daan_dm/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/daan_dm/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 2
  RunRoot: /run/user/1000
  VolumePath: /home/daan_dm/.local/share/containers/storage/volumes
```

Command to create the container:

`podman create --name=dcn --cap-add=CAP_SYS_ADMIN dcn /lib/systemd/systemd`

**Comment by nonetrix** [comment] 2022-06-26 05:30
Having this issue on Fedora Silverblue using toolbox,  strangely didn't happen until I rebased by system to KDE using this guide
https://communityblog.fedoraproject.org/rebasing-fedora-silverblue-to-kinoite/
Doing it as sudo works fine however but that seems like it's begging for trouble

**Comment by nonetrix** [comment] 2022-06-26 05:57
fixed itself :woozy_face:

**Comment by NicolaiLolansen** [comment] 2023-09-15 13:00
I know this is closed and all, but what worked for me was setting this environment variable as mentioned in the release notes:

`DOCKER_BUILDKIT=0` 

podman version 4.6.1
Docker Compose version v2.21.0

**Comment by GregJohnStewart** [comment] 2023-09-15 21:51
I'll follow up and say that I am also hitting this issue: (That env var didn't work for me.)

```
Error: unable to start container "6ce32cfb77275241d7ec6c4ee7f0f05022629db07c711fbefaef08110f8279c2": crun: write to `/proc/self/oom_score_adj`: Permission denied: OCI permission denied
```

I'll say that this doesn't happen for a `run` command, but does happen for a `start` command...

podman version 4.6.2 on Fedora

**Comment by Ovyerus** [comment] 2023-09-16 14:02
Running into this problem on a new Fedora machine I'm trying to set up, except plan `podman run` is working fine, but `docker-compose up` is giving me this problem.

Podman 4.6.2, Compose v2.21.0

```
$ podman run --rm hello-world
!... Hello Podman World ...!
<snip>
```
```
$ cat docker-compose.yml
version: "3"

services:
  foo:
    image: hello-world

$ docker-compose up
[+] Running 2/2
 ✔ Network test_default   Created                                                                                  0.0s
 ✔ Container test-foo-1  Created                                                                                  1.0s
Attaching to test-foo-1
Error response from daemon: crun: write to `/proc/self/oom_score_adj`: Permission denied: OCI permission denied
```

Downgrading to Podman `4.4.2` (only other installable version out of the box with dnf) shows no error (but just doesn't have any output or anything weirdly), another server running `4.6.1` works perfectly fine.

**Comment by MaximilianGaedig** [comment] 2023-09-17 12:56
This seems like a recent regression, I have the exact same problem @Ovyerus has `docker-compose up` does not work, `podman run hello-world` works.

**Comment by bosd** [comment] 2023-09-17 20:00
> This seems like a recent regression, I have the exact same problem @Ovyerus has `docker-compose up` does not work, `podman run hello-world` works.

Same problem here on fedora 38.
How can this issue be fixed?

**Comment by bosd** [comment] 2023-09-17 22:21
Update: This solved it for me:

edit  /usr/lib/systemd/system/user@.service and remove the following line.

`OOMScoreAdjust=100`
https://github.com/systemd/systemd/commit/ce7de0ba8ef355c5119e7dffc46e075b257dc90d#diff-e712f4f510835ff8be07a088402d790305356f9284023c7a286056ccf38147e3R28

Reboot

Source: https://bbs.archlinux.org/viewtopic.php?pid=2012166#p2012166

**Comment by GregJohnStewart** [comment] 2023-09-17 23:26
In case this helps determine the issue, I have attached two inspect outputs, one for run and one from the (failing) start.

They aren't _quite_ the same image, due to the start being created from the java api for Docker, but they are close.

[inspects.zip](https://github.com/containers/podman/files/12643921/inspects.zip)

**Comment by MaximilianGaedig** [comment] 2023-09-18 08:25
@bosd thank you for the fix, this worked for me, but this fix is not optimal, this makes user processes get oom killed just as root processes , while they should be prioritized by my understanding.

**Comment by bruno-fs** [comment] 2023-09-19 18:14
I recently updated to podman 4.6.2 on fedora 38 and noticed this issue as well.

**Comment by setofaces** [comment] 2023-09-19 19:18
> Update: This solved it for me:
> 
> edit /usr/lib/systemd/system/[user@.service](mailto:user@.service) and remove the following line.
> 
> `OOMScoreAdjust=100` [systemd/systemd@ce7de0b#diff-
> 
> Reboot
> 
> Source: https://bbs.archlinux.org/viewtopic.php?pid=2012166#p2012166

MacOS with latest podman here. I remove provided line via podman machine ssh connection however after restart of the VM, this property of OOMScoreAdjust=100 appears to be there again and error expectedly repeats, is there any workaround in that case? Thank you

**Comment by setofaces** [comment] 2023-09-21 17:51
UPD: rebooting via ssh sudo prevents overwrting this file, but problem still remains even without OOMScoreAdjust=100

**Comment by jorhett** [comment] 2023-09-22 03:12
4 years later?  The old bug should be locked and a new bug should be opened 🙏

**Comment by jenifera0110** [comment] 2023-09-22 19:16
> I have updated to Podman 4.6.2 and noticed the regression.
> 
> The workaround from @bosd worked on my box - but not sure that's really optimal, as @MaximilianGaedig states in his comment

chmod: changing permissions of '/usr/lib/systemd/system/user@.service': Read-only file system. Sudo doesn't work, how do we write this file to remove that property ?

**Comment by setofaces** [comment] 2023-09-22 20:37
> > I have updated to Podman 4.6.2 and noticed the regression.
> > The workaround from @bosd worked on my box - but not sure that's really optimal, as @MaximilianGaedig states in his comment
> 
> chmod: changing permissions of '/usr/lib/systemd/system/[user@.service](mailto:user@.service)': Read-only file system. Sudo doesn't work, how do we write this file to remove that property ?
Just mount directory, then change permissions

**Comment by stan-shih** [comment] 2023-09-24 08:45
> > I have updated to Podman 4.6.2 and noticed the regression.
> > The workaround from @bosd worked on my box - but not sure that's really optimal, as @MaximilianGaedig states in his comment
> 
> chmod: changing permissions of '/usr/lib/systemd/system/[user@.service](mailto:user@.service)': Read-only file system. Sudo doesn't work, how do we write this file to remove that property ? Just mount directory, then change permissions

I fixed it below the link(https://github.com/containers/podman/issues/19930#issuecomment-1732162092). You can try it.

**Comment by jenifera0110** [comment] 2023-09-25 07:20
> > > I have updated to Podman 4.6.2 and noticed the regression.
> > > The workaround from @bosd worked on my box - but not sure that's really optimal, as @MaximilianGaedig states in his comment
> > 
> > 
> > chmod: changing permissions of '/usr/lib/systemd/system/[user@.service](mailto:user@.service)': Read-only file system. Sudo doesn't work, how do we write this file to remove that property ? Just mount directory, then change permissions
> 
> I fixed it below the link([#19930 (comment)](https://github.com/containers/podman/issues/19930#issuecomment-1732162092)). You can try it.

This doesn't help me.

<img width="1020" alt="Screenshot 2023-09-25 at 09 19 37" src="https://github.com/containers/podman/assets/67537416/a9f1adb8-d95b-422c-9e21-95734b8ac0ce">

**Comment by kdubois** [comment] 2023-09-25 13:53
I'm ran into the same issue on Fedora 38. Per a comment in #19930 I downgraded crun `sudo dnf downgrade crun` and that seems to have worked for now.

**Comment by WinterWolf98** [comment] 2023-09-26 10:45
Was able to solve this by upgrading to [Fedora v38.20230902.3.0](https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/38.20230902.3.0/x86_64/fedora-coreos-38.20230902.3.0-qemu.x86_64.qcow2.xz)

**Comment by fansari** [comment] 2023-10-01 14:52
I have updated from Fedora Silverblue 38 to 39 and one of the first things I did is to check whether podman is still working. Nope! All rootless containers fail with

```
crun: write to `/proc/self/oom_score_adj`: Permission denied: OCI permission denied
```

podman version 4.6.2

**Comment by stemid** [comment] 2023-10-13 22:27
> Update: This solved it for me:
> 
> edit /usr/lib/systemd/system/[user@.service](mailto:user@.service) and remove the following line.
> 
> `OOMScoreAdjust=100` [systemd/systemd@ce7de0b#diff-e712f4f510835ff8be07a088402d790305356f9284023c7a286056ccf38147e3R28](https://github.com/systemd/systemd/commit/ce7de0ba8ef355c5119e7dffc46e075b257dc90d#diff-e712f4f510835ff8be07a088402d790305356f9284023c7a286056ccf38147e3R28)
> 
> Reboot
> 
> Source: https://bbs.archlinux.org/viewtopic.php?pid=2012166#p2012166

Since this thread comes up on Google I just want to add that this helped me with running Gitlab Runner in a rootless podman on CoreOS. Since /usr is write protected, I copied user@.service to /etc/systemd/system, and removed that one line, rebooted and now Gitlab runner can run jobs again.

**Comment by andrewgdunn** [comment] 2023-10-13 23:39
@stemid appreciate that comment, I've not attempted this on my systems (which are centos9stream gitlab runners)... wondering if it would be better to consider the override mechanism within systemd.

**Comment by stemid** [comment] 2023-10-14 08:08
> @stemid appreciate that comment, I've not attempted this yet on my systems (which are centos9stream gitlab runners)... wondering if it would be better to consider the override mechanism within systemd.

Yeah that is actually what I ended up doing, my comment was a bit premature. I ended up using the equivalent of systemctl edit user@.service but since I deploy on CoreOS with Ignition that means I created the directory /etc/systemd/system/user@.service.d with the file override.conf and just two lines;

```
[Service]
OOMScoreAdjust=
```

**Comment by edgarjoao** [comment] 2023-11-28 19:09
Hi @stemid 
I just followed the steps provided by you, but still not able to start any container.

Here is my configuration.

Fedora Linux 39 (Server Edition)
Podman 
Client:       Podman Engine
Version:      4.7.2
API Version:  4.7.2
Go Version:   go1.21.1
Built:        Tue Oct 31 08:32:01 2023
OS/Arch:      linux/amd64

crun version 1.11.2
commit: ab0edeef1c331840b025e8f1d38090cfb8a0509d
rundir: /run/user/1001/crun
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL

Any advice?

Thanks,
Edgar

**Comment by edgarjoao** [comment] 2023-12-06 00:23
Hi there,
After install docker, I was able to run podman containers

`sudo dnf -y install dnf-plugins-core
sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo`
