### ISSUE TITLE
podman cp does not change ownership of files (sometimes)

### ISSUE THREAD

**Issue by MarcoFalke** [containers/libpod#3218] opened 2019-05-28 21:34 UTC
/kind bug

Unfortunately I can not reproduce this with a minimal example, so feel free to close this issue.

According to the documentation, the ownership should be set to the user that ran `podman cp` (see https://docs.docker.com/engine/reference/commandline/cp/#extended-description).
However, sometimes `podman cp` will change the owner, and sometimes it does not.

**Steps to reproduce the issue:**

*Working* example:

```
$ podman exec jolly_goodall touch           /tmp/new_file
$ podman exec jolly_goodall chown 1888:1888 /tmp/new_file
$ podman exec jolly_goodall ls -l           /tmp/new_file
-rw-r--r--. 1 1888 1888 0 May 28 21:29 /tmp/new_file
$ podman cp   jolly_goodall:/tmp/new_file /tmp/f_2
$ ll /tmp/f_2
-rw-r--r--. 1 marco marco 0 May 28 17:29 /tmp/f_2
```

*Broken* example:

```
$ cat base-bionic-amd64.Dockerfile 
FROM ubuntu:bionic

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get --no-install-recommends -y install pciutils build-essential git subversion language-pack-en wget lsb-release linux-image-generic grub-pc openssh-server

RUN useradd -ms /bin/bash -U ubuntu
USER ubuntu:ubuntu
WORKDIR /home/ubuntu

CMD ["sleep", "infinity"]
$ podman build --pull -f base-bionic-amd64.Dockerfile -t test_002 .
$ podman run -d --name run_002 test_002:latest
$ podman exec -u ubuntu -i run_002 bash -c "echo > /home/ubuntu/test_file"
$ podman cp run_002:/home/ubuntu/test_file /tmp/test_002
$ ls -l /tmp/test_002/
total 4
-rw-r--r--. 1 100999 100999 1 Jun 25 09:52 test_file
```

(See that `ls -l` displays different owners)

**Output of `podman version`:**

```
podman version 1.3.1
```

**Comment by MarcoFalke** [comment] 2019-06-25 13:53
I think I figured out steps to reproduce:


```
$ cat base-bionic-amd64.Dockerfile 
FROM ubuntu:bionic

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get --no-install-recommends -y install pciutils build-essential git subversion language-pack-en wget lsb-release linux-image-generic grub-pc openssh-server

RUN useradd -ms /bin/bash -U ubuntu
USER ubuntu:ubuntu
WORKDIR /home/ubuntu

CMD ["sleep", "infinity"]
$ podman build --pull -f base-bionic-amd64.Dockerfile -t test_002 .
$ podman run -d --name run_002 test_002:latest
$ podman exec -u ubuntu -i run_002 bash -c "echo > /home/ubuntu/test_file"
$ podman cp run_002:/home/ubuntu/test_file /tmp/test_002
$ ls -l /tmp/test_002/
total 4
-rw-r--r--. 1 100999 100999 1 Jun 25 09:52 test_file

**Comment by mheon** [comment] 2019-06-25 14:17
I think this is actually expected behavior - 100999 looks like the correct UID for the first user to be created in that rootless container. Inside the container `ubuntu` is probably UID 1000, so that's mapping to `100999` outside the container. `podman cp` retained the original UID here - this isn't a bug, it's just how rootless containers work.

We could potentially consider a flag for rootless containers that would squash UIDs for rootless containers down to only the UID of the user that ran the container.

**Comment by QiWang19** [comment] 2019-06-25 14:42
@mheon  why there's different  UID/GID result when the issues was reported https://github.com/containers/libpod/issues/3218#issue-449488229 ?

**Comment by MarcoFalke** [comment] 2019-06-25 14:46
The first example ("working") uses the default user and does a `chown`. The second example uses a dockerfile with `useradd` and `USER ubuntu:ubuntu`.

**Comment by mheon** [comment] 2019-06-25 14:57
That one also looks like a user running in the container

**Comment by mheon** [comment] 2019-06-25 15:01
Alternatively... a `chown` to another user in the rootless container would do the same. Anything that's not root (or your own UID if `--userns=preserve-id` is given) is going to come out of a rootless container with distorted UIDs.

You can use `podman unshare` to chown them to your UID.

**Comment by MarcoFalke** [comment] 2019-06-25 15:57
Is there documentation available for `podman unshare`? The help doesn't tell me how to unshare the file in the running container `run_002:/home/ubuntu/test_file`.

```
$ podman help unshare
Run a command in a modified user namespace

Description:
  Runs a command in a modified user namespace.

Usage:
  podman unshare [flags] [COMMAND [ARG]]

Examples:
  podman unshare id
  podman unshare cat /proc/self/uid_map,
  podman unshare podman-script.sh

```

```
$ podman unshare run_002:/home/ubuntu/test_file 
Error: fork/exec run_002:/home/ubuntu/test_file: no such file or directory

**Comment by mheon** [comment] 2019-06-25 15:59
Unshare without arguments will get you a shell with the same user mappings as the rootless container - within that shell you can run podman cp to extract the file, and chown it to UID 0 (your user outside the container).

Given the complexity here, I am thinking that a flag for `cp` to squash UIDs is definitely a good idea.

**Comment by MarcoFalke** [comment] 2019-06-25 16:03
So I will have to call any future command that reads the file from the `podman unshare` shell?

**Comment by MarcoFalke** [comment] 2019-06-25 16:07
Would be nice if `podman cp` behaved identical to `docker cp` with regard to ownership.

> Ownership is set to the user and primary group at the destination. For example, [...] Files copied to the local machine are created with the UID:GID of the user which invoked the docker cp command. 

https://docs.docker.com/engine/reference/commandline/cp/#extended-description

**Comment by rhatdan** [comment] 2019-06-25 16:24
From the docs, it looks like podman cp should be creating files inside of the container as "root" inside of the container, if we are not, then that is a bug.

**Comment by MarcoFalke** [comment] 2019-06-27 22:32
As a workaround I use `tar` to pipe the folder to stdout on the container and `tar` to receive it from stdin on the host.

**Comment by rhatdan** [comment] 2019-08-05 20:48
@QiWang19 Can you confirm that we are doing the right thing, and can close this issue?

**Comment by QiWang19** [comment] 2019-08-05 21:27
I checked this issue, we are not doing the right thing(not the same result as docker), but I have no idea how to fix this

**Comment by rhatdan** [comment] 2019-08-06 00:19
Lets talk about this on Wednesday in the office.

**Closed** 2019-08-08 22:44 UTC
Labels: kind/bug

**Comment by joeyhub** [comment] 2020-10-19 18:26
Is it possible you accidentally applied this to tar files as well?

I have a set of build and deploy scripts that have always worked with docker.

They also worked with podman when installing the docker wrapper as a drop in replacement.

However I recently updated it (which fixes the image ls locking up problem and it taking ages) and now have a bunch of permission issues when deploying containers.

Your fix is for the cp command on a direct file but I suspect you also may have inadvertently changed the behaviour of this:

`ADD path/application.tgz /application`

When I look at an image before updating podman it has the right owners from the tar file but when I check it after everything is root.
