### ISSUE TITLE
Map mounted local volume to the same and correct local user id (rootless mode)

### ISSUE THREAD

**Issue by decosvaldo** [containers/libpod#5016] opened 2020-01-29 18:46 UTC
I'm sorry if this was already discussed, but I've tried everything from the other topics with no success...

I'm using podman in CentOS 8.1 with SELINUX enabled (enforcing) The native podman version in this system is podman version 1.4.2-stable2

I'm mounting a local volume with podman in rootless mode, using a user called web. The command I'm using is:

`podman run -v /opt/web/jurberglab/src:/var/www/html:Z -p 8080:8080 iq/jurberglab
`
iq\jurberglab is my image tag name.

The container is working, I can access it and everything is OK except for the file permissions, which I can only upload and write files to the mounted volume only if I give 777 permissions to the folder outside the container. The "web" user is the owner of the folder and It should work.

Inside the container I use the nobody user. When using the 777 permissions on the folder outside the container (/opt/web/jurberglab/src), the inside user can create and delete files correctly and I see that they are created outside the container with a high ID from the namespace range of the "web" id. If I manually give permissions to this high user ID outside the container, I can remove the 777 permissions and the container user can write files.

So, my question is: is it possible to map the correct local "web" user ID to the user inside the container so I can use and set permissions to this "web" user outside and make it work correctly inside the container?

I have tried to edit the namespace file to not use a range, but it gives an error. Also, I've tried to use the --uidmap setting, but my container won't start the services configured to run as the local nobody user. Also tried the "z" option instead of "Z".

The folder /opt/web/jurberglab/src is local and inside a xfs filesystem.

Content of /etc/subuid:
admin:100000:65535
web:165535:65536

podman unshare cat /proc/self/uid_map
         0       1001          1
         1     165535      65536

I've also tried to set the map manually inside the /home/web/.config/containers/storage.conf file.

I just need to map the outside rootless user (web) inside the container, so it will set the right permissions when performing uploads, file creation, etc.

Thank you very much.

**Comment by rhatdan** [comment] 2020-01-29 20:15
Why are you using the nobody user?  If you use a normal user then you could just create the directory owned by the users UID on the host.

**Comment by decosvaldo** [comment] 2020-01-30 11:32
> Why are you using the nobody user? If you use a normal user then you could just create the directory owned by the users UID on the host.

Your suggestion is that I use a user inside the container with the same ID as the outside user? But won't that be translated to one of the namespace ID range the same way?

**Comment by decosvaldo** [comment] 2020-01-30 13:15
> Why are you using the nobody user? If you use a normal user then you could just create the directory owned by the users UID on the host.

Answering my own question. Yes, if I use any other user than nobody the effect is the same. Files are mapped to one of the ID's inside the range, even if the inside and outside user have the same ID.

**Comment by mheon** [comment] 2020-01-30 14:33
I'm assuming that your UID on the host is 1000. As such, your `uid_map` indicates that root within the container will write files as your user on the host - did you try root?

**Comment by decosvaldo** [comment] 2020-01-30 17:04
> I'm assuming that your UID on the host is 1000. As such, your `uid_map` indicates that root within the container will write files as your user on the host - did you try root?

Just tried. Root is an exception and inside/outside files are now owned by user 0 (root), which is undesirable. If I use any other local user inside the container, it will be mapped to one ID of the namespace for the user that is running the container, and I will have wrong permissions...

Any thoughts? Really need to make this work...

**Comment by mheon** [comment] 2020-01-30 17:36
`--userns=keep-id` will automatically map your UID outside the container to the same UID inside the container, so files created as UID 1000 in the container would also be 1000 outside it

**Comment by mheon** [comment] 2020-01-30 17:38
Also, I would *not* expect files outside the container to be owned by UID 0, if they were made with root inside the container. Root inside a rootless container is not special - it's mapped to a user outside the container, by default your user, and it has no special privileges that you do not have. There are some security benefits to running as non-root in a rootless container, but they mostly have to do with potential container escapes accessing your user's files; if you need to read and write files from outside the container, you really can't avoid that.

**Comment by decosvaldo** [comment] 2020-01-30 18:21
> `--userns=keep-id` will automatically map your UID outside the container to the same UID inside the container, so files created as UID 1000 in the container would also be 1000 outside it

This completely solved my problem. Now I just have to create an inside user with the same ID from the outside rootless user.

Thank you very much!

**Comment by baude** [comment] 2020-01-30 19:49
closing as reporter claims the problem is solved

**Closed by baude** 2020-01-30 19:49 UTC
