### ISSUE TITLE
podman docker shim fails to emulate version query

### ISSUE THREAD

**Issue by ssbarnea** [containers/libpod#4602] opened 2019-11-29 17:31 UTC
Podman should assure that it returns version information in a parsable format that is backward compatible with original docker command, which happens to return a simple version string like `19.1.3.`.

At this moment podman shim returns something like:
```
# case 1
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: template: image:1:9: executing "image" at <.Server.Version>: can't evaluate field Server in type libpod.Version

# case 2 (if the nodocker file was created
Error: template: image:1:9: executing "image" at <.Server.Version>: can't evaluate field Server in type libpod.Version

# case 3
docker version
Version:            1.4.2-stable2
RemoteAPI Version:  1
Go Version:         go1.12.8
OS/Arch:            linux/amd64
``` 

One side effect of this bug is that renders docker_connection in Ansible useless on systems that have podman shim installed because it confuses Ansible.

## Examples from real docker:
```
docker version --format '{{.Server.Version}}'
19.03.5

docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
```

**Comment by rhatdan** [comment] 2019-11-30 12:54
You did not describe what is wrong with the Podman version output, or what you would expect it to be.
Is this something you would like to open a PR to fix?

**Comment by felixfontein** [comment] 2019-12-01 18:49
@rhatdan If you run `docker version --format '{{.Server.Version}}'` with the podman docker shim, it seems to produce something like
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: template: image:1:9: executing "image" at <.Server.Version>: can't evaluate field Server in type libpod.Version
```
which is very different than what the real `docker` CLI program produces:
```
19.03.5
```
This breaks programs which expect `docker version --format '{{.Server.Version}}'` to return a version number. One example (which caused this issue report) is Ansible's docker connection plugin, which is used by Molecule. (See the two issues referencing this one.)

**Comment by rhatdan** [comment] 2019-12-02 05:15
The issue with Podman is there is no Server, only a Client.

**Comment by felixfontein** [comment] 2019-12-02 07:40
@rhatdan that's true, but most users of `docker version` don't really care about that, they just need a version number so they can compare it to something to find out whether some features can be used or not. For example, Ansible's docker connection plugin compares to 1.3 (if less, won't run) and 1.7 (if less, can't specify `user` for `exec`). So as long as sensible numbers are returned for `.Server.Version` (and similar values), most (program) users will be happy.

**Comment by ssbarnea** [comment] 2019-12-02 12:44
Not sure how we are going to sort this out but it could make sense to return a fake server version in order to make Ansible happy, especially fixing ansible itself is not really possible in this case. Mainly that is a price we have to pay for creating the shim.

For molecule tests I added extra detection for podman itself and a skip-tests https://github.com/ansible/molecule/pull/2457 because it would not work with podman disguised as docker (ansible). Still, for molecule users it is easy to switch driver used to podman.

**Comment by rhatdan** [comment] 2019-12-03 02:49
Closing since the PR Merged.

**Closed by rhatdan** 2019-12-03 02:49 UTC

**Comment by rpresser** [comment] 2021-08-18 13:58
Ansible is not the only product that depends on docker version. Getting a very similar error when using the Azure cli:
`[rpresser@mtllpvtcbbld01 ~]$ az acr check-health -n dynamicswebapidev002 --yes 
Docker daemon status: available
An error occurred: DOCKER_VERSION_ERROR
An error occurred while retrieving Docker version. Please try verifying it manually.
Failed to run command 'docker version --format 'Docker version {{.Server.Version}}, build {{.Server.GitCommit}}, platform {{.Server.Os}}/{{.Server.Arch}}''. Error: template: version 1.0.0:1:45: executing "version 1.0.0" at <.Server.GitCommit>: can't evaluate field Server in type *define.Version

Please refer to https://aka.ms/acr/errors#docker_version_error for more information.
`

**Comment by rhatdan** [comment] 2021-08-20 11:17
@rpresser Are you saying we still have an issue, if so, then open a new issue, so the problem will get addressed.

**Comment by sreich** [comment] 2023-03-30 01:41
sorry for reviving this dead issue but...how is this issue resolved or did i misunderstand?

my understanding is, the purpose of a shim is to be a drop in replacement for docker, right?

how can it successfully do this if it cannot be told to lie about the version it reports? The issue is if you have an application checks the version number against a known list, to ensure it is compatible...you're stuck. Because podman reports its own version as e.g. 4.4.1 instead of 18.03.0. That is one of the things I'm running into

i would have expected a shim app to behave as others i have worked with in the past, and offer e.g. `podman --fake-version=18.03.0` allowing me to lie about whatever I need in order to get it to run

of course, less legacy is better..but podman's very design is all about legacy support. Now, would it actually run correctly if I fake the version? Well, maybe..considering it is supposed to be fairly backwards compatible, yeah?

**Comment by rhatdan** [comment] 2023-04-03 20:35
Please open a new issue and give us the specific tool that is failing.
