### ISSUE TITLE
Docker incompatibility: Podman fails if user's uid/gid is mapped in subuid/subgid

### ISSUE THREAD

**Issue by wardev** [containers/libpod#5751] opened 2020-04-07 14:38 UTC
/kind bug

**Description**

I would like podman to use all of the uid/gid mappings in subuid/subgid, which Docker currently does. It seems that currently podman only uses the first one.

**Steps to reproduce the issue:**

On Ubuntu 18.04, using podman 1.8.2 installed from kubic repo.

```bash
# setup up multiple mappings for subuid and subgid.
# Note this is what docker needs for root in container to be my user name on the host.
echo "$(id -un):$(id -u):1" | sudo tee -a /etc/subuid /etc/subgid
echo "$(id -un):120000:65536" | sudo tee -a /etc/subuid /etc/subgid
# make sure podman picks up the chages
killall podman
# try to run a container that is not in the local cache
podman run -it centos:7
```
Output from podman:

```
Trying to pull optimus.nrl.navy.mil:50443/centos:7...
Getting image source signatures
Copying blob ab5ef0e58194 done  
Copying config 5e35e350ad done  
Writing manifest to image destination
Storing signatures
ERRO[0009] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 0:54 for /run/lock/lockdev): lchown /run/lock/lockdev: invalid argument 
  ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 0:54 for /run/lock/lockdev): lchown /run/lock/lockdev: invalid argument
Error: unable to pull centos:7: 1 error occurred:
	* Error committing the finished image: error adding layer with blob "sha256:ab5ef0e5819490abe86106fd9f4381123e37a03e80e650be39f7938d30ecb530": ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 0:54 for /run/lock/lockdev): lchown /run/lock/lockdev: invalid argument
```

I expected to container to be run with a user name space that includes 1001,120000-185536. The output of `podman info` indicates it is not picking up all the uid/gid mappings correctly:

```
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
```

After commenting out the line that maps a single uid/gid in subuid/gid podman behaves correctly. It even adds the mapping that was commented out:

```
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 120000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 120000
      size: 65536
```

**Output of `podman version`:**

```
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 1.8.2~143 amd64 [installed]
```

**Comment by mheon** [comment] 2020-04-07 14:39
I recall hearing that this is a limitation of the `newuidmap`/`newgidmap` utilities, but @giuseppe would know more

**Comment by wardev** [comment] 2020-04-07 14:48
Also I forgot to mention. Thanks for making podman! Once I figured out the workaround it is already a big improvement over Docker in terms of flexibility and configurability. Thanks for all your time making this.

**Comment by giuseppe** [comment] 2020-04-07 15:03
> I recall hearing that this is a limitation of the `newuidmap`/`newgidmap` utilities, but @giuseppe would know more

I think the issue is in podman.  newuidmap/newgid map supports multiple ranges

**Comment by giuseppe** [comment] 2020-04-07 15:09
I get the multiple mappings:

```
$ podman unshare cat /proc/self/uid_map
         0       1000          1
         1     100000      65536
     65537     300000      65536
```

@wardev could you try to recreate the user namespace with `podman system migrate` ?

**Comment by wardev** [comment] 2020-04-07 18:32
I tried using `podman system migrate` in both configurations. It seems to have the same effect of killing all podman processes. i.e. nothing new to report.

With both entries in the subuid/subgid files I see:

```
$ podman unshare cat /proc/self/uid_map
         0       1001          1
```

With only the second entry in the subuid/subgid files I see:

```
$ podman unshare cat /proc/self/uid_map
         0       1001          1
         1     120000      65536
```

I tried adding another entry to the subuid file and it works as long as the entry for my uid is not present. Perhaps podman assumes that it added that entry itself and then doesn't add the others?

This fails:

```
$ cat /etc/subuid && podman system migrate && podman unshare cat /proc/self/uid_map
ward:1001:1
ward:200000:65536
ward:300000:65536
         0       1001          1
```

This works:

```
$ cat /etc/subuid && podman system migrate && podman unshare cat /proc/self/uid_map
ward:200000:65536
ward:300000:65536
         0       1001          1
         1     200000      65536
     65537     300000      65536
```

**Comment by giuseppe** [comment] 2020-04-07 19:47
in the first case, podman tries to create a namespace using new*idmap using twice the same mapping, in your case.  That fails because the kernel does not accept the same id mapped twice.  Then Podman fallbacks to create the namespace with just one id mapped, that doesn't require newuidmap.

Your user id should not be present in /etc/subuid, as it can be already used without an explicit mapping.

**Comment by wardev** [comment] 2020-04-07 20:12
Removing my uid from /etc/subuid was the workaround I found.

To enable the same behavior in Docker my uid must be the first entry in /etc/subuid. I.e. docker doesn't insert an entry for my uid. So this is a difference between docker and podman. At least it should be documented. It would be nice if podman could check if my uid is already in the mapping and skip adding it again so that I can run docker and podman with the same /etc/subuid file.

Once I figured out the difference I much prefer podman's behavior because it is easier to set up. But I would also like to be able to run podman and docker on the same machine. This issue means I have to start Docker, edit /etc/subuid, then migrate podman to get them to have the same configuration. If I need to restart docker then I have to do it all again. Maybe this should be a bug against Docker instead of podman.

**Comment by rhatdan** [comment] 2020-04-07 20:25
PRs often help these things forward...

**Comment by giuseppe** [comment] 2020-04-08 07:01
Podman doesn't require any tweak of `/etc/subuid` and `/etc/subgid` files.  Recent versions of `useradd` automatically create a range for new users and that doesn't include the user own ID mapping.   That is not needed anyway since `newuidmap/newgidmap` already allows to add it even if not specified in the `/etc/sub*id` files.

Said so, I am fine if we add a check in Podman to skip the mapping if it is the user's own ID

**Comment by giuseppe** [comment] 2020-04-09 08:04
I am closing the issue since it is not really a problem in Podman.  Fell free to open a PR to add the check for the existing UID if you'd like this behaviour

**Closed by giuseppe** 2020-04-09 08:04 UTC
Labels: kind/bug

**Comment by codefist** [comment] 2021-05-01 12:18
This IS a problem in podman, because it's a year later and I'm hitting this wall today.

**Comment by giuseppe** [comment] 2021-05-03 12:24
can you show the content of `/etc/subuid`?

**Comment by mheon** [comment] 2021-10-31 17:06
The answer from @rhatdan is correct - the UID/GID of the user should not be included. We get that implicitly.

I don't see where in the documentation the user's own UID and GID are mentioned?
