### ISSUE TITLE
Pulling from private registry without authentication needs a better error message

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#2736] opened 2019-03-21 17:52 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When pulling from a private repo without appropriate authentication, the error is not helpful, it just says "Failed"

**Steps to reproduce the issue:**

1.  podman pull docker://quay.io/{myprivaterepo}/alpine:latest

**Describe the results you received:**
```
# podman pull docker://quay.io/{myprivaterepo}/testing:third 
Trying to pull docker://quay.io/{myprivaterepo}/testing:third...Failed
(0x1840f00,0xc000486e60)
```

**Describe the results you expected:**

A message along the lines of what Docker supplies:

```
Error response from daemon: unauthorized: access to the requested resource is not authorized
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:            1.1.2
RemoteAPI Version:  1
Go Version:         go1.11.5
Git Commit:         a95a49d3038462d033f84ac314ec8a3064a99cff
Built:              Tue Mar  5 13:10:31 2019
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
podman info --debug
debug:
  compiler: gc
  git commit: a95a49d3038462d033f84ac314ec8a3064a99cff
  go version: go1.11.5
  podman version: 1.1.2
host:
  BuildahVersion: 1.7.1
  Conmon:
    package: podman-1.1.2-1.git0ad9b6b.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: a95a49d3038462d033f84ac314ec8a3064a99cff'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 931577856
  MemTotal: 2087501824
  OCIRuntime:
    package: runc-1.0.0-69.dev.git6635b4f.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: 1281cf10155a1881fbc87ee7d1401adf180963b7-dirty
      spec: 1.0.1-dev
  SwapFree: 2145894400
  SwapTotal: 2147479552
  arch: amd64
  cpus: 1
  hostname: localhost.localdomain
  kernel: 4.20.15-200.fc29.x86_64
  os: linux
  rootless: false
  uptime: 1h 20m 51.77s (Approximately 0.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 12
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 8
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment] 2019-03-21 17:57
Anything more get printed with `--log-level=debug`?

**Comment by mheon** [comment] 2019-03-21 17:57
(I think we might have a good error and be eating it)

**Comment by TomSweeneyRedHat** [comment] 2019-03-21 18:02
Me thinks you're correct @mheon, here's the last line of debug:

```
Error pulling image ref //quay.io/tomsweeneyredhat/testing:latest: Error determining manifest MIME type for docker://quay.io/tomsweeneyredhat/testing:latest: Error reading manifest latest in quay.io/tomsweeneyredhat/testing: unauthorized: access to the requested resource is not authorized 
Failed
```

**Comment by giuseppe** [comment] 2019-03-22 10:57
is it a duplicate of https://github.com/containers/libpod/issues/2710?

**Comment by rhatdan** [comment] 2019-04-13 09:30
Going to close as a duplicate.

**Closed by rhatdan** 2019-04-13 09:30 UTC
Labels: kind/bug
