### ISSUE TITLE
[rootless] unable to get inside the podman containers

### ISSUE THREAD

**Issue by balamuruganravi** [containers/libpod#6085] opened 2020-05-05 07:23 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**
`podman run -d \ 
-p {{port}}:{{port}} \ 
--name $CONTAINER_NAME \ 
-h $CONTAINER_NAME \ 
-v $CONTAINER_NAME:/usr/share/containerA/data \ 
-e "ES_JAVA_OPTS=-Xms{{ jvm_heap_size_min }} -Xmx{{ jvm_heap_size_max }}" \ 
-e "node.master=true" \ 
-e "node.ingest=true" \ 
-e "node.data=true" \ 
$CONTAINER_IMAG`

After 3-4 days uptime `podman ps` not listing any running containers. 

**Describe the results you received:**
`podman ps` does not display the running containers and `podman exec -it containerA /bin/bash` throws error cannot exec into container that is not running: container state improper
**Describe the results you expected:**
it should display the running containers and get inside to it.

**Additional information you deem important (e.g. issue happens only occasionally):**
The issue happens after 3-4 days of container uptime.

**Output of `podman version`:**
```
Version:                     1.4.4
RemoteAPI Version:  1
Go Version:               go1.10.3
OS/Arch:                   linux/amd64
```

**Output of `podman info --debug`:**

```
podman@ip-00-00-000-00[~] $ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"rhel"'
    version: "7.7"
  MemFree: 815738880
  MemTotal: 16507850752
  OCIRuntime:
    package: runc-1.0.0-65.rc8.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  hostname: ip-00-000-000-00.cloud.dev.net
  kernel: 3.10.0-1062.12.1.el7.x86_64
  os: linux
  rootless: true
  uptime: 455h 32m 46.46s (Approximately 18.96 days)
registries:
  blocked:
  - all
  insecure: null
  search:
  - registry1.global.com
  - registry2.global.com
store:
  ConfigFile: /home/podman/.config/containers/storage.conf
  ContainerStore:
    number: 6
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/podman/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 7
  RunRoot: /tmp/run-600000
  VolumePath: /home/podman/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.4.4-4.el7.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS RHEL 7.7  
AWS RHEL 8.1

**Comment by giuseppe** [comment] 2020-05-05 09:03
looks like a duplicate of: https://github.com/containers/libpod/issues/6034

If you agree, can we close this issue and keep the discussion there?

**Comment by balamuruganravi** [comment] 2020-05-05 12:38
ok. could you please update your response for my issue mentioned in #6034

**Comment by mheon** [comment] 2020-05-05 13:25
Closing as dupe of #6034

**Closed by mheon** 2020-05-05 13:25 UTC
Labels: kind/bug
