### ISSUE TITLE
podman: Copy doesn't seem to work from cache

### ISSUE THREAD

**Issue by ford-prefect** [containers/libpod#3110] opened 2019-05-12 08:27 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Run `podman build` on a `Dockerfile` that uses `FROM .. AS ...` and `COPY --from` syntax. Example: https://github.com/ford-prefect/laser-egg/blob/master/Dockerfile

2. Make some changes around the second container.

3. Run `podman build` again

**Describe the results you received:**

An error like the following is seen:

```
% docker build .           
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
STEP 1: FROM haskell:8.6 AS builder
STEP 2: WORKDIR /opt/laser-egg
--> Using cache 9df34abc65ed6df0ea5a53c43a2b84b12e50d635c260ac38554782422eb60b83
STEP 3: FROM 9df34abc65ed6df0ea5a53c43a2b84b12e50d635c260ac38554782422eb60b83 AS builder
STEP 4: ADD . .
--> Using cache cfbc6d928043c053a9fb378a7f9de6a9e6a22501d8109c03f7d101a0e0c730d6
STEP 5: FROM cfbc6d928043c053a9fb378a7f9de6a9e6a22501d8109c03f7d101a0e0c730d6 AS builder
STEP 6: RUN stack --install-ghc install && strip /root/.local/bin/laser-egg
--> Using cache 1dbd7dd8bd67b2a4faa9eb5a53165fe53766ed73347041cb30e93e7a0d2d4929
STEP 7: COMMIT 
--> 96b5fb8f4a76bdb85d2d3c77c9ee15d905cb1bdf7d5a64989142752d44b5eeb0
--> c9b71cb635aa8aac7318b7e9e64685d6454f3de89cad79f99d1ac5f75810e00a
STEP 8: FROM debian:stretch
STEP 9: ENV LANG            C.UTF-8
--> Using cache 73c7282f117c4af0d3eb21eb995a0aea33136a2652e6d0651b9771a0c6b6e5f9
STEP 10: FROM 73c7282f117c4af0d3eb21eb995a0aea33136a2652e6d0651b9771a0c6b6e5f9
STEP 11: RUN apt-get update &&     apt-get install -y --no-install-recommends libgmp10
--> Using cache 769fe1804b6a0afcab3919d955be86926af1656604fe95fb93478835e9ef3d7c
STEP 12: FROM 769fe1804b6a0afcab3919d955be86926af1656604fe95fb93478835e9ef3d7c
STEP 13: COPY --from=builder /root/.local/bin/laser-egg /usr/bin/laser-egg
Error: error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LANG=C.UTF-8] Command:copy Args:[/root/.local/bin/laser-egg /usr/bin/laser-egg] Flags:[--from=builder] Attrs:map[] Message:COPY --from=builder /root/.local/bin/laser-egg /usr/bin/laser-egg Original:COPY --from=builder /root/.local/bin/laser-egg /usr/bin/laser-egg}: no files found matching "/home/arun/.local/share/containers/storage/overlay/6c4c42ae1b2e264ad337bbf00a01cea677c572828ff6c2bd8dfa6e5c946b5ea7/merged/root/.local/bin/laser-egg": no such file or directory
```

**Describe the results you expected:**

The expectation is that the cached image from the end of the previous `FROM` section be used.

**Additional information you deem important (e.g. issue happens only occasionally):**

The problem seems to be that the wrong image is substituted in the second `FROM ...` section.

**Output of `podman version`:**

```
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12
  podman version: 1.2.0
host:
  BuildahVersion: 1.7.2
  Conmon:
    package: podman-1.2.0-2.git3bd528e.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: a13eadcaf0f07ba590c96d845a03ac3a0da7c56d'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 12337438720
  MemTotal: 33335652352
  OCIRuntime:
    package: runc-1.0.0-92.dev.gitc1b8c57.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc7+dev
      commit: d38f8a2d00ff444e52d16ab1ea5bbe5c1cb471e8
      spec: 1.0.1-dev
  SwapFree: 16738152448
  SwapTotal: 16739463168
  arch: amd64
  cpus: 8
  hostname: stillness
  kernel: 5.0.13-300.fc30.x86_64
  os: linux
  rootless: true
  uptime: 20h 38m 12.79s (Approximately 0.83 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/arun/.config/containers/storage.conf
  ContainerStore:
    number: 11
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/arun/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 11
  RunRoot: /tmp/1000
  VolumePath: /home/arun/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment] 2019-05-13 18:57
@TomSweeneyRedHat PTAL

**Comment by yann-soubeyrand** [comment] 2019-06-04 16:03
Hi,

Here is a minimal Dockerfile with instructions to reproduce the bug:
```
FROM fedora as builder

RUN mkdir -p /dir1/dir2 && touch /dir1/dir2/file1 /dir1/dir2/file2 /dir1/dir2/file3

FROM fedora

RUN mkdir /dir1
COPY --from=builder /dir1 /dir1/
```

`podman build --no-cache -t test .`
```
STEP 1: FROM fedora AS builder
STEP 2: RUN mkdir -p /dir1/dir2 && touch /dir1/dir2/file1 /dir1/dir2/file2 /dir1/dir2/file3
--> 11b715ed9fdac79ce12bc426181ad38536bd3acfb5b00c842d66d133a77987c2
STEP 3: FROM fedora
STEP 4: RUN mkdir /dir1
--> 936161aab1fd8c3eb6dbe66c21a271a8ba6c9d2990c87fad0dbf12b5a74c9c7f
STEP 5: COPY --from=builder /dir1 /dir1/
STEP 6: COMMIT test
--> ad3ebfbad62f7ee5f42012974d793821a30b50fc1e2d0e75875c9511347f6c8c
```

`podman run -ti test /bin/ls /dir1/dir2`
```
file1  file2  file3
```

`podman build -t test .`
```
STEP 1: FROM fedora AS builder
STEP 2: RUN mkdir -p /dir1/dir2 && touch /dir1/dir2/file1 /dir1/dir2/file2 /dir1/dir2/file3
--> Using cache d716810b7e7ddfa927610db4b00801d7952ed7c070090fe4251d9cf202bf8ac0
STEP 3: FROM fedora
STEP 4: RUN mkdir /dir1
--> Using cache 5255c4dd19660c1e6ba6c3b93ce35ac362ba097123ae02399d269a7ef64d2326
STEP 5: COPY --from=builder /dir1 /dir1/
Error: error building at STEP "COPY --from=builder /dir1 /dir1/": no files found matching "/var/home/yann/.local/share/containers/storage/overlay/fb446028084dbab62b8f0b6eb4e5dafb7a737c77ea36a842cd27cf46074108b6/merged/dir1": no such file or directory
```

**Comment by mheon** [comment] 2019-06-04 16:23
Thanks - that should help a lot!

**Comment by rhatdan** [comment] 2019-08-05 20:34
@TomSweeneyRedHat @QiWang19 PTAL

**Comment by QiWang19** [comment] 2019-08-08 15:18
I tries the above minimal Dockerfile, looks like we have fixed this problem. 
```
podman version 1.4.5-dev
BuildahVersion: 1.9.2
```
```
$ podman build --no-cache -t test -f Dockerfile.cache .
STEP 1: FROM fedora AS builder
STEP 2: RUN mkdir -p /dir1/dir2 && touch /dir1/dir2/file1 /dir1/dir2/file2 /dir1/dir2/file3
709d6353b83eab333f4460f276afb3c22c382cd59f2b71c64236b0bf812d33d6
STEP 3: FROM fedora
STEP 4: RUN mkdir /dir1
52404a945ec68daa758f5ad720a951321d5379c84b64b7dd0f03319eedb39c38
STEP 5: COPY --from=builder /dir1 /dir1/
STEP 6: COMMIT test
60c4aec0288dce05215b3c70c751efbce0583085a5375afa8711870e1fe86240


$ podman build -t test -f Dockerfile.cache .
STEP 1: FROM fedora AS builder
STEP 2: RUN mkdir -p /dir1/dir2 && touch /dir1/dir2/file1 /dir1/dir2/file2 /dir1/dir2/file3
--> Using cache 709d6353b83eab333f4460f276afb3c22c382cd59f2b71c64236b0bf812d33d6
STEP 3: FROM fedora
STEP 4: RUN mkdir /dir1
--> Using cache 52404a945ec68daa758f5ad720a951321d5379c84b64b7dd0f03319eedb39c38
STEP 5: COPY --from=builder /dir1 /dir1/
--> Using cache 60c4aec0288dce05215b3c70c751efbce0583085a5375afa8711870e1fe86240
STEP 6: COMMIT test
60c4aec0288dce05215b3c70c751efbce0583085a5375afa8711870e1fe86240
$ podman run -ti test /bin/ls /dir1/dir2
file1  file2  file3
```

**Comment by jbauers** [comment] 2019-09-07 07:16
Hey, I don't believe this is fully fixed. Please consider the following slightly adjusted Dockerfile (copying a specific file instead of dir):

```
FROM fedora as builder

RUN mkdir -p /dir1/dir2 && touch /dir1/dir2/file1 /dir1/dir2/file2 /dir1/dir2/file3

FROM fedora

RUN mkdir /dir1
COPY --from=builder /dir1/dir2/file1 /dir1/
```
```
╰─ docker build .
STEP 1: FROM fedora AS builder
STEP 2: RUN mkdir -p /dir1/dir2 && touch /dir1/dir2/file1 /dir1/dir2/file2 /dir1/dir2/file3
--> Using cache e7688a1b901697667da1b6b8eaaedfe8d607f17a5e2784bd28435700ccb6d72c
STEP 3: FROM fedora
STEP 4: RUN mkdir /dir1
--> Using cache c833352cb84fb7d58783327ea7d9b3677c437a86314586c710a9372b9bf4eda7
STEP 5: COPY --from=builder /dir1/dir2/file1 /dir1/
Error: error building at STEP "COPY --from=builder /dir1/dir2/file1 /dir1/": no files found matching "/home/jbauers/.local/share/containers/storage/overlay/3decf905202817b53228c65972d14070e165e8a0c7ae7e576d8ecfec2694e8b1/merged/dir1/dir2/file1": no such file or directory
```
```
╰─ podman version
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

Thanks!

**Comment by yann-soubeyrand** [comment] 2019-09-07 09:28
I confirm: I can reproduce the bug ;-)

**Comment by TomSweeneyRedHat** [comment] 2019-09-07 13:26
Thanks for the reproducer, we'll take another look.  @qiwang17 can you give the new Dockerfile a run through please?

**Comment by TomSweeneyRedHat** [comment] 2019-09-07 13:26
I'll try tagging the right Qi this time.   @QiWang19

**Comment by QiWang19** [comment] 2019-09-11 14:59
in podman 1.5.1 I see the error after I change the line `COPY --from=builder /dir1/dir2/file1 /dir1/` of the Dockerfile. But I can't regenerate this error with master branch podman or buildah.

  podman 1.5.1 build use same Dockerfile twice, cache works

```
// podman 1.5.1
$ podman build .
STEP 1: FROM fedora AS builder
STEP 2: RUN mkdir -p /dir1/dir2 && touch /dir1/dir2/file1 /dir1/dir2/file2 /dir1/dir2/file3
--> Using cache fb3f2e4ac0379f8b929b7b3a141fb019904d3f2e85b8641ada9bca2170077f05
STEP 3: FROM fedora
STEP 4: RUN mkdir /dir1
--> Using cache 8736da636d35ba9b0e12bf69b8b62a8308e7aae9a66b196d3adc8b62e6e887ad
STEP 5: COPY --from=builder /dir1/dir2/file1 /dir1/
--> Using cache 89f6e0c69ec57f50651bff17c1bb9ea973365e075583d45639a1f689a225cd00
```
change the Dockerfile COPY --from=builder /dir1/dir2/file1 to COPY --from=builder /dir1/dir2/file2
```
// podman 1.5.1
$ podman build .
STEP 1: FROM fedora AS builder
STEP 2: RUN mkdir -p /dir1/dir2 && touch /dir1/dir2/file1 /dir1/dir2/file2 /dir1/dir2/file3
--> Using cache 269c22ca168a583e5dc051ab13abdf6f0ab41eed483c9ef5603837d2a6a28b6c
STEP 3: FROM fedora
STEP 4: RUN mkdir /dir1
--> Using cache 6349f9cee535bfd1fe9d88b6e81deba877f2ff3f09f24937db156109e1a13d9d
STEP 5: COPY --from=builder /dir1/dir2/file2 /dir1/
Error: error building at STEP "COPY --from=builder /dir1/dir2/file2 /dir1/": no files found matching "/home/qiwan/.local/share/containers/storage/overlay/2748053c79264ecc8aa37319045385fc894a1f31aa8938ae507d0c3c0313e739/merged/dir1/dir2/file2": no such file or directory
```

**Comment by mheon** [comment] 2019-10-24 17:41
@TomSweeneyRedHat @QiWang19 Is this fixed? I know we've had a few Buildah revendors since

**Comment by rhatdan** [comment] 2019-10-24 19:23
Lets marked this as fixed.  Reopen if I am mistaken.

**Closed by rhatdan** 2019-10-24 19:23 UTC
Labels: kind/bug

**Comment by TomSweeneyRedHat** [comment] 2019-10-24 20:29
@rhatdan, just confirmed that it's fixed in at least upstream, and I believe Podman v1.6.2
