### ISSUE TITLE
systemd --user session broken in fedora:31 container

### ISSUE THREAD

**Issue by paravz** [containers/libpod#4446] opened 2019-11-05 06:59 UTC
/kind bug

**Description**
"Interactive" sessions broken for users inside of Fedora 31 NON-privileged systemd container:
  - systemd-logind doesn't start
  - any user auth takes ~25 seconds, including su, sudo, etc

This might be a fedora31/systemd-243 issue, since on the same host, fedora30 container works as expected (since https://github.com/containers/libpod/issues/3459 was fixed)

**Steps to reproduce the issue:**
1. $ sudo podman rm -vf sysuser; sudo podman run -it -d --name sysuser fedora:31 /sbin/init
2. $ sudo podman exec -it sysuser bash -c "systemctl unmask systemd-logind --now; useradd user; systemctl restart systemd-logind; systemctl status -l --all systemd-logind"
```
Removed /etc/systemd/system/systemd-logind.service.
Job for systemd-logind.service failed because the control process exited with error code.
See "systemctl status systemd-logind.service" and "journalctl -xe" for details.
● systemd-logind.service - Login Service
   Loaded: loaded (/usr/lib/systemd/system/systemd-logind.service; static; vendor preset: disabled)
   Active: activating (start) since Tue 2019-11-05 06:51:55 UTC; 4ms ago
     Docs: man:systemd-logind.service(8)
           man:logind.conf(5)
           https://www.freedesktop.org/wiki/Software/systemd/logind
           https://www.freedesktop.org/wiki/Software/systemd/multiseat
  Process: 66 ExecStartPre=/sbin/modprobe -abq drm (code=exited, status=226/NAMESPACE)
 Main PID: 67 ((d-logind))
   CGroup: /machine.slice/libpod-a4daeae644a6e856663ff0bf2dc9626f68cb9fc43b3e966d5afb2d6704e2216a.scope/system.slice/systemd-logind.service

Nov 05 06:51:55 a4daeae644a6 systemd[1]: Starting Login Service...
Nov 05 06:51:55 a4daeae644a6 systemd[1]: systemd-logind.service: Main process exited, code=exited, status=226/NAMESPACE
Nov 05 06:51:55 a4daeae644a6 systemd[1]: systemd-logind.service: Failed with result 'exit-code'.
Nov 05 06:51:55 a4daeae644a6 systemd[1]: Failed to start Login Service.
Nov 05 06:51:55 a4daeae644a6 systemd[1]: systemd-logind.service: Service has no hold-off time (RestartSec=0), scheduling restart.
Nov 05 06:51:55 a4daeae644a6 systemd[1]: systemd-logind.service: Scheduled restart job, restart counter is at 3.
Nov 05 06:51:55 a4daeae644a6 systemd[1]: Stopped Login Service.
Error: non zero exit code: 3: OCI runtime error
```

3. $ time sudo podman exec -it sysuser su - user -c 'bash -c "id"'
```
uid=1000(user) gid=1000(user) groups=1000(user)

real    0m25.401s
user    0m0.079s
sys     0m0.053s
```

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.12.10
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.10
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.2-1.fc30.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: a89d21975ee86e84e0b0e1c0f887687582f4b0e3'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 23454625792
  MemTotal: 33205600256
  OCIRuntime:
    name: runc
    package: runc-1.0.0-95.rc9.gitc1485a1.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9+dev
      commit: 0840802d505e28d3adcbc7a275cbeadbdf64ddec
      spec: 1.0.1-dev
  SwapFree: 6211760128
  SwapTotal: 6211760128
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: localhost
  kernel: 5.3.7-200.fc30.x86_64
  os: linux
  rootless: false
  uptime: 49m 44.22s
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 8
  GraphDriverName: overlay
  GraphOptions:
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 171
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc30.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by giuseppe** [comment] 2019-11-05 11:08
that looks like a change in systemd, I can confirm `fedora:30` works fine for me as well on a Fedora 31 host with cgroups v2 enabled while `fedora:31` fails with the same error message:

```
Nov 05 11:05:26 68720cac239e systemd[57]: systemd-logind.service: Failed at step NAMESPACE spawning /usr/lib/systemd/systemd-logind: Operation not supported

```

Could you file an issue with systemd?

**Comment by giuseppe** [comment] 2019-11-06 11:08
thanks!  Since there is systemd issue to track the regression, I am going to close this.

**Closed by giuseppe** 2019-11-06 11:08 UTC
Labels: kind/bug
