### ISSUE TITLE
podman does not resolve short hostname in image name

### ISSUE THREAD

**Issue by lfarkas** [containers/libpod#4954] opened 2020-01-23 15:15 UTC
we try to run our own local registry and refer to the image as registry/repo/image but podman doesn't able to resolve it only FQDN ie. in this case search for images in the global registry list. the strange thing is that:
- registry/repo/image can NOT be used
- registry:80/repo/image can be used 
- registry:443/repo/image can be used 

it seems that the first format assume it's a path element while all other case knows it's a hostname reference. i'm not able to find any doc about the hostname part.
so is there any way to use short hostname in an image name?

**Comment by baude** [comment] 2020-01-26 18:16
@lfarkas short names are used all the time.  can you give a real world example and maybe someone can debug

**Comment by lfarkas** [comment] 2020-01-26 23:02
- setup a repo which is NOT in the /etc/containers/registries.conf's registries.search
- put an image into the new registries repo/image
- podman pull registry/repo/image

**Comment by baude** [comment] 2020-01-27 14:44
@mtrmac wdyt here? one thing we dont try when resolving names is to flat out try a pull.  That might fix this one?

**Comment by mtrmac** [comment] 2020-01-27 15:09
No, this is working as designed, and is pretty much the opposite to resolving short names.

"registry/" which has neither a dot nor a colon, and is not `localhost`, is treated as a repository, not as a hostname, i.e. this is defined to be a short name.

At upstream Docker, `docker pull registry/repo/image` would always pull `docker.io/registry/repo/image`.

---

I would strongly suggest _not_ using the DNS search mechanism to use short registry names, primarily because that mechanism is completely invisible to the rest of the stack, notably credentials are then stored under a `registry` (not `registry.fully.qualified`) key in configuration files, and could easily be confused with credentials from other networks.

(This is not an issue with search, because when searching for "fedora" at "registry.fedoraproject.org/fedora" the code will look for credentials of "registry.fedoraproject.org".)

---

Independently of that, WRT extending the search mechanism to look in one more location: that _definitely_ should not happen silently/by default (consider the recent name squatting discussions), and even if explicitly opted in somehow I’d rather not suggest relying on DNS search, see above.

**Comment by baude** [comment] 2020-01-27 15:18
thanks @mtrmac !

**Comment by rhatdan** [comment] 2020-01-28 15:58
I am going to close this issue, as I believe from the discussion this is not a bug.  Reopen if you disagree.

**Closed by rhatdan** 2020-01-28 15:58 UTC
Labels: kind/bug
