### ISSUE TITLE
'cannot setfilecon_raw' when pushing Alpine image to OSTree repo

### ISSUE THREAD

**Issue by refi64** [containers/libpod#3202] opened 2019-05-24 19:03 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Pushing to an OSTree repo fails with "cannot setfilecon_raw" errors.

**Steps to reproduce the issue:**

1. Create a new ostree repo, e.g. `ostree init --repo=repo --mode=archive`.

2. Try pushing an image to it, e.g. `podman push alpine:latest ostree:alpine:latest@$PWD/repo`.

**Describe the results you received:**

```
$ podman push alpine:latest ostree:alpine:latest@$PWD/repo2
Getting image source signatures
Copying blob bcf2f368fe23 done
Copying config 5cb3aa00f8 done
Writing manifest to image destination
Storing signatures
Error: Error copying image to the remote destination: Error committing the finished image: cannot setfilecon_raw /tmp/alpine_3Alatest/bcf2f368fe234217249e00ad9d762d8f1a3156d60c442ed92079fa5b120634a1/root/sbin/depmod: invalid argument
```

**Describe the results you expected:**

It to work :rofl:

**Additional information you deem important (e.g. issue happens only occasionally):**

Thus far I can only reproduce this with Alpine, e.g. `debian:9-slim` works.

**Output of `podman version`:**

```
Version:            1.3.1
RemoteAPI Version:  1
Go Version:         go1.12.2
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.2
  podman version: 1.3.1
host:
  BuildahVersion: 1.8.2
  Conmon:
    package: podman-1.3.1-1.git7210727.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: c9a4c48d1bff85033b7fc9b62d25961dd5048689'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 541032448
  MemTotal: 8222687232
  OCIRuntime:
    package: runc-1.0.0-92.dev.gitc1b8c57.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc7+dev
      commit: d38f8a2d00ff444e52d16ab1ea5bbe5c1cb471e8
      spec: 1.0.1-dev
  SwapFree: 8049897472
  SwapTotal: 8359243776
  arch: amd64
  cpus: 4
  hostname: fedora.refi64.com
  kernel: 5.0.16-300.fc30.x86_64
  os: linux
  rootless: true
  uptime: 27h 3m 47.7s (Approximately 1.12 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/ryan/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/ryan/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 51
  RunRoot: /run/user/1000
  VolumePath: /var/home/ryan/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on Fedora Silverblue 30.

**Comment by rhatdan** [comment] 2019-05-25 11:07
Is SELinux enabled on this machine?
Any avc messages?
ausearch -m avc -ts recent

**Comment by giuseppe** [comment] 2019-05-28 07:31
what is your use case for using the ostree backend?  We are planning on disabling it in podman, as it is out of scope since you cannot run containers from there

**Comment by refi64** [comment] 2019-05-28 20:12
@rhatdan SELinux is set to permissive.
@giuseppe I was using it to [push containers to OSTree repos so I could run them as Flatpaks](https://github.com/refi64/flatpod), IIRC there's some existing skopeo bug where you can't easily access the user OCI storage (though it may have since been fixed maybe?).

**Comment by giuseppe** [comment] 2019-05-28 20:42
> @giuseppe I was using it to [push containers to OSTree repos so I could run them as Flatpaks](https://github.com/refi64/flatpod)

that is a really nice project!

From the code https://github.com/fedora-selinux/selinux/blob/master/libselinux/src/lsetfilecon.c#L14 it seems like the only way it returns `EINVAL` is with an empty context.

I cannot reproduce on F30, what do you get with:

`selabel_lookup -r -v -b file -k /sbin/depmod` ?

**Comment by rhatdan** [comment] 2019-05-28 21:19
No I think the kernel could return EINVAL, if the label that you are attempting to set does not exists in the policy loaded into the kernel.

setenforce 1
 chcon -t foo_t /etc/passwd
chcon: failed to change context of '/etc/passwd' to ‘system_u:object_r:foo_t:s0’: Invalid argument

strace shows
setxattr("/etc/passwd", "security.selinux", "system_u:object_r:foo_t:s0", 27, 0) = -1 EINVAL (Invalid argument)

**Comment by rhatdan** [comment] 2019-05-28 21:21
```
# echo "foo_t" > /proc/self/attr/fscreate 
sh: echo: write error: Invalid argument
# setenforce 0
# echo "foo_t" > /proc/self/attr/fscreate 
#2986  
```

**Comment by giuseppe** [comment] 2019-06-13 14:05
opened a PR here: https://github.com/containers/image/pull/640

**Comment by rhatdan** [comment] 2019-06-13 15:17
What label is attempting to be set?

**Comment by giuseppe** [comment] 2019-06-13 15:21
it is not clear from the debug messages we have, but it fails trying to set the label for `/root/sbin/depmod`.

**Comment by giuseppe** [comment] 2019-06-13 15:54
I've tried different combinations of images, but I wasn't able to reproduce it

**Comment by giuseppe** [comment] 2019-06-13 20:41
I am unable to reproduce, I've opened a PR to make the error clearer so we can see what context it tries to set (https://github.com/containers/image/pull/644)

@refi64 please reopen if you have a reproducer or more information about it

**Closed by giuseppe** 2019-06-13 20:41 UTC
Labels: kind/bug

**Comment by refi64** [comment] 2019-06-14 03:28
I can definitely still reproduce, I'll try to use it with that other branch to see if I can get some more info on it. :/

**Comment by giuseppe** [comment] 2019-06-14 08:59
can you tell me what do you get with the command: `selabel_lookup -r -v -b file -k /sbin/depmod` ?

**Comment by giuseppe** [comment] 2019-06-14 10:12
I've also tried on Silverblue:
```
$ rpm-ostree status
● ostree://fedora:fedora/30/x86_64/silverblue
                   Version: 30.20190614.0 (2019-06-14T00:36:58Z)
                    Commit: 588122e66ad0f5ef8ab0210a016883263ca6f0ab23427e3827c9492170ac1856
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
....
$ ostree init --repo=repo --mode=archive
$ podman pull alpine
$ podman push alpine:latest ostree:alpine:latest@$PWD/repo
Getting image source signatures
Copying blob f1b5933fe4b5 done
Copying config 055936d392 done
Writing manifest to image destination
Storing signatures
$
```
I've tried as root as well but no difference.
