### ISSUE TITLE
standard_init_linux.go:203: exec user process caused \"no such file or directory\"

### ISSUE THREAD

**Issue by cjeanner** [containers/libpod#1844] opened 2018-11-21 12:57 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

[//]: # Uncomment only one, leave it on its own line:

# **kind bug**

[//]: # **kind feature**

**Description**

From time to time, we hit this uncommon issue while running a ```podman run``` command.

**Steps to reproduce the issue:**

1. It's a random failure, no reproducer. yay.

2.

3.

**Describe the results you received:**
From time to time, it fails running a container

**Describe the results you expected:**
Well. It should run the container ;).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.11.1.1
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.11.1.1-3.git594495d.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: ccde1bf8e093607ecf92b404368033f645cad755-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 874045440
  MemTotal: 8365137920
  OCIRuntime:
    package: runc-1.0.0-55.dev.git2abd837.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 8557686784
  SwapTotal: 8588881920
  arch: amd64
  cpus: 8
  hostname: undercloud.localdomain
  kernel: 3.10.0-862.14.4.el7.x86_64
  os: linux
  rootless: false
  uptime: 59m 56.33s
insecure registries:
  registries:
  - 192.168.24.1:8787
  - 192.168.24.3:8787
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 19
  RunRoot: /var/run/containers/storage

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment] 2018-11-21 13:02
I'll double-check, but both these bugs seem to be coming out of runc, and
seem to be related to not being able to read files. The cgroup one could
theoretically be on the host, but this one is definitely trying to read
something in the container (the program specified in the container command).

Brent initially mentioned that this could be a result of the container not
mounting properly. I'm beginning to agree with him - this seems like
something weird is happening (intermittently) with storage

**Comment by EmilienM** [comment] 2018-11-21 13:03
A bit more details:

The container that causes problem:
2018-11-19 21:42:01 | "Error running ['podman', 'run', '--name', 'nova_wait_for_db_sync', '--label', 'config_id=tripleo_step3', '--label', 'container_name=nova_wait_for_db_sync', '--label', 'managed_by=paunch', '--label', 'config_data={\"command\": \"/docker-config-scripts/nova_wait_for_db_sync.py\", \"detach\": false, \"image\": \"docker.io/tripleomaster/centos-binary-nova-placement-api:3ed8ac0e93367a02ad53d9fa93467057724b6621_fd8eb74b\", \"net\": \"host\", \"privileged\": false, \"start_order\": 1, \"user\": \"root\", \"volumes\": [\"/var/lib/nova:/var/lib/nova:shared\", \"/var/lib/docker-config-scripts/:/docker-config-scripts/\", \"/var/lib/config-data/puppet-generated/nova_placement/etc/nova:/etc/nova:ro\"]}', '--net=host', '--privileged=false', '--user=root', '--volume=/var/lib/nova:/var/lib/nova:shared', '--volume=/var/lib/docker-config-scripts/:/docker-config-scripts/', '--volume=/var/lib/config-data/puppet-generated/nova_placement/etc/nova:/etc/nova:ro', 'docker.io/tripleomaster/centos-binary-nova-placement-api:3ed8ac0e93367a02ad53d9fa93467057724b6621_fd8eb74b', '/docker-config-scripts/nova_wait_for_db_sync.py']. [1]",
2018-11-19 21:42:01 | "stderr: standard_init_linux.go:203: exec user process caused \"no such file or directory\"",

logstash query for this error: http://logstash.openstack.org/#dashboard/file/logstash.json?query=message%3A%5C%22exec%20user%20process%20caused%5C%22%20AND%20message%3A%5C%22no%20such%20file%20or%20directory%5C%22 which means we hit this error since November 19th.

**Comment by giuseppe** [comment] 2018-11-21 13:37
who is creating the file `/docker-config-scripts/nova_wait_for_db_sync.py'?  Is it static or can it change while the container is creating/running?

**Comment by cjeanner** [comment] 2018-11-21 13:51
It's a static file, pushed before the container is started:
https://github.com/openstack/tripleo-heat-templates/blob/0561a3536a11975645f3b2371dfd458c6cbf179d/docker/services/nova-placement.yaml#L117-L120

**Comment by stuggi** [comment] 2018-11-21 13:52
> who is creating the file `/docker-config-scripts/nova_wait_for_db_sync.py'? Is it static or can it change while the container is creating/running?

nova_wait_for_db_sync.py is a static script which is part of the used volume '--volume=/var/lib/docker-config-scripts/:/docker-config-scripts/'

The config scripts get written to the node before they are used:

2018-11-19 21:31:07 | TASK [Write docker config scripts] *********************************************     
2018-11-19 21:31:08 | changed: [fedora-28-vexxhost-sjc1-0000573726] => (item=create_swift_secret.sh)
2018-11-19 21:31:08 | changed: [fedora-28-vexxhost-sjc1-0000573726] => (item=docker_puppet_apply.sh)       
2018-11-19 21:31:09 | changed: [fedora-28-vexxhost-sjc1-0000573726] => (item=neutron_ovs_agent_launcher.sh)
2018-11-19 21:31:09 | changed: [fedora-28-vexxhost-sjc1-0000573726] => (item=nova_api_discover_hosts.sh)   
2018-11-19 21:31:10 | changed: [fedora-28-vexxhost-sjc1-0000573726] => (item=nova_api_ensure_default_cell.sh)
2018-11-19 21:31:10 | changed: [fedora-28-vexxhost-sjc1-0000573726] => (item=nova_statedir_ownership.py)   
2018-11-19 21:31:10 | changed: [fedora-28-vexxhost-sjc1-0000573726] => (item=nova_wait_for_db_sync.py)     
2018-11-19 21:31:11 | changed: [fedora-28-vexxhost-sjc1-0000573726] => (item=pyshim.sh)                    
2018-11-19 21:31:11 | changed: [fedora-28-vexxhost-sjc1-0000573726] => (item=set_swift_keymaster_key_id.sh) 

2018-11-19 21:42:01 |         "Running container: nova_wait_for_db_sync",                                  
2018-11-19 21:42:01 |         "$ podman run --name nova_wait_for_db_sync --label config_id=tripleo_step3 --label container_name=nova_wait_for_db_sync --label managed_by=paunch --label config_data={\"command\": \"/docker-config-scripts/nova_wait_for_db_sync.py\", \"detach\": false, \"image\": \"docker.io/tripleomaster/centos-binary-nova-placement-api:3ed8ac0e93367a02ad53d9fa93467057724b6621_fd8eb74b\", \"net\": \"host\", \"privileged\": false, \"start_order\": 1, \"user\": \"root\", \"volumes\": [\"/var/lib/nova:/var/lib/nova:shared\", \"/var/lib/docker-config-scripts/:/docker-config-scripts/\", \"/var/lib/config-data/puppet-generated/nova_placement/etc/nova:/etc/nova:ro\"]} --net=host --privileged=false --user=root --volume=/var/lib/nova:/var/lib/nova:shared --volume=/var/lib/docker-config-scripts/:/docker-config-scripts/ --volume=/var/lib/config-data/puppet-generated/nova_placement/etc/nova:/etc/nova:ro docker.io/tripleomaster/centos-binary-nova-placement-api:3ed8ac0e93367a02ad53d9fa93467057724b6621_fd8eb74b /docker-config-scripts/nova_wait_for_db_sync.py",

**Comment by rhatdan** [comment] 2018-11-21 16:00
Could things be umounted before runc runs?  if you had a race between podman run and podman umount this could happen?

**Comment by mheon** [comment] 2018-11-21 16:05
@rhatdan The code to prevent unmount while c.state.Mounted is set should prevent that from happening - let me verify

**Comment by EmilienM** [comment] 2018-11-22 16:50
@giuseppe pointed me out that it also fails the same way with Docker:
http://logs.openstack.org/98/619598/3/check/tripleo-ci-fedora-28-standalone-docker/b3b6940/logs/undercloud/var/log/extra/errors.txt

So at this point I wouldn't spend much time on it for now, it's probably something on our side and we'll keep looking.

**Comment by giuseppe** [comment] 2018-11-23 08:47
I am going to close this issue for now, since it happens also with Docker.  Most likely the problem is somewhere else.

Let's reopen it if it needs more investigation in podman.

**Comment by EmilienM** [comment] 2018-12-19 21:17
@giuseppe please re-open, we can still see this one with podman 0.12:

```standard_init_linux.go:203: exec user process caused \"no such file or directory\"", ```

http://logs.openstack.org/03/625903/2/gate/tripleo-ci-centos-7-containers-multinode/23f5730/logs/undercloud/home/zuul/undercloud_install.log.txt.gz#_2018-12-19_20_05_52

**Comment by EmilienM** [comment] 2018-12-19 21:17
@mheon @baude @rhatdan @cjeanner FYI ^

**Comment by EmilienM** [comment] 2019-01-02 13:59
We still have the issue at this time, looking at our [kibana](http://logstash.openstack.org/#dashboard/file/logstash.json?query=build_name%3A%20*tripleo-ci*%20AND%20build_status%3A%20FAILURE%20AND%20message%3A%20%5C%22exec%20user%20process%20caused%5C%22):
![logstash-podman](http://my1.fr/files/logstash-podman.png)


+ podman version
Version:       0.12.1.2
Go Version:    go1.10.2
OS/Arch:       linux/amd64


+ podman info
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.2-2.git9551f6b.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 97d5f1232f62307696c8b4b2d430e8b771a45873-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 1249722368
  MemTotal: 8369278976
  OCIRuntime:
    package: runc-1.0.0-57.dev.git2abd837.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 8589930496
  SwapTotal: 8589930496
  arch: amd64
  cpus: 8
  hostname: centos-7-inap-mtl01-0001426023
  kernel: 3.10.0-957.1.3.el7.x86_64
  os: linux
  rootless: false
  uptime: 1h 29m 13.69s (Approximately 0.04 days)
insecure registries:
  registries:
  - 192.168.24.1:8787
registries:
  registries:
  - registry.centos.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 14
  RunRoot: /var/run/containers/storage

We couldn't reproduce the error with Docker, but only Podman. I'll comment if I have further findings.

**Comment by mheon** [comment] 2019-01-02 14:35
This is definitely a runc error, telling us that the entrypoint binary for the container doesn't exist.

If it works on Docker, it's most likely part of how we assemble container entrypoint - perhaps we're doing something differently that results in us generating a different path than Docker?

**Comment by mheon** [comment] 2019-01-02 14:38
It's always docker-puppet.py

I think we need to figure out where that lives in the image, and figure out why Podman isn't finding it properly.

**Comment by EmilienM** [comment] 2019-01-02 16:39
@mheon how do you know it's docker-puppet.py?
The container options are:
``--volume /var/lib/docker-puppet/docker-puppet.sh:/var/lib/docker-puppet/docker-puppet.sh:rw,z --security-opt label=disable --entrypoint /var/lib/docker-puppet/docker-puppet.sh``

I suspect it's ``/var/lib/docker-puppet/docker-puppet.sh`` which contains this code:
https://github.com/openstack/tripleo-heat-templates/blob/beb8ae7dd53c7b36313956c4ea847f487199468e/docker/docker-puppet.py#L260-L371

There is something in that snippet that doesn't run fine, I think. I'm digging.

**Comment by EmilienM** [comment] 2019-01-02 16:50
@mheon while I keep debugging myself, how could we know which directory isn't found by runc or podman? I wish I could strace it but it's happening randomly in CI and I can't reproduce it for now.

**Comment by EmilienM** [comment] 2019-01-02 16:58
My first feeling is that there is a race when your entrypoint is bind-mounted from the host.

**Comment by EmilienM** [comment] 2019-01-02 18:06
FTR https://github.com/containers/libpod/pull/2068 can help with logging.

**Comment by cjeanner** [comment] 2019-01-03 08:01
@EmilienM hmmm I don't think so. According to the [runc code involved](https://github.com/opencontainers/runc/blob/master/libcontainer/standard_init_linux.go), if it was due to a missing entrypoint, it would fail earlier, something around [line 174](https://github.com/opencontainers/runc/blob/master/libcontainer/standard_init_linux.go#L174-L177) instead of the current line 203.

[L203](https://github.com/opencontainers/runc/blob/master/libcontainer/standard_init_linux.go#L203) seems to point to some Seccomp issue instead... Deeper in runc/podman?

**Comment by cjeanner** [comment] 2019-01-03 08:59
Small steps:
when we have a missing ```--entrypoint foo.sh```, we have another error:
```
podman run --volume $(pwd)/entry.sh:/entry.s --entrypoint /entry.sh alpine
container create failed: container_linux.go:344: starting container process caused "exec: \"/entry.sh\": stat /entry.sh: no such file or directory"
: internal libpod error
```

If we don't have the file on disk, podman itself returns an error:
```
podman run --volume $(pwd)/entry.s:/entry.sh --entrypoint /entry.sh alpine
error checking path "/root/entry.s": stat /root/entry.s: no such file or directory
```

So it's really, really strange. And the line 203 involves "seccomp init" message, NOT "exec user process" :(.

**Comment by mheon** [comment] 2019-01-03 15:08
This is definitely the `syscall.Exec()` at the very end of the Linux init code.

Per the manpage for `execve` - `The file filename or a script or ELF interpreter does not exist, or a shared library needed for file or interpreter cannot be found. `

Could we be missing a library necessary to run the script?

**Comment by cevich** [comment] 2019-01-03 15:43
This couldn't be at all related to the occasional fail we see from python tests where the cgroup mount isn't there (for some/whatever reason)?

**Comment by EmilienM** [comment] 2019-01-04 13:46
@giuseppe 

So mount ordering: https://review.openstack.org/628441 (let's see if that actually helps).
As for the dcmd, we already print it in debug mode:

```log.debug('Running %s command: %s' % (container_cli, ' '.join(dcmd)))```
I'll run in --debug to show you the command.

**Comment by rhatdan** [comment] 2019-01-04 13:50
I know in podman we sort the volume mounts to make sure that no volume mount ever mounts over another.

**Comment by EmilienM** [comment] 2019-01-04 13:51
@rhatdan in other words... CLI order doesn't matter?

**Comment by EmilienM** [comment] 2019-01-04 14:00
also, could we update runc vendoring in libpod? maybe it would help? I've seen some missing bug fixes that could eventually fix our problem.

**Comment by mheon** [comment] 2019-01-04 14:49
@EmilienM CLI order shouldn't matter - we sort the mounts first to make sure they apply in a sane order.

Of course, that's not a hard guarantee (our sort code could be buggy), but I don't know if that causes our issue where stat succeeds but exec fails

**Comment by EmilienM** [comment] 2019-01-08 14:11
@mheon @rhatdan we still have this bug, despite the ordering change and also the mount in read-only:
https://review.openstack.org/#/c/628376/
https://review.openstack.org/#/c/628441/

It still affects our CI, I think we still need help for this one.

**Comment by EmilienM** [comment] 2019-01-08 17:42
@giuseppe @mheon more logs, with lot of details:

https://paste.fedoraproject.org/paste/EIXGr2dMeWjO4fKqqD69qg/

**Comment by EmilienM** [comment] 2019-01-09 02:58
I can finally provide more debug:
https://logs.rdoproject.org/81/628381/4/openstack-check/tripleo-ci-centos-7-ovb-3ctlr_1comp-featureset035/3c233ba/logs/undercloud/home/zuul/undercloud_install.log.txt.gz#_2019-01-08_23_15_19

I've noticed that some output was shown where only some parts of the script was there. I wondered if maybe the script would be re-written while bind mounted somewhere so I went ahead and proposed that we don't touch the script if already exist: https://review.openstack.org/629371

However, I'm not sure it'll be useful as I think the script isn't modified once we run the podman commands.
Anyway, we'll see what our CI says with this patch, probably tomorrow morning.

**Comment by giuseppe** [comment] 2019-01-09 07:52
> I've noticed that some output was shown where only some parts of the script was there. I wondered if maybe the script would be re-written while bind mounted somewhere so I went ahead and proposed that we don't touch the script if already exist: https://review.openstack.org/629371

I always assumed in this discussion that there is only one container running, and using that script.

Is it possible that the script can be executed multiple times on the same system (and at the same time)?

**Comment by EmilienM** [comment] 2019-01-09 13:49
I doubt the docker-puppet.py script itself is executed multiple times on the same host. However within this script we execute podman multiple times with concurrency.
I'm not convinced that https://review.openstack.org/629371 will actually help in this bug, however it can't hurt.

**Comment by giuseppe** [comment] 2019-01-09 14:03
could we use a temporary file instead so we are sure there are no other processes trying to use it?

**Comment by EmilienM** [comment] 2019-01-09 15:39
I'm trying again with disabling concurrency in our script that run multiple podman containers at the same time to configure our containers: https://review.openstack.org/629546

**Comment by EmilienM** [comment] 2019-01-10 20:12
I've been doing testing all day with disabled concurrency. Of course deployments took much longer but I've got zero hit for this bug... So I believe that running podman commands at the same time is still risky (lock issues?) and might cause some issues when the entrypoint is a bind-mounted script.

**Comment by mheon** [comment] 2019-01-10 20:14
Hm. I don't think we do any checks/locking on volumes.

Possible solution: mount the container, copy the bash script in, and then run it?

**Comment by cjeanner** [comment] 2019-01-11 07:33
@mheon uhu, I was thinking about such a solution. As a last resort though.

IIRC, there isn't any "podman copy", replaced in favour of
```Bash
ct_mount=$(podman mount <container>)
cp /foo ${ct_mount}/foo
podman umount <container>
```
right? Or is there now some internal wrapper for that? Care to list the steps just to be sure? :)

**Comment by EmilienM** [comment] 2019-01-11 12:57
@mheon We'll try your solution, @cjeanner is working on a patch. In the meantime, I'm proposing to disable concurrency on that script, which has proven to help after 3 days of heavy testing in our CI: https://review.openstack.org/629546

**Comment by bogdando** [comment] 2019-01-11 14:20
@mheon why would we want to have we any checks/locking on volumes mounted in :ro?

**Comment by EmilienM** [comment] 2019-01-11 21:56
@cjeanner another option is to retry the exec and keep concurrency. I'll try that out as well.

**Comment by EmilienM** [comment] 2019-01-11 22:06
With a ugly retry: https://review.openstack.org/#/c/614639/

**Comment by giuseppe** [comment] 2019-01-11 22:21
Could you use temporary files that are different for each run?  Then it should not matter how many containers run in parallel

**Comment by EmilienM** [comment] 2019-01-11 22:33
Yes we could, however the file is always the same.

Since the file is only used during config step, it wouldn't need to be
persistent so we can probably investigate using /tmp for that. I'll look
over the weekend.

---
Emilien Macchi

**Comment by EmilienM** [comment] 2019-01-14 12:31
Before I go write the code, here are 2 options (at least):

* Create docker-puppet-<container-name>.sh in /var/lib/docker (and we would end up with ~30 files which have the same content). Not a HUGE deal but still ugly from an engineering point of view.
* Create a tempfile, which should probably be fine since the entrypoint is only used when the containers are configured (aka puppet runs inside the container during the initial deployments or upgrades) so when the host reboots the files aren't there anymore but since entrypoint isn't used, it's ok.

I'll try option 2.

**Comment by EmilienM** [comment] 2019-01-16 09:09
@rhatdan @mheon @giuseppe 

until we find out more about this bug and what the root cause would be in libpod, we decided to go with an ugly workaround in our deployment, where we simply retry 3 times the ```podman run``` command during the configuration steps.

By adding the retry will:
* highly reduce the chances to hit this bug in our CI
* increase deployment time when the bug is hit during the retries
* log the retries and make them visible in logstash so we'll have more metrics on how much we still hit the bug.

@cjeanner is also working on a python implementation of "podman cp" in https://review.openstack.org/#/c/630287/ - it would be great to have this native feature in podman directly, as we are dealing with multi-threads etc.

Let's keep this issue open, as there is a bug somewhere and we seem to be alone hitting it so far.

**Comment by ssbarnea** [comment] 2019-01-16 10:30
I retry approach is acceptable and needed but we should also create an elastic-recheck query for measuring how often this happens and assure it will be fixed.

Look at https://review.openstack.org/#/c/619059/ and try to raise a similar one for this bug, add me as a reviewer. This will create a nice graph on http://status.openstack.org/elastic-recheck/

**Comment by giuseppe** [comment] 2019-01-16 10:39
> @cjeanner is also working on a python implementation of "podman cp" in https://review.openstack.org/#/c/630287/ - it would be great to have this native feature in podman directly, as we are dealing with multi-threads etc.

there is already a PR to add cp to podman: `https://github.com/containers/libpod/pull/2151`

**Comment by cjeanner** [comment] 2019-01-17 09:37
Hello there,

Sooooo. I now have a patch that push the entrypoint script in the container before starting it.
Basically, it does the following:
- creates the container with all the mounts, options and so on
- mounts that container, copies content, umounts it
- starts the container

And, well, it still fails randomly because it "doesn't find the script".

I've added a lot of debug, and here's what I get:
```
2019-01-17 08:58:30 |         "2019-01-17 08:56:48,287 INFO: 24656 -- podman: Creating container docker-puppet-zaqar",
2019-01-17 08:58:30 |         "1995372dae0aba414626cd6d79309fc80d189c69a5cc7276b6012b6d6ded66f4",
2019-01-17 08:58:30 |         "2019-01-17 08:56:48,619 INFO: 24657 -- podman: Pushing /var/lib/docker-puppet/docker-puppet.sh in container docker-puppet-mistral",
2019-01-17 08:58:30 |         "2019-01-17 08:56:49,149 INFO: 24657 -- docker-puppet-mistral: cp /var/lib/docker-puppet/docker-puppet.sh /var/lib/containers/storage/overlay/ee7b8a4c83e204b02e34db795e1ed7f531c879df528af486056c87c55aa86eb8/merged/var/lib/docker-puppet/docker-puppet.sh",
2019-01-17 08:58:30 |         "2019-01-17 08:56:49,162 INFO: 24657 -- Content of /var/lib/containers/storage/overlay/ee7b8a4c83e204b02e34db795e1ed7f531c879df528af486056c87c55aa86eb8/merged/var/lib/docker-puppet for docker-puppet-mistral: docker-puppet.sh",
2019-01-17 08:58:30 |         "2019-01-17 08:56:49,167 INFO: 24657 -- Entrypoint checksum for docker-puppet-mistral: 41171bd3e13723c3586b3957418c0bb8  /var/lib/containers/storage/overlay/ee7b8a4c83e204b02e34db795e1ed7f531c879df528af486056c87c55aa86eb8/merged/var/lib/docker-puppet/docker-puppet.sh",
2019-01-17 08:58:30 |         "c1a8039f20b7e915c4f7da9ac77dd1884fb8bc78c4e4ee35f65a15d2d713fc79",
2019-01-17 08:58:30 |         "2019-01-17 08:56:49,220 INFO: 24656 -- podman: Pushing /var/lib/docker-puppet/docker-puppet.sh in container docker-puppet-zaqar",
2019-01-17 08:58:30 |         "2019-01-17 08:56:50,096 INFO: 24656 -- docker-puppet-zaqar: cp /var/lib/docker-puppet/docker-puppet.sh /var/lib/containers/storage/overlay/18b1f91747dcf5d44856a8521ec1bf1bca3f450c6ebfb526a8503ecf5aeeaba3/merged/var/lib/docker-puppet/docker-puppet.sh",
2019-01-17 08:58:30 |         "2019-01-17 08:56:50,114 INFO: 24656 -- Content of /var/lib/containers/storage/overlay/18b1f91747dcf5d44856a8521ec1bf1bca3f450c6ebfb526a8503ecf5aeeaba3/merged/var/lib/docker-puppet for docker-puppet-zaqar: docker-puppet.sh",
2019-01-17 08:58:30 |         "2019-01-17 08:56:50,123 INFO: 24656 -- Entrypoint checksum for docker-puppet-zaqar: 41171bd3e13723c3586b3957418c0bb8  /var/lib/containers/storage/overlay/18b1f91747dcf5d44856a8521ec1bf1bca3f450c6ebfb526a8503ecf5aeeaba3/merged/var/lib/docker-puppet/docker-puppet.sh",
2019-01-17 08:58:30 |         "2019-01-17 08:56:50,320 INFO: 24657 -- Container diff for docker-puppet-mistral: C /var/lib",
2019-01-17 08:58:30 |         "2019-01-17 08:56:50,320 INFO: 24657 -- podman: Start container docker-puppet-mistral",
2019-01-17 08:58:30 |         "2019-01-17 08:56:50,619 INFO: 24656 -- Container diff for docker-puppet-zaqar: ",
2019-01-17 08:58:30 |         "2019-01-17 08:56:50,619 INFO: 24656 -- podman: Start container docker-puppet-zaqar",
2019-01-17 08:58:30 |         "2019-01-17 08:56:58,019 INFO: 24658 -- podman: Creating container docker-puppet-iscsid",
2019-01-17 08:58:30 |         "2019-01-17 08:56:58,134 INFO: 24655 -- podman: Creating container docker-puppet-ironic_inspector",
2019-01-17 08:58:30 |         "2019-01-17 08:57:05,049 INFO: 24654 -- podman: Creating container docker-puppet-nova",
2019-01-17 08:58:30 |         "2019-01-17 08:57:06,662 INFO: 24653 -- podman: Creating container docker-puppet-glance_api",
2019-01-17 08:58:30 |         "15e9c9f7f07ae50979d90ae8bc99a747157278dbba5d1fcf87983acced3896b8",
2019-01-17 08:58:30 |         "2019-01-17 08:57:06,678 INFO: 24658 -- podman: Pushing /var/lib/docker-puppet/docker-puppet.sh in container docker-puppet-iscsid",
2019-01-17 08:58:30 |         "bf38fa325b1a7e343623f0d445ea8e1a4d2763f63545cfd2074f6b8540aa68dd",
2019-01-17 08:58:30 |         "2019-01-17 08:57:06,871 INFO: 24655 -- podman: Pushing /var/lib/docker-puppet/docker-puppet.sh in container docker-puppet-ironic_inspector",
2019-01-17 08:58:30 |         "ae2c2a1968fca547c26ddbbea8746f53e0fb573b2e90204a9355918519a481ad",
2019-01-17 08:58:30 |         "2019-01-17 08:57:06,971 INFO: 24654 -- podman: Pushing /var/lib/docker-puppet/docker-puppet.sh in container docker-puppet-nova",
2019-01-17 08:58:30 |         "2019-01-17 08:57:07,553 INFO: 24655 -- docker-puppet-ironic_inspector: cp /var/lib/docker-puppet/docker-puppet.sh /var/lib/containers/storage/overlay/3845785a6e67fdc80603256a99e7526cac86d7f04f41ffa577e988662a11d931/merged/var/lib/docker-puppet/docker-puppet.sh",
2019-01-17 08:58:30 |         "2019-01-17 08:57:07,553 INFO: 24658 -- docker-puppet-iscsid: cp /var/lib/docker-puppet/docker-puppet.sh /var/lib/containers/storage/overlay/dfe732ae6fed26d8fe6ac1b994093ffee688df80ffaad51dc2102e44125b80e0/merged/var/lib/docker-puppet/docker-puppet.sh",
2019-01-17 08:58:30 |         "2019-01-17 08:57:07,555 ERROR: 24656 -- Failed running docker-puppet.py for zaqar",
2019-01-17 08:58:30 |         "2019-01-17 08:57:07,555 ERROR: 24656 -- unable to start container c1a8039f20b7e915c4f7da9ac77dd1884fb8bc78c4e4ee35f65a15d2d713fc79: container create failed: container_linux.go:336: starting container process caused \"exec: \\\"/var/lib/docker-puppet/docker-puppet.sh\\\": stat /var/lib/docker-puppet/docker-puppet.sh: no such file or directory\"",
2019-01-17 08:58:30 |         ": internal libpod error",
2019-01-17 08:58:30 |         "2019-01-17 08:57:07,555 INFO: 24656 -- Finished processing puppet configs for zaqar",
```
If we take only the info for the failed container:
```
2019-01-17 08:58:30 |         "2019-01-17 08:56:48,287 INFO: 24656 -- podman: Creating container docker-puppet-zaqar",
2019-01-17 08:58:30 |         "2019-01-17 08:56:49,220 INFO: 24656 -- podman: Pushing /var/lib/docker-puppet/docker-puppet.sh in container docker-puppet-zaqar",
2019-01-17 08:58:30 |         "2019-01-17 08:56:50,096 INFO: 24656 -- docker-puppet-zaqar: cp /var/lib/docker-puppet/docker-puppet.sh /var/lib/containers/storage/overlay/18b1f91747dcf5d44856a8521ec1bf1bca3f450c6ebfb526a8503ecf5aeeaba3/merged/var/lib/docker-puppet/docker-puppet.sh",
2019-01-17 08:58:30 |         "2019-01-17 08:56:50,114 INFO: 24656 -- Content of /var/lib/containers/storage/overlay/18b1f91747dcf5d44856a8521ec1bf1bca3f450c6ebfb526a8503ecf5aeeaba3/merged/var/lib/docker-puppet for docker-puppet-zaqar: docker-puppet.sh",
2019-01-17 08:58:30 |         "2019-01-17 08:56:50,123 INFO: 24656 -- Entrypoint checksum for docker-puppet-zaqar: 41171bd3e13723c3586b3957418c0bb8  /var/lib/containers/storage/overlay/18b1f91747dcf5d44856a8521ec1bf1bca3f450c6ebfb526a8503ecf5aeeaba3/merged/var/lib/docker-puppet/docker-puppet.sh",
2019-01-17 08:58:30 |         "2019-01-17 08:56:50,619 INFO: 24656 -- Container diff for docker-puppet-zaqar: ",
2019-01-17 08:58:30 |         "2019-01-17 08:56:50,619 INFO: 24656 -- podman: Start container docker-puppet-zaqar",
2019-01-17 08:58:30 |         "2019-01-17 08:57:07,555 ERROR: 24656 -- Failed running docker-puppet.py for zaqar",
2019-01-17 08:58:30 |         "2019-01-17 08:57:07,555 INFO: 24656 -- Finished processing puppet configs for zaqar",
```
And what's interesting is this:
```"2019-01-17 08:56:50,619 INFO: 24656 -- Container diff for docker-puppet-zaqar: "```

Here, we should see a ```C /var/lib``` after the semicolon (yeah, apparently I have a small issue with the logging, it doesn't show the full diff).

So, apparently, the file isn't properly detected in the container, while we can actually get its md5sum on the mounted container....

Any idea what's going on?

I'll try to work a bit the output of the "podman diff" in order to get its full content on our CI. But that's an interesting thing.

Also, we're still running 6 instances of those commands in parallel. Maybe there's a small issue in podman layer managment?

Cheers,

C.

**Comment by cjeanner** [comment] 2019-01-17 09:59
Taking also the opportunity to point the podman version - yes, it also happens in latest 1.0 release:
```
+ podman version
Version:       1.0.0
Go Version:    go1.10.2
OS/Arch:       linux/amd64


+ podman info
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.14.0-dev, commit: 635328ab9b2058e40335533f35d595604666f1e4-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 867885056
  MemTotal: 8369270784
  OCIRuntime:
    package: runc-1.0.0-57.dev.git2abd837.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 8579125248
  SwapTotal: 8589930496
  arch: amd64
  cpus: 8
  hostname: undercloud.localdomain
  kernel: 3.10.0-957.1.3.el7.x86_64
  os: linux
  rootless: false
  uptime: 42m 41.68s
insecure registries:
  registries:
  - 192.168.24.1:8787
  - 192.168.24.3:8787
registries:
  registries:
  - registry.centos.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 19
  RunRoot: /var/run/containers/storage
```

**Comment by cjeanner** [comment] 2019-01-17 14:31
@mheon it's on the CI, so it's set to "permissive", indeed. I would point to some "commit" part in the container management.

**Comment by cjeanner** [comment] 2019-01-17 14:42
Some more info about the system we're running this, and encountering the issue:
System:
```CentOS Linux release 7.6.1810 (Core)```
CPU:
```8x Intel Xeon E3-12xx v2 (Ivy Bridge, IBRS)```
Installed kernel:
```kernel-3.10.0-957.1.3.el7.x86_64```

**Comment by giuseppe** [comment] 2019-01-17 14:56
can you please show the last version of the script?

**Comment by cjeanner** [comment] 2019-01-17 15:03
@giuseppe the patch is here: https://review.openstack.org/#/c/630287/12/docker/docker-puppet.py

And you can get a peek on the logs here:
http://logs.openstack.org/87/630287/12/check/tripleo-ci-centos-7-standalone/0d547cb/logs/undercloud/home/zuul/standalone_deploy.log.txt.gz#_2019-01-17_09_06_18
(Search for "no such file").

**Comment by rhatdan** [comment] 2019-03-08 15:43
@giuseppe Any progress on this issue?

**Comment by giuseppe** [comment] 2019-03-08 18:28
@rhatdan I still believe it is not in Podman but how the script is created/deleted outside of the container.

Haven't heard anything back for a while and I've never seen this issue anywhere else, so let's close this issue for now, if there is any update we can re-open it.

**Closed by giuseppe** 2019-03-08 18:28 UTC
