### ISSUE TITLE
Tutorial is confused about sudo usage

### ISSUE THREAD

**Issue by QuLogic** [containers/libpod#4250] opened 2019-10-13 06:17 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The [tutorial](https://github.com/containers/libpod/blob/master/docs/tutorials/podman_tutorial.md) seems to be a bit confused about when to use `sudo`. At the start it says we are going to do rootless commands, which is great and exactly what I want. However, starting at the ["Viewing the container's logs" section](https://github.com/containers/libpod/blob/master/docs/tutorials/podman_tutorial.md#viewing-the-containers-logs), everything starts using `sudo`. This makes no sense because root wouldn't see any of these containers. 

**Steps to reproduce the issue:**

Follow the instructions in the [first tutorial](https://github.com/containers/libpod/blob/master/docs/tutorials/podman_tutorial.md).

**Describe the results you received:**
_Every_ command with `sudo` doesn't work and says "no such container" (using either container ID or name.)

When dropping the `sudo`, the checkpointing commands don't work.

**Describe the results you expected:**
All the tutorial steps work.

**Additional information you deem important (e.g. issue happens only occasionally):**
Side note, but the initial container runs httpd, but the sample output for `top` shows nginx.

**Output of `podman version`:**

```
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.5.1-3.fc30.x86_64
```

**Comment by QuLogic** [comment] 2019-10-13 07:38
I just realized my version was outdated, so I updated to the following, though the results are the same:
```
$ podman version
Version:            1.6.1
RemoteAPI Version:  1
Go Version:         go1.12.9
OS/Arch:            linux/amd64
$ rpm -q podman
podman-1.6.1-2.fc30.x86_64
```

**Comment by rhatdan** [comment] 2019-10-13 10:49
@QuLogic Would you be willing to open a PR to fix this?

**Comment by QuLogic** [comment] 2019-10-13 20:42
I can remove `sudo`, but that doesn't fix checkpointing and I don't know how to do that.

**Comment by rhatdan** [comment] 2019-10-14 13:48
Checkpointing only works on rootful containers.

**Comment by TomSweeneyRedHat** [comment] 2019-10-14 14:02
I'm going to close this as a duplicate of #3932.  @ipbabble any progress?

**Closed by TomSweeneyRedHat** 2019-10-14 14:02 UTC
Labels: good first issue, kind/bug
