### ISSUE TITLE
podman exec stdin regression

### ISSUE THREAD

**Issue by yanchenko-igor** [containers/libpod#4326] opened 2019-10-23 10:13 UTC
I discovered a regression bug in podman, since commit a1a79c08b72793cf2f75490d8ffc844c3d16bd4a podman exec does not attach stdin to the command

/kind bug

**Description**

podman doesn't attach stdin to the command when podman exec is used

**Steps to reproduce the issue:**

1.
run a container
podman run --rm --detach --name busybox busybox sleep 60

2.
echo test | podman exec -i busybox cat

**Describe the results you received:**

I receive an empty output

**Describe the results you expected:**

I expect to receive output "test"

**Additional information you deem important (e.g. issue happens only occasionally):**
it works before commit a1a79c08b72793cf2f75490d8ffc844c3d16bd4a

**Output of `podman version`:**

```
podman version 1.6.1
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.1
  podman version: 1.6.1
host:
  BuildahVersion: 1.11.2
  CgroupVersion: v1
  Conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.1, commit: 4dc8bcfec41e10ca760c8e2089474c2843dfd066'
  Distribution:
    distribution: arch
    version: unknown
  MemFree: 2512916480
  MemTotal: 16676732928
  OCIRuntime:
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9
      commit: d736ef14f0288d6993a1845745d6756cfc9ddd5a
      spec: 1.0.1-dev
  SwapFree: 8140279808
  SwapTotal: 8589930496
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: archlinux
  kernel: 5.3.4-arch1-1-ARCH
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: Unknown
    Version: |-
      slirp4netns version 0.4.1
      commit: 4d38845e2e311b684fc8d1c775c725bfcd5ddc27
  uptime: 379h 29m 30.86s (Approximately 15.79 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/igor/.config/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/igor/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 7
  RunRoot: /run/user/1000
  VolumePath: /home/igor/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Name            : podman
Version         : 1.6.1-1
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/libpod
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : cni-plugins  conmon  device-mapper  iptables  libseccomp  ostree  runc  skopeo  btrfs-progs  slirp4netns  libsystemd
Optional Deps   : podman-docker: for Docker-compatible CLI [installed]
Required By     : podman-docker
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 102.76 MiB
Packager        : Bart
Build Date      : Fri Oct 4 14:34:03 2019
Install Date    : Fri Oct 4 15:21:59 2019
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by baude** [comment] 2019-10-23 17:04
@haircommander ptal

**Comment by variadico** [comment] 2019-10-28 06:55
I think I'm also hitting some stdin issues with `exec`. I thought I remember being able to pipe SQL to a container like I do below. But, now I'm not sure if I'm doing something wrong or if I'm running into this bug.

**Steps to reproduce**
```shell
$ sudo podman run --rm --detach --name mypg docker.io/library/postgres:12.0-alpine
2b8a869654ea7978e39767b903a58574bcd9fec61f644e51bb6b2acb51997baf

$ echo 'select 1;' | sudo podman exec -i mypg psql -U postgres
```

**Expected behavior**
I expected `select 1` to be evaluated by Postgres and the result of that query to be printed to stdout.

**Actual behavior**
```
Error: read unixpacket @->/var/run/libpod/socket/edcc49d484e689c71e4f52206859ddd55a591754356bf05412e7015d1f86450a/attach: 
read: connection reset by peer
```

**Other info**
This does work, however.
```
$ sudo podman exec -i --tty mypg psql -U postgres
psql (12.0)
Type "help" for help.

postgres=# 
```

I have the exact same `podman version` and `podman info --debug` as yanchenko-igor.

**Comment by haircommander** [comment] 2019-11-01 13:45
I still wouldn't actually consider this closed

**Comment by variadico** [comment] 2019-11-02 06:12
Retried with podman 1.6.2, yeah, still broken.

**Comment by rhatdan** [comment] 2019-11-02 09:34
@variadico the partial fixes would be in Master not in a released version.  But @haircommander Says it is not fixed yet anyways.

**Comment by rhatdan** [comment] 2019-12-03 04:49
@haircommander Any update?

**Comment by haircommander** [comment] 2019-12-03 13:48
unfortunately not!

**Comment by adrubesh** [comment] 2019-12-26 17:21
Is there any updates to this issue? I'm running into a problem backing up / restoring a mariadb container via:

Backup (Successful): 
`podman exec -it mariadbcontainer mysqldump -u USER -pPASS DATABASE > mybackup.sql`

Restore (Unsuccessful):
`cat mybackup.sql | podman exec -i mariadbcontainer mysql -u USER -pPASS DATABASE`

This is my usual workflow with docker, however, it fails to restore the backup for a podman container.

**Comment by rhatdan** [comment] 2020-01-02 14:47
@mheon Thoughts.

**Comment by mheon** [comment] 2020-01-02 14:53
@rhatdan I view this one as similar in scope to the recent Openstack bug about reusing container names. It's likely a small issue somewhere in the exact details of how Podman and Conmon interact during attach, but identifying the precise where and what exactly is going on are probably going to be very difficult. I'd love to solve this, but I think we'd need a lot of eyes and a fair bit of time blocked off to give it a proper look.

**Comment by lfarkas** [comment] 2020-01-07 13:10
is there any progress with it? without it any database daemon like mysql, mariadb, mongo etc. initialization can't be done when running in a container.

**Comment by mheon** [comment] 2020-01-07 14:56
I'm in the process of reworking `podman attach` for the new apiv2 branch, and I'm hoping to get a fix for this in at the same time since I'm knee-deep in the code already, but I don't want to make promises - we still don't have a 100% certain root cause here.

**Comment by daheise** [comment] 2020-01-08 13:20
I have also encountered this issue while trying to set up a podman custom executor for GitLab CI following this guide: https://tech.immerda.ch/2019/10/gitlab-ci-with-podman/

This line runs and exits, without taking any action: `podman exec "$CONTAINER_ID" /bin/bash < "$1"`

**Closed** 2020-01-09 13:01 UTC
Labels: do-not-close, kind/bug

**Comment by yanchenko-igor** [comment] 2020-01-09 13:44
It works, amazing!

**Comment by pkubatrh** [comment] 2020-01-30 08:49
Can confirm the fix working as well. Hope this gets into Fedora and RHEL soon.

**Comment by lfarkas** [comment] 2020-01-30 09:32
we're waiting to it also...at least someone can make a scratch-build for fedora and rhel-7 then we'd be happy to test them:-)

**Comment by TomSweeneyRedHat** [comment] 2020-02-26 16:23
New related BZ:  https://bugzilla.redhat.com/show_bug.cgi?id=1807379
