### ISSUE TITLE
Starting a systemd container with bind mount has doubled cgroup path mounted

### ISSUE THREAD

**Issue by aalba6675** [containers/libpod#836] opened 2018-05-29 05:09 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
>
> /kind feature

**Description**

Split off from #730 as this relates to starting a container (actually this may be causing #730 as the clean up routine may not be expecting a doubled cgroup path?). Maintainers, please close #730 if this is the real issue.

Starting a systemd-based container with a bind mount (`-v`) creates a doubled cgroup path. By doubled I mean that the sub-path `/libpod_parent/libpod-6cab0d8c9dc817e69fd0c02a7657e9a83edab3903f25f50d758c1511283bbbf0/ctr/` is repeated exactly twice.

**Steps to reproduce the issue:**

1. Run a Fedora 28  container with `CMD=/sbin/init` and a single volume mount like `-v /volumes/podman/test:/home:z`. Before doing this do `mount --make-private /tmp`, otherwise the container won't start up.

2. On the host observe:
```
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-6cab0d8c9dc817e69fd0c02a7657e9a83edab3903f25f50d758c1511283bbbf0/ctr type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)

cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-6cab0d8c9dc817e69fd0c02a7657e9a83edab3903f25f50d758c1511283bbbf0/ctr type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)

cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-6cab0d8c9dc817e69fd0c02a7657e9a83edab3903f25f50d758c1511283bbbf0/ctr/libpod_parent/libpod-6cab0d8c9dc817e69fd0c02a7657e9a83edab3903f25f50d758c1511283bbbf0/ctr type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
```
3.

**Describe the results you received:**
The cgroup path has a doubled sub-path

**Describe the results you expected:**
The cgroup path has only a single subpath from `/libpod_parent/.../ctr`

**Additional information you deem important (e.g. issue happens only occasionally):**

* Requires a systemd based container - any other CMD does not cause this problem
* Requires a single bind mount from the host  - without bind mount the doubling does not occur

**Output of `podman version`:**

```
$ podman version
Version:       0.6.1-dev
Go Version:    go1.10.2
OS/Arch:       linux/amd64

```

**Output of `podman info`:**

```
podman info
host:
  MemFree: 24886456320
  MemTotal: 33667436544
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  hostname: amadeus.zenquark.com
  kernel: 4.16.11-300.fc28.x86_64
  os: linux
  uptime: 1h 25m 10.68s (Approximately 0.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 7
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 5
  RunRoot: /var/run/containers/storage

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by aalba6675** [comment] 2018-05-29 05:13
Also I do not see any `/conmon` mounts at all — is this to be expected?

**Comment by rhatdan** [comment] 2018-05-29 15:47
The double path is caused by oci-systemd-hook mounting the cgroups in the container and then bind mounting on top with a readonly bind mount.

**Comment by thoraxe** [comment] 2018-06-17 01:00
I am seeing this on CentOS 7 with podman 0.6.2 trying to run a CentOS7 systemd container (`quay.io/thoraxe/openshift-centos-samba` specifically)

**Comment by thoraxe** [comment] 2018-06-17 01:20
By the way, on CentOS7:

```
# mount --make-private /tmp
mount: /tmp is not mountpoint or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

**Comment by rhatdan** [comment] 2018-06-20 18:34
You could try
# mount --bind /tmp /tmp
# mount --make-private /tmp
--make-private requires a mount point.

https://github.com/projectatomic/oci-systemd-hook/pull/98 should/might fix this.  I need people to try it out so we can get it merged and a new package out.

**Comment by rhatdan** [comment] 2018-07-13 19:29
@aalba6675 I don't see this anymore with podman 0.7.1.  Are you still seeing it?

**Comment by space88man** [comment] 2018-08-11 03:09
@dwalsh with volume mounts and the latest bunch of RPMs I am still seeing this issue:

podman-0.7.4-4.git80612fb.fc28.x86_64
oci-systemd-hook-0.1.17-3.gitbd86a79.fc28.x86_64

Your directory change to /run/... from /tmp/oci.tmp hasn't make it into oci-systemd-hook-0.1.17-3.gitbd86a79.fc28.x86_64 so we still the the mount propagation issue (shared, needs to be private).

The libpod/parent mounts (single and double) are not cleaned up on container stop.

```
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-790290f6050adda17cd19835db08a62e1c57554aead09ccca41acd1b94c1181c type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-790290f6050adda17cd19835db08a62e1c57554aead09ccca41acd1b94c1181c type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-790290f6050adda17cd19835db08a62e1c57554aead09ccca41acd1b94c1181c/libpod_parent/libpod-790290f6050adda17cd19835db08a62e1c57554aead09ccca41acd1b94c1181c type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
```

**Comment by aalba6675** [comment] 2018-08-11 07:26
@dwalsh with volume mounts and the latest bunch of RPMs I am still seeing this issue:

podman-0.7.4-4.git80612fb.fc28.x86_64
oci-systemd-hook-0.1.17-3.gitbd86a79.fc28.x86_64

Your directory change to /run/... from /tmp/oci.tmp hasn't make it into oci-systemd-hook-0.1.17-3.gitbd86a79.fc28.x86_64 so we still have the mount propagation issue (shared, needs to be private).

The libpod/parent mounts (single and double) are not cleaned up on container stop.

```
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-790290f6050adda17cd19835db08a62e1c57554aead09ccca41acd1b94c1181c type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-790290f6050adda17cd19835db08a62e1c57554aead09ccca41acd1b94c1181c type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-790290f6050adda17cd19835db08a62e1c57554aead09ccca41acd1b94c1181c/libpod_parent/libpod-790290f6050adda17cd19835db08a62e1c57554aead09ccca41acd1b94c1181c type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
```

If the container doesn't use volume mounts the behaviour is good (no cgroups leaking) as beforem

**Comment by aalba6675** [comment] 2018-08-14 03:12
@rhatdan  a data point:

I sprinkled oci-systemd-hook with stat calls to see when the path /sys/fs/cgroup/systemd/libpod_parent/libpod-<container_uuid>/libpod_parent/libpod-<container_uuid> appears:

There is one call to systemdhook.c: bind_mount where /sys/fs/cgroup/systemd is mounted into the overlay.
Before the  call to mount(..MS_BIND) the path does not exist on the host; after the call to mount() the double path appears on the host. I can't imagine how this can happen.

Once again: this only happens with containers that specify other volume mounts with -v ; for a container without host volume mounts the doubled path never appears.

**Comment by rhatdan** [comment] 2018-08-14 11:06
@aalba6675 Did you try the patch I had in oci-systemd-hook?  Does this fix the issue?
https://github.com/projectatomic/oci-systemd-hook/pull/98

**Comment by aalba6675** [comment] 2018-08-14 21:48
@rhatdan I have just tried #98 - some observations:
1. Still seeing `/tmp/oci-systemd-hook.*` issues; /tmp has to be marked private before the container will start.
1. *BUT* I am no longer seeing a doubled path! Only a single path is visible on the host and it is not cleaned up. 

The host sees

```
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-0cebf3cae8d7e554b2647893c5032354b2d843e5052ff7b4a29c28c82ed167c1 type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
```

The container sees

```
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-0cebf3cae8d7e554b2647893c5032354b2d843e5052ff7b4a29c28c82ed167c1 type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
```

When I stop the container, the following remains:

```
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-0cebf3cae8d7e554b2647893c5032354b2d843e5052ff7b4a29c28c82ed167c1 type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
```

is left behind; this however can be undone with an umount command.

**Comment by mheon** [comment] 2018-11-01 16:07
I think this should be a nonissue now (we've removed the need to use `oci-systemd-hook`)

**Closed by mheon** 2018-11-01 16:07 UTC
Labels: bug
