### ISSUE TITLE
rawhide: podman run /no/such/command : hangs

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#4142] opened 2019-09-30 12:03 UTC
The two special-case 126 and 127 commands are now hanging:
```
# podman run alpine /no/such/command
[hangs forever]
# podman run alpine /etc
[same]
```
Interestingly, adding `--log-level=debug` fixes the problem.

The timing (of when this started happening), and the log-level thing, makes me suspect that it's related to #4124 

Rawhide only; cannot reproduce on f30 with runc.

**Comment by edsantiago** [comment] 2019-09-30 12:04
I reported this Friday morning on IRC

**Comment by debarshiray** [comment] 2019-09-30 12:11
I can reproduce this with `podman-1.6.0-0.2.rc2.git9181c65.fc31.x86_64` and `crun-0.9.1-1.fc31.x86_64` on Fedora 31:
```
$ podman run registry.fedoraproject.org/fedora:30 fubar
<stuck>
```

**Comment by mheon** [comment] 2019-09-30 12:32
Not podman remote? Normal Podman?

**Comment by edsantiago** [comment] 2019-09-30 12:35
Correct. I haven't tried podman-remote. This is with root.

Just tried rootless, and *all* podman-run commands hang.

**Comment by mheon** [comment] 2019-09-30 13:02
F30, crun and runc both, things work fine. Has to be v2 related.

**Comment by debarshiray** [comment] 2019-09-30 14:59
I am running 5.3.1-300.fc31.x86_64

**Comment by mheon** [comment] 2019-09-30 15:15
Per discussion in IRC, axe my "v2" comment, it seems like a kernel issue

**Comment by giuseppe** [comment] 2019-09-30 15:17
I don't think the kernel issue is causing this issue, I am not able to reproduce it yet.

The kernel issue seems a new one happening on Rawhide that prevents Podman to work at all: https://bugzilla.redhat.com/show_bug.cgi?id=1757104

**Comment by edsantiago** [comment] 2019-09-30 15:29
Problem introduced between 240095e and f197ebe

**Comment by edsantiago** [comment] 2019-09-30 15:31
...and the diff between those two commits is documentation-only. There is obviously something else going on.

**Comment by edsantiago** [comment] 2019-09-30 15:42
Possibly important difference between the last successful run and first failing one:
```
works: conmon-2.0.0-2.fc32.x86_64
fails: conmon-2.0.2-0.1.dev.git422ce21.fc32.x86_64
```
My VM is hosed, will try to build a new one and downgrade conmon.

**Comment by edsantiago** [comment] 2019-09-30 16:01
It's conmon; or at least the podman-conmon combination:
```
podman \ conmon             |   2.0.0-2  |  2.0.2-0.1.dev.git422ce21
----------------------------+------------+--------------------------
1.5.2-0.59.dev.git7312811   | [untested] | pass
1.6.0-0.36.dev.git01b7af8   | pass       | *HANG*
```
IOW: downgrading conmon resolves the hang.

**Comment by debarshiray** [comment] 2019-09-30 17:25
I have `conmon-2.0.1-1.fc31.x86_64`

**Comment by edsantiago** [comment] 2019-09-30 18:32
Duh, my bad: the reason it passed with podman-1.5.2 is that conmon is bundled. After removing `/usr/libexec/podman/conmon`, results are the same as with podman-1.6: hangs with conmon-2.0.2, ok with conmon-2.0.0

**Comment by haircommander** [comment] 2019-09-30 21:21
problem commit it: https://github.com/containers/conmon/pull/65
@giuseppe can you PTAL? I tried taking a stab at a fix, we are stuck on the waitpid... I guess the cleanup process is hanging?

**Comment by giuseppe** [comment] 2019-10-01 08:45
>  @giuseppe can you PTAL? I tried taking a stab at a fix, we are stuck on the waitpid... I guess the cleanup process is hanging?

I am still struggling trying to reproduce it, reinstalling F31 right now.  I think the waitpid can hang only if the cleanup process doesn't terminate.  If you can easily reproduce the issue, do you see any other podman processes (beside the pause process) lying around?

**Comment by haircommander** [comment] 2019-10-01 13:32
@giuseppe I wasn't able to reproduce either. @mheon gave me access to a VM that could yesterday, and I couldn't see any other running process in `ps aux | grep conmon` which was especially odd. It seemed like the cleanup process did finish but waitpid didn't terminate...

**Comment by debarshiray** [comment] 2019-10-07 22:55
This got fixed.

**Comment by mheon** [comment] 2019-10-07 23:18
Concur, this was fixed in crun

**Closed by mheon** 2019-10-07 23:18 UTC
