### ISSUE TITLE
as a user i want to know if podman pull found new image

### ISSUE THREAD

**Issue by ikke-t** [containers/libpod#2600] opened 2019-03-09 14:36 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

If I do podman pull imagename:latest in script, I can't tell from return value if it found a new image or not. And output is always just list of blobs, which looks the same.

It would be necessary to know if it did downloaded new version, so that pod can be restarted and thus get to run new verion.

Look here for the use case: https://github.com/ikke-t/podman-container-systemd/blob/46d5fd08ef00fba3f6c42e34a69139a30f82a542/tasks/main.yml#L18

**Steps to reproduce the issue:**

1. podman pull jacobalberty/unifi:stable

2.

3.

**Describe the results you received:**

```
$ podman pull nextcloud:latest
Trying to pull docker://nextcloud:latest...Getting image source signatures
Copying blob f7e2b70d04ae [======================================] 21.5MiB / 21.5MiB
Copying blob 744aedb7995c [======================================] 226b / 226b
Copying blob 07afe22f8a58 [======================================] 64.3MiB / 64.3MiB
Copying blob c7bf4f31c4a4 [======================================] 238b / 238b
Copying blob b528e75732cc [======================================] 16.3MiB / 16.3MiB
Copying blob 27e7d214ded2 [======================================] 435b / 435b
Copying blob 894549c23c16 [======================================] 489b / 489b
Copying blob 9aa6d55932b2 [======================================] 11.9MiB / 11.9MiB
Copying blob 1b27fd7479e6 [======================================] 502b / 502b
Copying blob eacdac7d65c9 [======================================] 14.6MiB / 14.6MiB
Copying blob 66f1bd2ad7cf [======================================] 2.2KiB / 2.2KiB
Copying blob ee6444380c18 [======================================] 261b / 261b
Copying blob 1500f6dd9b69 [======================================] 906b / 906b
Copying blob 18560f19c8c4 [======================================] 1.5MiB / 1.5MiB
Copying blob 3da0b71d7146 [======================================] 11.7MiB / 11.7MiB
Copying blob 3820bd8e530e [======================================] 525b / 525b
Copying blob 3eb271d05479 [======================================] 539b / 539b
Copying blob fe98cc3e887d [======================================] 59.3MiB / 59.3MiB
Copying blob 9bfc0c3ccf71 [======================================] 1.9KiB / 1.9KiB
Copying blob 40e368c13955 [======================================] 917b / 917b
Copying config c1d2c267ec [======================================] 18.2KiB / 18.2KiB
Writing manifest to image destination
Storing signatures
c1d2c267ec65acd09c93ac054bfbf8344a2feed763851cbfddf72b9aa41ee272
```

**Describe the results you expected:**

e.g.

* text saying in stdout: image changed
* meaningful return value other than 0

**Comment by ikke-t** [comment] 2019-03-10 17:28
FYI,

docker pull output ends with ```Status: Downloaded newer image for docker.io/ansible/awx_task:latest``` if image was refreshed, and returns 0 in both cases, for what it's worth.

```
[root@ohuska ~]# docker pull ansible/awx_web:latest
Trying to pull repository docker.io/ansible/awx_web ... 
sha256:0ccca278a3219869dcd2646bb828c138cb0469753d1cb2d2bee31d38c3c4e3ab: Pulling from docker.io/ansible/awx_web
a02a4930cb5d: Already exists 
1bdeea372afe: Already exists 
743d55e71777: Already exists 
63bc11d5e943: Already exists 
4f6b45cc1e14: Already exists 
8fbcc770b828: Already exists 
35264fdcec00: Already exists 
ca57668b5d9f: Already exists 
a2d5c3662d6f: Already exists 
59158af4cc8b: Already exists 
856e909f199c: Already exists 
c1aa98b278b8: Already exists 
99aeef84b446: Already exists 
4e16d35eca22: Already exists 
95c26b5b3889: Already exists 
0e9497bd7622: Already exists 
94eda400fe80: Already exists 
851d1f93c344: Already exists 
b5f50c5f5355: Already exists 
d8e375b25fe1: Already exists 
0f80c0493949: Already exists 
709edff13e38: Already exists 
8e497b8239e8: Already exists 
8abbfbc0de85: Already exists 
b7e3ad873246: Already exists 
49e4f1dbe04a: Already exists 
1180093f1f93: Already exists 
80ae636ae7ed: Already exists 
1b6769112ed0: Already exists 
3713b7507693: Already exists 
Digest: sha256:0ccca278a3219869dcd2646bb828c138cb0469753d1cb2d2bee31d38c3c4e3ab
Status: Downloaded newer image for docker.io/ansible/awx_web:latest
[root@ohuska ~]# echo $?
0
[root@ohuska ~]# docker pull ansible/awx_web:latest
Trying to pull repository docker.io/ansible/awx_web ... 
sha256:0ccca278a3219869dcd2646bb828c138cb0469753d1cb2d2bee31d38c3c4e3ab: Pulling from docker.io/ansible/awx_web
Digest: sha256:0ccca278a3219869dcd2646bb828c138cb0469753d1cb2d2bee31d38c3c4e3ab
Status: Image is up to date for docker.io/ansible/awx_web:latest
[root@ohuska ~]# echo $?
0
```

**Comment by vrothberg** [comment] 2019-03-11 11:10
Thanks for opening the issue, @ikke-t! We'll look into it.

**Comment by giuseppe** [comment] 2019-03-11 15:08
you could do:

```
podman pull $IMAGE
ctr_version=$(podman inspect --type container  --format "{{.ImageID}}" $CTR)
img_version=$(podman inspect --type image  --format "{{.Id}}" $IMAGE)

if $test ctr_version != $img_version; then
   .....
fi
```

**Comment by rhatdan** [comment] 2019-03-11 15:15
Well we do have some precedence with podman rm and podman rmi exiting with 1 when the image does not exists.
Theoretically we could exit 0, if it pulls an image.  Exit 1 if the image already exists and no new image was pulled.  Exit 125 if there was a failure to pull.

**Comment by mheon** [comment] 2019-03-11 15:30
The problem is that 1 is still a failure - there are a lot of scripts that probably start with a `podman pull $IMAGE`, and making that fail if the image exists would break them.

I wouldn't mind adding a flag to do this (exit 1 if exists), but we should not make it default.

**Comment by giuseppe** [comment] 2019-03-11 15:31
wouldn't an exit 1 mean an error though?  That is different from `podman rm` where it is an error to specify a container that doesn't exist.
We would need something explicit like `rpm-ostree upgrade --upgrade-unchanged-exit-77`, that means return 77 if there is nothing to upgrade.

**Comment by giuseppe** [comment] 2019-03-11 15:32
same comment at the same time :-)

I'd still suggest using `inspect`.  It is more robust if the image was already updated from another process

**Comment by vrothberg** [comment] 2019-03-11 15:48
I am working on the progress bar messages and will link a PR soon. I am currently testing :)

**Comment by vrothberg** [comment] 2019-03-11 16:06
I opened the necessary CI PR over at Skopeo: https://github.com/containers/skopeo/pull/614

Feel free to have a look at the new behaviour, e.g.:
```
[valentin@nebuchadnezzar skopeo]$ sudo ./skopeo copy docker://nginx:latest containers-storage:nginx:latest
Getting image source signatures
Copying blob d9ef3a1eb792 completed: already exists
Copying blob f7e2b70d04ae completed: already exists
Copying blob 08dd01e3f3ac completed: already exists
Copying config 881bd08c0b completed
Writing manifest to image destination
Storing signatures
```

**Comment by rhatdan** [comment] 2019-04-13 09:43
I believe this is fixed in the current release.

**Closed by rhatdan** 2019-04-13 09:43 UTC
Labels: kind/feature

**Comment by vrothberg** [comment] 2019-04-14 13:32
Yes, this is working now. Thanks for catching up on the issue!
