### ISSUE TITLE
/kind feature: podman-compose analogue of docker-compose

### ISSUE THREAD

**Issue by barseghyanartur** [containers/libpod#3865] opened 2019-08-21 13:15 UTC
/kind feature

**Description**

Introduce ``podman-compose`` as analogue of ``docker-compose``.

**Comment by baude** [comment] 2019-08-21 13:31
@barseghyanartur there are no plans for an exact dupe of docker compose for podman.  we believe people should attempt to use podman generate kube and podman play kube.  we continue development on this feature.

a contributor has also made https://github.com/muayyad-alsadi/podman-compose which i hear people have had decent luck with.

**Comment by rhatdan** [comment] 2019-08-21 13:42
Docker-compose is not a part of Docker, and therefore the core engineering team is not making an effort to support podman-compose a part of podman.  But this is an open source project, I could see us adding a subset of compose to podman, `podman generate compose/podman play compose`.  BUT it would have to be fully supported by the community.  

Our direction (Red Hat) is to make it easy to move from Podman to Kubernetes and plan on investing in these features.

As @baude points out the community project podman-compose might be a place to try out and continue development efforts their.  I would even be willing to move https://github.com/muayyad-alsadi/podman-compose under the github.com/containers framework, if this was something @muayyad-alsadi was interested in.

Our bottom line on this is that we don't want to end up with Red Hat/RHEL supporting the compose language for use with Podman.  The compose use cases are huge and not well constrained, as I understand it.

**Comment by muayyad-alsadi** [comment] 2019-08-21 13:58
> I would even be willing to move https://github.com/muayyad-alsadi/podman-compose under the github.com/containers framework, if this was something @muayyad-alsadi was interested in.

sure, I would be pleased by that.

**Comment by rhatdan** [comment] 2019-08-21 14:02
Is there a way for you to request a move, or should I just create a podman-compose and you can open a PR to it.

**Comment by muayyad-alsadi** [comment] 2019-08-21 14:08
yes, there is, let me click that.

**Comment by barseghyanartur** [comment] 2019-08-21 14:11
@baude, @rhatdan:

Thanks. I see. Thanks for the quick answers. I did took a quick look at ``play kube``.

Nowadays, most of the devs make use of ``docker-compose``. What once used to be a third-party tool, became a core feature of docker and I think it's very well justified.

One way to attract more people to the project is to make it available and usable by larger audience.

If ``play kube`` is the way to orchestrate different containers with ``podman``, it would be good to have that part documented (as in ``moving from docker and docker-compose to podman`` dedicated article/doc section).

Regarding the ``podman-compose``, I have quickly tried it and it failed. I did use it on an existing ``docker-compose.yml`` config. Perhaps that wasn't a right assumption.

I personally think it's really cool to be able to state that docker can be an alias of podman. I think my expectations were partly caused by that statement.

@muayyad-alsadi:

Some guidance on how to use ``podman-compose`` instead of ``docker-compose`` would be great. :)

**Comment by muayyad-alsadi** [comment] 2019-08-21 14:11
I've followed this

https://help.github.com/articles/transferring-a-repository/

![Screenshot from 2019-08-21 17-09-54](https://user-images.githubusercontent.com/1312683/63439430-acecf800-c436-11e9-9093-0839c4ade9a5.png)

and got

![Screenshot from 2019-08-21 17-09-39](https://user-images.githubusercontent.com/1312683/63439412-a494bd00-c436-11e9-90e2-6a23f91fa020.png)

**Comment by muayyad-alsadi** [comment] 2019-08-21 14:17
> Some guidance on how to use podman-compose instead of docker-compose would be great. :)

@barseghyanartur please try devel branch of podman compose on files in `examples/`

for example

```
curl -sSL -o ~/.local/bin/podman-compose https://raw.githubusercontent.com/muayyad-alsadi/podman-compose/devel/podman-compose.py
chmod +x ~/.local/bin/podman-compose
cd example/busybox
podman-compose up
```

**Comment by muayyad-alsadi** [comment] 2019-08-21 14:28
> The target account must not have a repository with the same name, or a fork in the same network.

**Comment by baude** [comment] 2019-08-21 15:01
> Nowadays, most of the devs make use of `docker-compose`. What once used to be a third-party tool, became a core feature of docker and I think it's very well justified.

But as @rhatdan points out, compose is not technically part of the docker core.  I know we are drawing lines here.  Also, if i install docker on latest ubuntu, it doesnt install docker-compose.  Anyways, podman generate and podman play is always being developed as we get input from users.

**Comment by rhatdan** [comment] 2019-08-21 22:29
@muayyad-alsadi I created github.com/containers/podman-compose and made you the administrator, you can checkout it out, copy all of youre content to the new repo and then push it to github.com/containers/podman-compose.

**Comment by muayyad-alsadi** [comment] 2019-08-21 22:50
but in that case I guess we lose issues, history ,...etc.

when I clicked transfer it gave me

> containers/podman-compose already exists and You don’t have the permission to create repositories on containers 

would you please delete that and then fork my repo as user containers?
I hope that would work

https://help.github.com/en/articles/transferring-a-repository

**Comment by muayyad-alsadi** [comment] 2019-08-21 22:52
>  and made you the administrator

it seems I don't have any permission on `containers/podman-compose`

**Comment by muayyad-alsadi** [comment] 2019-08-21 22:53
sorry my bad I did not see the invitation

**Comment by muayyad-alsadi** [comment] 2019-08-21 22:55
it still gives me even after I accepted the invitation to become owner

>  containers/podman-compose already exists and You don’t have the permission to create repositories on containers

**Comment by rhatdan** [comment] 2019-08-22 09:31
@muayyad-alsadi You need to fork the repo, and add your content to it, then open up a PR to containers/podman-compose and we can merge in your code.

**Comment by muayyad-alsadi** [comment] 2019-08-22 10:43
that's now how github transfer work. that's just uploading a fresh code, in that way we lost all stars, issues, forks connections, and no redirect from old repo to new repo   ...etc.

on the other hand if you fork my repo, then if I clicked transfer and you accept my transfer then github will redirect every one to your repo (starts, forks, urls)

**Comment by rhatdan** [comment] 2019-08-22 10:52
Ok lets try that.

**Comment by rhatdan** [comment] 2019-08-22 10:56
I have forked your repo into containers/podman-compose and added you as an admin

**Comment by barseghyanartur** [comment] 2019-08-22 10:56
GitHub transfer is a way to go. Fresh re-upload should not even be considered.

**Comment by barseghyanartur** [comment] 2019-08-22 10:58
Forking is a bad idea. It shall be transferred.

**Comment by barseghyanartur** [comment] 2019-08-22 11:00
https://help.github.com/en/articles/transferring-a-repository

**Comment by vrothberg** [comment] 2019-08-22 11:15
I agree. A transfer will preserve the history etc. which would be very valuable to have.

**Comment by rhatdan** [comment] 2019-08-22 13:45
@muayyad-alsadi I did not see any email?

**Comment by muayyad-alsadi** [comment] 2019-08-22 13:49
very strange

![Screenshot from 2019-08-22 16-46-59](https://user-images.githubusercontent.com/1312683/63519975-8db89e00-c4fc-11e9-9d30-9fe16c4a8054.png)

I'm not sure how you are supposed to accept that or where it's supposed to appear to your.

**Comment by barseghyanartur** [comment] 2019-08-22 13:50
@rhatdan:

Did you check your spam folder? :)

**Comment by itamarst** [comment] 2019-08-31 22:23
Docker Compose just added support for running Docker CLI, instead of using API (https://github.com/docker/compose/pull/6865). This would in theory enable plain old Docker Compose to work with podman, I think?

**Comment by mheon** [comment] 2019-08-31 23:00
That sounds very interesting - worth trying it, definitely

**Comment by muayyad-alsadi** [comment] 2019-08-31 23:04
> in theory enable plain old Docker Compose to work with podman, I think?

It does not work like that.
The main objective of podman-compose is to run unmodified docker-compose files *rootless*. It has to do some changes under the hood to make it work rootless for example, it creates a single pod and share its network namespace and add-host that point the name of the service to localhost which is the shared network namespace.

**Comment by vrothberg** [comment] 2019-09-02 06:58
I am closing this issue since podman-compose now resides at https://github.com/containers/podman-compose. Feel free to continue the conversation here or to move it over to https://github.com/containers/podman-compose.

**Closed by vrothberg** 2019-09-02 06:58 UTC
Labels: kind/feature

**Comment by itamarst** [comment] 2020-01-23 17:48
Docker Compose now supports calling out to Docker CLI, so it's possible Podman would work now... https://www.docker.com/blog/faster-builds-in-compose-thanks-to-buildkit-support/

**Comment by barseghyanartur** [comment] 2020-01-23 18:25
Hey, to ping back, I'm already successfully using podman and podman-compose as docker/docker-compose replacement.
